zed-industries/extensions

.gitmodules
extensions.toml

Pushing as extension as suggested in https://github.com/zed-industries/zed/pull/7616

theme: Add NeoSolarized Zed theme

---

.gitmodules
extensions.toml

theme: Add vscode-dark-plus

---

.gitmodules
extensions.toml

@maxbrunsfeld, if this is all we need to do to migrate over a language's grammar into an extension, I'd be willing to run around and do all the languages we want to move out, if that helped by reducing some of the busy work.

Add nu extension

---

.gitmodules
extensions.toml

Dracula theme

---

extensions.toml

Updated the git submodule after finishing porting / polishing the rest of the catppuccin themes.

Update `catppuccin` theme

---

.gitmodules
extensions.toml

I'm fairly new to language configuration, but I decided to give it a try to check out the new experience of creating Zed extensions by adding support for [the Pkl language](https://pkl-lang.org/).
I couldn't quite figure out how to test it locally with Zed, though.

Add Pkl extension

---

AUTHORING_EXTENSIONS.md

Add section on how to run extensions locally

---

extensions.toml

Updates the `tokyo-night` themes plugin to next version.

Update `tokyo-night` to `v0.0.2`

---

.gitmodules
extensions.toml

Here is the port of the [mellow.nvim](https://github.com/mellow-theme/mellow.nvim) theme to Zed!

Add Mellow theme

---

.gitmodules
extensions.toml

Minimalist dark theme for loosely based on the [rsms Sublime Text theme](https://github.com/rsms/sublime-theme).
https://github.com/mikesun/msun-dark-zed

msun-dark theme

---

.gitmodules
extensions.toml

Add "macOS Classic" theme.

---

extensions.toml

https://github.com/huacnlee/zed-theme-macos-classic/issues/1

Update macos-classic theme for fix error, warning, info color in dark mode

---

.gitmodules
extensions.toml

https://github.com/zed-industries/zed/pull/7977

Add Dockerfile

---

.gitmodules
extensions.toml

https://navi-lang.org
https://github.com/navi-language/zed-navi

Add Navi language extension

---

.gitmodules
extensions.toml

- `Smooth` theme which brings an aesthetically pleasing dark theme with soft pastel colors

Theme: Smooth

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.3
This Pull Request dependency #70, then can work.

macos-classic 0.0.3

---

.gitmodules
extensions.toml

This adds [the Kiselevka theme](https://github.com/kdubrovsky/kiselevka) for Zed

Add Kiselevka theme extension

---

.gitmodules
extensions.toml

Currently I've only ported the dark version!

Add everforest theme

---

.gitmodules
extensions.toml

A custom port of VSCode GitHub Dark Default theme

theme: GitHub Dark Default

---

.gitmodules

This PR fixes the everforest submodule name to match the others.

Fix everforest submodule name

---

.gitmodules
extensions.toml

Changed the `predictive` text to more muted colour.

Bump The Dark Side to `0.2.1`

---

.gitmodules
extensions.toml

I somehow messed things up with git (sorry, git is not my strong side) and it ended up closing the previous PR (https://github.com/zed-industries/extensions/pull/96). However, this PR is final and ready.
Closes https://github.com/zed-industries/zed/issues/5282

Add SQL extension

---

.gitmodules
extensions.toml

Add syntax highlighting and embedding for `.graphql` files.
Originally this was a [PR](https://github.com/zed-industries/zed/pull/7980) to main Zed repo

Add GraphQL extension

---

.gitmodules
extensions.toml

Add `poimandres` theme

---

extensions.toml
package-lock.json

Bump XY-Zed to 0.0.2

---

.gitmodules
extensions.toml

Changed:
- `extensions.toml`
- `.gitmodules`
Added:
- `extensions/new-darcula-z` submodule

Add New Darcula Theme Extension

---

extensions.toml

- fix color saturation on main theme
- add light gray (blue) to comments for monokai theme
- add bordered version

Bump exquisite theme to 0.1.1

---

.gitmodules
extensions.toml

Add Muted theme

---

extensions.toml

Feature request: https://github.com/mikesun/msun-dark-zed/issues/1

Update msun-dark theme with no-bold syntax variants

---

extensions.toml

Updated license and `drop_target.background`

Bump XY-Zed to 0.0.3

---

.gitmodules
extensions.toml

Adds a port of the requested Night Owl theme: https://github.com/zed-industries/extensions/issues/35

Add Night Owl theme

---

extensions.toml

Release notes:
https://github.com/navi-language/zed-navi/releases/tag/v0.0.3

navi 0.0.3

---

extensions.toml

Changed elevated surface background to lighter shade of black to differentiate it better from editor background.

Bump The Dark Side to 0.2.3

---

.gitmodules
extensions.toml

Add GDScript support

---

extensions.toml

[🤿 Update subheader background](https://github.com/zarifpour/xy-zed/commit/ee7a3dc51f42d35593d2412538bd6165f7406819)

Bump XY-Zed to 0.0.5

---

extensions.toml

[✍️ Update write background](https://github.com/zarifpour/xy-zed/commit/810abb066e2c6a1b22e257af1c5952f03e77d83a)

Bump XY-Zed to 0.0.6

---

extensions.toml

Fixes https://github.com/elGusto/night-owlz/issues/1

Bump night-owlz theme to 0.0.2

---

extensions.toml

Release notes:
https://github.com/navi-language/zed-navi/releases/tag/v0.0.4

navi 0.0.4

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml
src/lib/validation.test.js
vite.config.mjs

This PR sets up a test suite using [Vitest](https://vitest.dev/).
To start we have a few tests for our validation functions.

Add some tests for validation

---

extensions.toml

[📜 Update scrollbar & highlighted line](https://github.com/zarifpour/xy-zed/commit/a7772296c1e727899f12be74af9329ba25f29fc7)

Bump XY-Zed to 0.0.7

---

.gitmodules
extensions.toml

Theme: One Hunter 0.0.1

---

.gitmodules
extensions.toml

Added an extension for LaTeX syntax highlighting

Add LaTeX Extension

---

.gitmodules
extensions.toml

Add cosmos theme

---

.gitmodules
package.json
pnpm-lock.yaml
src/lib/git.js
src/package-extensions.js

This PR makes it so the `.gitmodules` file will get sorted by the packaging script.
Next I'll look to enforce this as part of CI.

Sort `.gitmodules` as part of packaging

---

.github/workflows/ci.yml
.gitmodules

This PR adds a CI check to ensure that `.gitmodules` is properly sorted.

Enforce sorted `.gitmodules` in CI

---

.gitmodules
extensions.toml

Add Nix extension

---

.gitmodules
extensions.toml

Add solarized-fp theme

---

.gitmodules
extensions.toml

Add Fish extension

---

extensions.toml

Related to:
https://github.com/dracula/zed/pull/8/files
&
https://github.com/zed-industries/zed/pull/8544

Bump dracula to 0.2.0

---

extensions.toml

[💚 Restore solidity.toml](https://github.com/zarifpour/zed-solidity/commit/0d76629e809c29164aaab587cace639dd8e73875)
Closes https://github.com/zarifpour/zed-solidity/issues/2

Bump Solidity to 0.0.2

---

.gitmodules
extensions.toml

A modest zed theme based on one dark but with brighter colours on a darker background

Add Modest Dark theme

---

extensions.toml

Update GitHub Theme

---

extensions.toml

Bump srcery theme to version 0.0.2

---

extensions.toml

[⏬ Highlight imports](https://github.com/zarifpour/xy-zed/commit/ec86d283866635f056425f4544a25f392f100d29)

Bump XY-Zed to 0.0.8

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.5

macos-classic 0.0.5

---

extensions.toml

Release notes:
https://github.com/navi-language/zed-navi/releases/tag/v0.0.5

navi 0.0.5

---

.gitignore

Ignore bun lockfile: https://bun.sh/docs/install/lockfile

Ignore bun.lockb

---

extensions.toml

[💎 Improve Ruby support](https://github.com/zarifpour/xy-zed/commit/02a19056cf851755c1c580c151bc875284a7216e)
Closes https://github.com/zarifpour/xy-zed/issues/1

Bump XY-Zed to 0.0.9

---

.gitmodules
extensions.toml

A dark Zed theme inspired by my Gentle Dark UI theme created for the Atom editor.

Add gentle dark theme

---

extensions.toml

This version fixes surface background to match theme

Update modest-dark 0.1.1

---

extensions.toml

[🫂 Support more keywords](https://github.com/zarifpour/zed-solidity/commit/1394052dc02c131f120c94ca5426b065559bf8f4)

Bump Solidity to 0.0.3

---

.gitmodules
extensions.toml

A dark Zed theme inspired by my Gentle Dark UI theme created for the Atom editor.

Add the gentle dark theme, take 2

---

.gitmodules
extensions.toml

Siri Dark is based on One Dark but with dark borders and damped purple colors since I find them quite distracting. Siri Light is a light theme with a non white background to save my old tired eyes. 🤓

Add Siri theme

---

extensions.toml

I updated the colorizer theme and fixed some colors

Update colorizer theme to 0.0.2

---

extensions.toml

Add msun-dark-twilight variant

Update msun-dark theme to 0.0.4

---

.gitmodules
extensions.toml

This PR adds a new theme for zed, port of vs code's blanche (https://github.com/shytikov/blanche).

Add blanche theme

---

extensions.toml

- [👷 Color constructor](https://github.com/zarifpour/xy-zed/commit/e54348caf71ed3d08e2374b78d5e18d922b65234)
- [📝 Add example of unidentified](https://github.com/zarifpour/xy-zed/commit/7b73e853ab5ad831fcc684c71f5c749858d8d9a4)

Bump XY-Zed to 0.0.10

---

.gitmodules
extensions.toml

Adds a light and dark [penumbra](https://github.com/nealmckee/penumbra) theme. The themes were ported from vs code using the theme importer in zed.
Closes #45

Add Penumbra theme

---

extensions.toml

- Improved & Fixed Italic keyword

Update colorizer theme to 0.0.3

---

.gitmodules
extensions.toml

Add Nord theme

---

extensions.toml

- Fixes last player color
- Support for tags
- Support for type hints

Upgrade Dracula to 0.4.0

---

.gitmodules
extensions.toml

This includes highlighting, folding, and outlining support.
Closes #204.

Add D language support

---

.gitmodules
extensions.toml

Adds CUE language extension. Fixes: #190
This is my first attempt at creating an extension for Zed and tree-sitter queries, feedback greatly appreciated 🙇🏼‍♂️

Add CUE language extension

---

.gitmodules
extensions.toml

Port of the [Alabaster Sublime Scheme](https://github.com/tonsky/sublime-scheme-alabaster) by Nikita Prokopov for zed editor.

Add Alabaster theme

---

.gitmodules
extensions.toml

This PR adds [Cadence language](https://cadence-lang.org/docs/language) syntax highlighting.

Add Cadence language syntax highlighting

---

AUTHORING_EXTENSIONS.md

This PR updates the docs for authoring extensions to reflect the latest changes in the extension API.

Update docs for authoring extensions

---

extensions.toml

* Update extension to match latest Zed extensions API
* Refactor highlights queries
* Enhance bracket detection
* Define comments syntax

Update Pkl to 0.1.0

---

extensions.toml

Release notes:
https://github.com/pest-parser/zed-pest/releases/tag/v0.1.0

Update pest to 0.1.0

---

.gitmodules
extensions.toml

This PR adds support for the Scala language, based on Metals (Scala LSP).

Add Scala extension

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.6

Update macos-classic to 0.0.6

---

extensions.toml

- Amends git modified to use dracula convention colors (cyan)
- Fixes interaction states on ghost elements
- Adds correct styles for active wrap guides 
- Amends scrollbar to be less janky
- Amends terminal background to be darker
- Amends predictive colors

Update dracula to 0.5.2

---

extensions.toml

Bump Elisp to 0.0.3

---

extensions.toml

- Complete all terminal colors (including .... bright-black ![confused_girl](https://github.com/zed-industries/extensions/assets/7274458/267dfd1e-2e0e-4182-8f2e-93e1bd739cc7))
-  Amends disabled text to be slightly more visible

Update dracula from 0.5.2 to 0.6.0

---

extensions.toml

[🥸 Increase line number visibility](https://github.com/zarifpour/xy-zed/commit/f2a2c39e45be94c00a626f26716eb5f9ec425727)
Closes https://github.com/zarifpour/xy-zed/issues/3

Bump XY-Zed to 0.0.11

---

extensions.toml

Changes:
- change warning and error colors https://github.com/tsimoshka/zed-theme-alabaster/commit/817ab288a9fd3c3952a45776fd6f29316a0ba1cc
- migrate from extension.json to extension.toml https://github.com/tsimoshka/zed-theme-alabaster/commit/53bb59ed23493a88c0ad17ddb93c2dfdf90b1381

Bump Alabaster to 0.0.2

---

.gitmodules
extensions.toml

Dark theme with purple and blue as main colors, as you can see on my Github profile, my favorites :P

Add Indigo theme

---

.gitmodules
extensions.toml

Add starlark extension

---

extensions.toml

Update markdown-oxide to v0.0.4

---

.gitmodules
extensions.toml

Please find detail in repo: https://github.com/pcminh0505/ktrz-monokai-zed-theme
JS: 
Python:
Rust:

Add KTRZ Monokai Theme

---

extensions.toml

- Add Transparency and Blurred capability
- Amend Terminal background color
- Amend ignore files to be more visible
- Adds style for fixed ignore theme property
- Improve Syntax colors to match dracula spec

Dracula 0.6.0 to 0.7.1

---

extensions.toml

Bump catppuccin to 0.2.5

---

extensions.toml

Change PlayerColor for `selection` and `cursor`
| Before | After |
| - | - |
| <img width="323" alt="image" src="https://github.com/zed-industries/extensions/assets/54668379/e0ac1942-4200-4010-948c-f74a53af3a30"> |<img width="332" alt="image" src="https://github.com/zed-industries/extensions/assets/54668379/b8a8486f-560c-4d3f-9282-4be3a8ea5a09">|

Bump KTRZ Monokai to 0.0.2

---

.gitmodules
extensions.toml

This extension starts by adding syntax highlighting for Handlebars/Glimmer files.
Potentially closes #193

Add Ember extension

---

extensions.toml

Related to: zed-industries/zed#4992

Add Emmet extension to the store

---

.gitmodules
extensions.toml

Adds support for typst (typst.app) language with tinymist language server

Add Typst extension

---

.gitmodules
extensions.toml

Monosami | 98% black and white monochrome theme for Zed Editor
https://github.com/borngraced/monosami

Add Monosami theme

---

.gitmodules
extensions.toml

Lox is a toy language introduced in the book [Crafting Interpreters](https://craftinginterpreters.com/). There was already a Treesitter schema written for it so I thought it would be cool to add it to zed. Hopefully future generations of compiler enthusiasts reading that book can use zed to learn how to make compilers from scratch.

Add support for Lox language

---

.gitmodules
extensions.toml

1. Glazier | Phantom
2. Glazier | Deep Space
3. Glazier | Redrum
Early prototype

Add Glazier themes

---

.gitmodules
extensions.toml

Ref issue: https://github.com/zed-industries/zed/issues/9653
----
The negative number is no highlight match, I have made a change to tree-sitter-csv: https://github.com/arnau/tree-sitter-csv/pull/1
I think we can release version v0.0.1 first to use, and then if the tree-sitter-csv accept that PR, I can release a new version.

Add CSV support

---

extensions.toml

Add default `tab_size = 2` setting

Bump elisp to v0.0.4

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.7

Update macos-classic to 0.0.7

---

extensions.toml

Added an extra theme for the new transparent/blurred background feature.

Bump Indigo to 0.1.1

---

.gitmodules
extensions.toml

tmux grammar from https://github.com/Freed-Wu/tree-sitter-tmux

Add tmux extension

---

extensions.toml

Fixed the modified colour to be more prominent.

Bump Dark Side to 0.2.5

---

.gitmodules
extensions.toml

Add Justfile support

---

extensions.toml

Color updates for the blurred version.

Bump Indigo to 0.1.2

---

extensions.toml

Bump KTRZ Monokai to 0.0.3

---

.gitmodules
extensions.toml

Gemini gemtext syntax highlighter.
Tree-Sitter Grammar: https://git.sr.ht/~nbsp/tree-sitter-gemini

Add gemini extension

---

.gitmodules
extensions.toml

Adding a new extension to support [VHS](https://github.com/charmbracelet/vhs) tape files.

Add VHS extension

---

.gitmodules
extensions.toml

Here is a port of an awesome neovim theme Kanagawa.nvim

Add Kanagawa themes extension

---

.gitmodules
extensions.toml

Extension for the Odin language with support for syntax highlighting using `tree-sitter-grammars/tree-sitter-odin` and support for the odin language server (at `DanielGavin/ols`).

Add Odin extension

---

.gitmodules
extensions.toml

Adds a theme based around Dracula, but much darker.
https://github.com/JacobCoffee/blackula?tab=readme-ov-file#readme

Add `Blackula` theme

---

.gitmodules
extensions.toml

This extension adds syntax highlighting for .pica PICA200 assembly files.

Add support for the PICA200 GPU assembly language

---

.gitmodules
extensions.toml

Add Warp One Dark theme for Zed

Publish Warp One Dark theme extension

---

.gitmodules
extensions.toml

Add support for the Docker Compose language server from Microsoft.

Add Docker Compose extension

---

extensions.toml

https://github.com/caius/zed-make/pull/5

Update Make to 1.0.1 for hard-tabs support

---

extensions.toml

Adds changes dropzone transparency to work with the change in https://github.com/zed-industries/zed/pull/10643

Update Zedwaita to v0.0.3

---

.gitmodules
extensions.toml

Improve surface background color

Update Warp One Dark theme

---

.gitmodules
extensions.toml

Closes #145.
:wave: @piechologist there is now [JuliaEditorSupport/zed-julia](https://github.com/JuliaEditorSupport/zed-julia) if you want to collaborate.

Add Julia extension

---

extensions.toml

Thank you @moomerman for the LSP implementation.

Add LSP support for GDScript

---

.gitmodules
extensions.toml

This adds support for AsciiDoc syntax highlighting.
The tree sitter is still WIP, but it works to some extent and it's good to see at least a bit of color in the editor.

Add asciidoc 0.0.1

---

.gitmodules
extensions.toml

Add Quill theme

---

extensions.toml

- Adds type.interface style to theme

Update Dracula 0.9.0 to 0.9.1

---

extensions.toml

Update Quill theme to v0.2.0

---

.gitmodules
extensions.toml

Add struct theme

---

extensions.toml

Update `blackula` to `0.1.1`
- Adjust terminal background color

Update Blackula to 0.1.1

---

.gitmodules
extensions.toml

[Marksman](https://github.com/artempyanykh/marksman) is an LSP for Markdown files.
I hope I've done everything correctly, but if not, please let me know. Thank you.

Add Marksman extension

---

.gitmodules
extensions.toml

Thie extension contains:
- Syntax highlighting
- Language server (intellisense)
for the twig templating language.

Add twig extension

---

.gitmodules
extensions.toml

Adds Rose Pine theme, closes https://github.com/zed-industries/zed/issues/9151
https://github.com/rose-pine/zed

Add rose-pine-theme

---

.gitmodules
extensions.toml

Add a csv extension to solve: #475 
it look like:
At the same time, the tsv extension has been added, They may be merged into the same extension in the future,and I will refine the logic of automatic indentation alignment in the future

Add rainbow-csv extension

---

.gitmodules
extensions.toml

Closes #201
This PR adds support for [Jsonnet][1] language.
[1]: https://jsonnet.org/

Add initial support for Jsonnet language

---

extensions.toml

Update rose-pine-theme to v1.0.4

---

.gitmodules
extensions.toml

https://github.com/x032205/tsar-zed-theme

Add TSAR Theme

---

.gitmodules
extensions.toml

Added Initial support for Blade templating language.(https://github.com/zed-industries/extensions/issues/641)

Add blade templating language 

---

.gitmodules
extensions.toml

A port of the emacs theme of the same name by rexim

Add Gruber Darker theme

---

extensions.toml

Release notes:
https://github.com/navi-language/zed-navi/releases/tag/v0.2.1

Update navi to 0.2.1

---

.gitmodules
extensions.toml

Hi!
I tried myself on the Cucumber/Gherkin extension.
It features 
* tree-sitter grammar (via https://github.com/thlcodes/tree-sitter-gherkin) incl. highlights, outlines and injections for docstrings _(all WIP but working well for (my) daily use)_
* LSP via `@cucumber/language-server` with support for project-settings
This could potentially close #175.
Cheers
Thomas

Add cucumber/gherkin extension

---

.gitmodules
extensions.toml

Added scss language support for Zed(https://github.com/zed-industries/zed/issues/5356)
Note: I have not found any language server for scss yet :(

Add SCSS extension

---

.gitmodules
extensions.toml

This pull request introduces the Snowflake theme, originally developed for Visual Studio Code, to the Zed editor. As the owner and maintainer of the original theme, I've adapted the theme's aesthetics to align with Zed user interface.
I request a review and approval from the zed extensions repository maintainers to merge this theme into the main repository. Feedback and suggestions for further refinement are highly welcome :)

Add Snowflake Theme

---

.gitmodules
extensions.toml

Pick up https://github.com/zed-industries/zed/pull/9902

Add Basher

---

extensions.toml

Update Notes:
- improved the higlighting(based on user feedback)

Update SCSS to v0.0.2

---

extensions.toml

Release notes:
https://github.com/teziovsky/zed-one-hunter-theme/releases/tag/v0.0.4

Update one-hunter to 0.0.4

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.8

Update macos-classic to 0.0.8

---

.gitmodules
extensions.toml

Add syntax highlighting and LSP support for [noir](https://github.com/noir-lang/noir/) language

Add noir extension

---

extensions.toml

Update improves brackets in WIT files.

Update `wit` to v0.2.0

---

extensions.toml

Updates:
- improved highlighting

Update Blade to 0.0.2

---

extensions.toml

Release notes:
https://github.com/valentinegb/zed-wit/releases/tag/v0.3.0

Update wit to 0.3.0

---

extensions.toml

Release notes:
https://github.com/valentinegb/zed-wit/releases/tag/v0.4.0

Update wit to 0.4.0

---

.gitmodules
extensions.toml

A port from https://github.com/EdenEast/nightfox.nvim theme
https://github.com/cange/nightfox.zed

Add Nightfox (nvim) Theme

---

extensions.toml

Improved styling on scrollbars

Update `Le Blackque` 0.0.1 -> 1.0.0

---

.gitmodules
extensions.toml

Add strace extension

---

.gitmodules
extensions.toml

Add nginx extension

---

extensions.toml

Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.1.1

Update Nightfox (nvim) to 0.1.1

---

extensions.toml

Release notes:
- Add code actions to run tests, benchs and program.
https://github.com/navi-language/zed-navi/releases/tag/v0.3.0

Update navi to 0.3.0

---

.gitmodules
extensions.toml

https://github.com/borngraced/monosami

Update monosami to v0.1.0

---

extensions.toml

This PR updates the Kotlin extension to v0.0.3.
This version adds language server support.

Update Kotlin to v0.0.3

---

.gitmodules
extensions.toml

Adds a Verilog/SystemVerilog treesitter grammar and the [Verible language server](https://github.com/chipsalliance/verible).
Closes #170

Add verilog extension

---

.gitmodules
extensions.toml

Update TSAR to 0.0.2

---

extensions.toml

Includes:
- https://github.com/zed-industries/zed/pull/11761

html: bump to 0.0.2

---

.gitmodules
extensions.toml

Fixed format string coloring issues
Added new theme variants Serendipity Midnight

Update serendipity to 0.0.2

---

.gitmodules
extensions.toml

Adding new theme https://github.com/syntaxfm/syntax-zed-theme

Add Syntax.fm theme

---

.gitmodules
extensions.toml

Adds the Aura theme to Zed from https://github.com/daltonmenezes/aura-theme.
This was first requested in #36.

Add Aura theme

---

extensions.toml

https://github.com/zed-industries/zed/pull/12083

html: Bump to 0.1.0

---

extensions.toml

https://github.com/zed-industries/zed/pull/12093

html: Bump to 0.1.1

---

.gitmodules
extensions.toml

https://github.com/zed-industries/extensions/issues/150

Add V extension

---

extensions.toml

Support for https://github.com/zed-industries/zed/pull/12140

Update PHP to v0.0.4

---

.gitmodules
extensions.toml

https://github.com/hichemfantar/halcyon-zed.git
closes #82

Add Halcyon theme

---

.gitmodules
extensions.toml

The popular VSCode `Palenight` theme extension!

Add Palenight Theme

---

extensions.toml

This PR updates the SCSS extension to v0.0.3.

Update SCSS to v0.0.3

---

.gitmodules
extensions.toml
pnpm-lock.yaml

Added UnoCSS LSP extension (https://github.com/zed-industries/extensions/issues/473).

Add UnoCSS extension

---

.gitmodules
extensions.toml

[AutoCorrect](https://github.com/huacnlee/autocorrect) is a linter and formatter to help you to improve copywriting, correct spaces, words, and punctuations between CJK (Chinese, Japanese, Korean).
https://github.com/huacnlee/zed-autocorrect

Add AutoCorrect extension

---

extensions.toml

- Increase visibility of active/inactive wrap guides
- Improve search match background color
- Adds custom colors for document_highlight.read_background/write_background

Update Dracula to 0.9.2

---

.gitmodules
extensions.toml

Adds syntax highlighting for [Exograph](https://exograph.dev/) files

Add Exograph extension

---

.github/workflows/ci.yml
pnpm-lock.yaml

This PR upgrades the version of pnpm used to v9.

Upgrade pnpm to v9

---

package.json
pnpm-lock.yaml

This PR upgrades Vitest to v1.6.0.

Upgrade Vitest to v1.6.0

---

.gitmodules
extensions.toml

Evil Rabbit Theme by @kettanaito

Add evil-rabbit-theme

---

.gitmodules
extensions.toml

This plugin adds Meson syntax highlighting and a language server.
closes #595

Add meson language support extension

---

extensions.toml

d1y/dockerfile.zed#7
Co-authored-by: joshmeads github@joshmeads.com

Update dockerfile to v0.0.4

---

.gitmodules
extensions.toml

Add terrible theme

---

extensions.toml

Release notes:
https://github.com/denix666/zed-theme/releases/tag/v0.0.4

Update denix to 0.0.4

---

.gitmodules
extensions.toml

Update XML extension to 0.0.3

---

extensions.toml

This PR updates the Siri extension to v0.0.4.

Update Siri to v0.0.4

---

.gitmodules
extensions.toml

This theme is a frosted glass style theme. Would love to publish to the extensions store.

Add frosted-theme extension

---

extensions.toml

Changed from extension.json to extension.toml.

Update Siri to 0.0.5

---

extensions.toml

Includes:
- https://github.com/zed-industries/zed/pull/12526
- https://github.com/zed-industries/zed/pull/11879
- https://github.com/zed-industries/zed/pull/12467

Bump php to 0.0.6 and elixir to 0.0.5

---

extensions.toml

This PR updates the Kotlin extension to v0.0.4.
Changes:
- https://github.com/zed-extensions/kotlin/pull/7
- https://github.com/zed-extensions/kotlin/pull/10

Update Kotlin to v0.0.4

---

extensions.toml

Add path_suffixes tmTheme and xcsettings

Update XML to v0.0.5

---

extensions.toml

This includes the following change:
- Allow opt-in to Tailwind LS in string https://github.com/zed-industries/zed/pull/12742

Update Ruby to v0.0.7

---

extensions.toml

This includes the following change:
- astro: Fix Tailwind LS not working in attributes https://github.com/zed-industries/zed/pull/12741

Update Astro to v0.0.3

---

extensions.toml

The new version adds CSS file support

Update Biome to v0.0.7

---

extensions.toml

- Changed automatic code completion color
- Changed git decoration color
- Changed syntax.property color

serendipity: Bump to v0.0.6

---

extensions.toml

See [release notes](https://github.com/cange/nightfox.zed/releases/tag/v0.2.0)

Update Nightfox (nvim) to v0.2.0

---

.gitmodules
extensions.toml

📺 This PR adds the Call trans opt: received. 2-19-98 13:24:18 REC:Log> theme for Zed.
The "Call trans opt: received. 2-19-98 13:24:18 REC:Log>" theme brings the iconic aesthetic of the shell screen from the 1999 film "The Matrix" to your Zed editor. Inspired by the film's opening command "Call trans opt: received. 2-19-98 13:24:18 REC:Log>", this theme offers a unique and immersive visual experience, capturing the nostalgic essence of green phosphor CRT monitors. Available in a dark version, the theme transforms your coding environment with its distinct green-on-black aesthetics.
The "Call trans opt: received. 2-19-98 13:24:18 REC:Log>" is designed to evoke the look and feel of classic CRT monitors, emphasising simplicity and readability. The dark version features a predominantly black …

Add Call trans opt: received. 2-19-98 13:24:18 REC:Log> Theme

---

.gitmodules
extensions.toml

Add the Zed extension for Rego: https://github.com/StyraInc/zed-rego

Add extension for Rego

---

.gitmodules
extensions.toml

Adding preliminar support for the Bend programming language (with a tree-sitter grammar).
(There's no LS yet).

Add Bend support

---

extensions.toml

Release notes:
https://github.com/denix666/zed-theme/releases/tag/v0.0.5

Update denix to 0.0.5

---

.gitmodules
extensions.toml

Hello, I'd like to invite you to integrate my very first theme on Zed! 🙌 
Thanks in advance 🙂

Add Wakfu Theme

---

extensions.toml

- white space coloring adjustment 
- adjust zed collab cursor coloring
- match vscode theme more
- new repo previews

Bump catppuccin to 0.2.8

---

extensions.toml

Finally merged an old PR that adds support for Godot resource files.

Update Godot to v0.2.0

---

extensions.toml

Adds terminal themes and removes deprecated thumb styles

Update leblackque 1.0.0 -> 1.0.1

---

extensions.toml

This PR updates the ChatGPT theme to version 0.1.2.

Update ChatGPT theme

---

extensions.toml

Update ChatGPT theme to v0.1.3

---

extensions.toml

https://github.com/zed-industries/simple-completion-language-server/tree/main
https://github.com/zed-industries/zed/pull/13253

Add snippets extension

---

extensions.toml

Fixes:
https://github.com/zed-industries/zed/pull/13261

snippets: Release 0.0.2

---

extensions.toml

Includes: https://github.com/zed-industries/zed/pull/13265

snippets: Bump to 0.0.3 (more languages)

---

extensions.toml

Includes:
https://github.com/zed-industries/zed/pull/13356

Snippets: Release 0.0.4

---

extensions.toml

Update rainbow CSV to 0.0.3 for support pipe

---

extensions.toml

Includes: https://github.com/zed-industries/zed/pull/13434

snippets: release 0.0.5

---

extensions.toml

add a light theme
removed some deprecated options

Update Terrible Theme to v0.0.3

---

extensions.toml

Update roc to v0.0.6

---

.gitmodules
extensions.toml

This PR adds syntax highlighting for [LilyPond](https://lilypond.org).

Add LilyPond extension

---

.gitmodules
extensions.toml

I forked scss extension and and add more the less support.

Add Less extension

---

extensions.toml

Update `github-copilot-theme` to v0.0.2

---

extensions.toml

Release notes:
https://github.com/trbutler4/zed-cairo/releases/tag/v0.0.3

Update cairo to v0.0.3

---

extensions.toml

- [❌ Add support for error](https://github.com/zarifpour/zed-solidity/commit/5702468ff64c687fbbac6d71f36a154fb24f9e0a)
- [🌐 Add language server](https://github.com/zarifpour/zed-solidity/commit/f303fa5bc686d902efbd1595dd29bb6515f0be26)
> [!Note]
> Updated from `extension.json` to `extension.toml`.

Bump Solidity to v0.1.0

---

.gitmodules
extensions.toml

Adds a theme based on the default monokai pro but with more exciting syntax highlighting.

Add Monokai Theme 

---

extensions.toml

Release notes:
https://github.com/denix666/zed-theme/releases/tag/v0.0.6

Update denix to v0.0.6

---

.gitmodules
extensions.toml

Update dialogs, deprecated variables and other minor improvements

Update ocean-dark-motifs to v0.0.2

---

extensions.toml

@maxdeviant addresses your issue from [here](https://github.com/ssaunderss/zed-tokyo-night/issues/7) and a few other contrast issues

Update tokyo-night to v0.2.0

---

.gitmodules
extensions.toml

https://github.com/sinamombeiny/S-DarkTheme.zed

Add S-DarkTheme extension

---

extensions.toml

This PR updates the Swift extension to v0.3.0.
Changes:
- https://github.com/zed-extensions/swift/pull/9
- https://github.com/zed-extensions/swift/pull/11

Update Swift to v0.3.0

---

extensions.toml

This PR updates the Nix extension to v0.1.0.
Changes:
- https://github.com/zed-extensions/nix/pull/6

Update Nix to v0.1.0

---

.gitmodules
extensions.toml

Added a new editor theme that extends the standard One Dark and will be expanded in the future for a better vue experience

Add One Dark Extended theme

---

extensions.toml

Added the `line_comments` config to make comments work.

Update slim to v1.0.1

---

extensions.toml

[💬 Fix comments](https://github.com/zarifpour/zed-solidity/commit/c297847e59ed8c2a197b2e51d0779f4fc6c924a5)
Fixes https://github.com/zarifpour/zed-solidity/issues/7

Bump Solidity to v0.1.1

---

extensions.toml

- [💬 Support doc comment](https://github.com/zarifpour/xy-zed/commit/c9e9e798d5b63790baf722d874d6273b68ea9f6f)
- [⚙ Use config.toml](https://github.com/zarifpour/xy-zed/commit/a089497fd6d5bbc9e904fa8c23788a369761a5fd)
---
Closes https://github.com/zarifpour/xy-zed/issues/4

Bump XY-Zed to v0.1.0

---

extensions.toml

https://github.com/zed-industries/zed/pull/14176

dart: Release 0.0.3

---

extensions.toml

- [🧵 Update strings](https://github.com/zarifpour/xy-zed/commit/9491c1cc73644471c43304cd37fdc484057f8135)
- [Bump XY-Zed to v0.1.1](https://github.com/zarifpour/xy-zed/commit/591a0e91a0602e038fc4a93401424828f498546c)

Bump XY-Zed to v0.1.1

---

extensions.toml

[🖍️ Improve syntax highlighting](https://github.com/zarifpour/zed-solidity/commit/22d124d0106f9614f34894d6572a718d46bd1ccf)

Bump Solidity to v0.1.2

---

.gitmodules
extensions.toml

[melange-nvim](https://github.com/savq/melange-nvim) port for Zed.

Add Melange theme

---

.gitmodules
extensions.toml

Adds a new theme extension https://github.com/Acepie/OutrunZedTheme

Add outrun theme

---

.gitmodules
extensions.toml

Syntax highlighting support for [dbml](https://github.com/holistics/dbml)

Add dbml extension

---

extensions.toml

- [🗺️ Improve mapping variable highlighting](https://github.com/zarifpour/zed-solidity/pull/10)
- [🔧 Fix function highlights](https://github.com/zarifpour/zed-solidity/pull/11)

Bump Solidity to v0.1.3

---

.gitmodules
extensions.toml

This PR adds language support for QML files.

Add QML language support

---

extensions.toml

This PR updates the Just extension to v0.1.1.
Changes:
- https://github.com/jackTabsCode/zed-just/pull/2
- https://github.com/jackTabsCode/zed-just/pull/5

Update Just to v0.1.1

---

.gitmodules
extensions.toml

The PR adds a Golangci Lint extension that I added yesterday and should address #525 .

Add Golangci Lint extension

---

.gitmodules
extensions.toml

Add env support

---

.gitmodules
extensions.toml

Added a new theme: **[Focus](https://github.com/jigyansunanda/Focus)**. Please find screenshots and all other info in this [github repository](https://github.com/jigyansunanda/Focus).

Add Focus theme

---

.gitmodules
extensions.toml

This extension adds nim Tree-sitters and a Language server to support.

Add Nim extension

---

extensions.toml

v1.0.7 has been released with fixes

Update Rose Pine theme to v1.0.7

---

.gitmodules
extensions.toml

Add syntax highlighting for [Solarized](https://github.com/zed-industries/zed/blob/main/assets/themes/solarized/solarized.json) and [Latte](https://github.com/catppuccin/zed) themes.

Add hex-light-theme

---

.gitmodules
extensions.toml

Adds a new theme https://github.com/dylf/zed-tanuki

Add Tanuki theme extension

---

.gitmodules
extensions.toml

A fork of the [Catppuccin](https://github.com/catppuccin/zed) that includes 2 custom variants.
Repo: https://github.com/jenslys/zed-catppuccin-blur

Add catppuccin-blur theme

---

.gitmodules
extensions.toml

Adds a basic extension for `.ron` files with some syntax highlighting. I am not too sure if this is "complete" or if something else could be added, so if anyone knows more, please feel free to open an issue or PR to my repository and I'll update the extension

Add RON extension

---

.gitmodules
extensions.toml

Add VS Code's Marine Dark theme.

Add Marine Dark theme

---

.gitmodules
extensions.toml

Adds a new theme extension https://github.com/Becker-Theme/zed

Add becker theme

---

.gitmodules
extensions.toml

Language support for [Vala](https://vala.dev/). 
https://github.com/FyraLabs/zed-vala

Add Vala extension

---

.gitmodules
extensions.toml

Add Kubesong theme

---

extensions.toml

This PR updates the nim extension submodule to version 0.0.2 and updates the version in extensions.toml

Update nim extension to version 0.0.2

---

extensions.toml

Closes https://github.com/mauscoelho/zed-mau-themes/issues/1

Update Mau theme to v0.0.3

---

.gitmodules
extensions.toml

Add Awk extension

---

.gitmodules
extensions.toml

- [Repository of the extension](https://github.com/Ph0enixKM/zed-amber-extension)
- [Repository of the tree sitter](https://github.com/amber-lang/tree-sitter-amber)
- [Repository of the language](https://github.com/amber-lang/amber)
- [Link to the official website](https://amber-lang.com)
Since this is a relatively new programming language, we're still working on LSP and plan to add it's support soon. For now this extension features syntax highlighting with intelligent bracketing.

Add Amber Extension

---

.gitmodules
extensions.toml

This is a port of the [Ember Color Scheme](https://plugins.jetbrains.com/plugin/12401-ember-color-scheme) plugin from IntelliJ IDEs

Add Ember Theme

---

extensions.toml

latex: Bump to v0.0.3

---

extensions.toml

https://github.com/zed-industries/zed/pull/14198

Add Ruff extension

---

extensions.toml

Many Small Updates to fix contrast/color issues as well as updating the extension description for the new repo
<table>
<tr>
<td>Old</td>
<td>New</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/48a73da9-c5ec-47b6-81b2-36228487fa00" width="500"></td>
<td><img src="https://github.com/user-attachments/assets/3cdf4f27-b347-47a6-87b2-d93a905d1958" width="500"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0c8807b4-947a-400f-aa29-46411a7b34b8" width="500"></td>
<td><img src="https://github.com/user-attachments/assets/c868c7f2-be23-4555-a89f-bbac4dc1813b" width="500"></td>
</tr>
</table>

Update Ember Theme to v0.6.0

---

extensions.toml

Added experimental windows compatibility.

Update GDScript to v0.3.1

---

.gitmodules
extensions.toml

This is a mainly port of the [Panda Syntax Theme](https://github.com/PandaTheme/atom-panda-syntax). It has a Light variant and [Nebula](https://github.com/eating-coleslaw/vscode-nebula-theme) inspired variant as well.
<table>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/panda-theme-zed/raw/main/assets/panda.png" width="500"></td>
<td><img src="https://github.com/bIaqat/panda-theme-zed/raw/main/assets/panda-light.png" width="250"></td>
</tr>
<tr>
<td><img src="https://github.com/bIaqat/panda-theme-zed/raw/main/assets/panda-nebula.png" width="250"></td>
</tr>
</table>
I think this could close #87 as the dark variant is based off of the one requested.

Add Panda Theme

---

.gitmodules
extensions.toml

This theme based on the theme used on the [moonscript website](<https://moonscript.org/>). Comes with 3 Variants.
<details>
<summary>Other Variants</summary>
</details>

Add Yue Theme

---

.gitmodules
extensions.toml

Add EJS extension

---

.gitmodules
extensions.toml

This theme is a port of the default Mariana and Breakers theme in Sublime Text 4 (closes #642). This also comes with a variant based of off the [Mariana Pro Warm](https://arc.net/l/quote/erujorqf) Vscode Theme.
<table>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/mariana-theme-zed/raw/main/assets/mariana.png" width="500"></td>
<td><img src="https://github.com/bIaqat/mariana-theme-zed/raw/main/assets/mariana-breakers.png" width="250"></td>
</tr>
<tr>
<td><img src="https://github.com/bIaqat/mariana-theme-zed/raw/main/assets/mariana-trench.png" width="250"></td>
</tr>
</table>

Add Mariana Theme

---

extensions.toml

Includes: https://github.com/zed-industries/zed/pull/15001

Ruff: Bump to 0.0.2

---

extensions.toml

Release notes:
https://github.com/denix666/zed-theme/releases/tag/v0.0.8

Update denix to v0.0.8

---

extensions.toml

Update modest-dark to fix scrollbar colours

Update modest-dark to v0.1.2

---

.gitmodules
extensions.toml

Updated the version number from 0.1.1 to 0.1.2
Changes:
- Fixed the attribute color being the same as JSX component tag color

Update Monospace theme to v0.1.2

---

.gitmodules
extensions.toml

Adding the first version of the Ada language support extension.
Provide syntax highlighting only for now.

Add Ada extension

---

extensions.toml

Bumping Panda, Mariana, Yue, and Tomorrow to their next version
Tomorrow v 0.6.0 (Terminal Highlight Fixes, Button Backgrounds Now More Translucent)
<details>
<summary>Panda v 0.6.0 (Terminal Highlight Fixes, Made background lighter on Light variant)</summary>
<table>
<tr>
<td>Old</td>
<td>New</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/99da937d-35b4-4b64-aed1-7c7596f3d8e2" width="500"></td>
<td><img src="https://github.com/user-attachments/assets/a0a1e3ab-2ae3-4d43-8e3f-177282e75d2b" width="500"></td>
</tr>
</table>
</details>
<details>
<summary>Mariana v0.7.0 (New Variant Mariana Sublime based off specific request, Terminal Highlight Fixes)</summary>
<table aligns="center">
<tr>
<td>New Variant</td>
</tr>
<tr>
<td><img …

Bump Panda, Mariana, Yue, and Tomorrow Themes

---

extensions.toml

Adds folds for transactions in ledger files

Update ledger extension to v0.1.0

---

.gitmodules
extensions.toml

<table>
<tr>
<td rowspan="2"><img src="https://github.com/user-attachments/assets/87a906b3-d1b6-46b0-8ea1-3d770ba5719a" width="450"></td>
<td><img src="https://github.com/user-attachments/assets/1bcd6ff2-707a-4a79-819b-a35c885da3fd" width="250"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/68bf5b66-01b1-487d-a52b-c4d0969c1816" width="250"></td>
</tr>
</table>

Add Aquarium Theme

---

.gitmodules
extensions.toml

Adds an extension to enable support for the [Aiken](https://aiken-lang.org) smart contract programming language
- syntax highlighting
- lsp

Add Aiken language extension

---

.gitmodules
extensions.toml

Add Cyan Light Theme

---

.gitmodules
extensions.toml

Add VSCode Dark High Contrast Theme

---

extensions.toml

Update graphql extension to v1.0.0
- Add GraphQL language server with auto-completion and documentation support. Thanks @affanshahid

 Update GraphQL extension to v1.0.0

---

.gitmodules
extensions.toml

Adding gruvbox material colorscheme

Add Gruvbox Material Theme

---

.gitmodules
extensions.toml

fix: light theme ghost element selected contrast

Update monosami to v0.1.1

---

.gitmodules
extensions.toml

Zedrack is a Vim-insipred strong-contrast transparent theme.
https://github.com/foorack/zed-theme

Add Zedrack Theme

---

extensions.toml

This PR updates the LilyPond extension to v0.0.2.

Update LilyPond extension to v0.0.2

---

extensions.toml

- Changed tab/top and bottom bar/border styles
- Added missing highlights
- Change contrast ratio
- Added new variant (Eclipse)
<table>
<tr>
<td> Old </td>
<td> New </td>
</tr>
<tr> <td rowspan="2"><img src="https://github.com/user-attachments/assets/d42676f9-3d08-44cc-ae5b-8bf00f3d7485" width="500"></td>
<td><img
src="https://github.com/user-attachments/assets/131352b6-a74b-44a7-b3bc-d15a8652415c" width="500"></td>
</table>
<img
src="https://github.com/bIaqat/yue-theme-zed/raw/main/assets/yue-eclipse-bg.png" width="300">

Update Yue Theme to v1.0.0

---

.gitmodules
extensions.toml

16 Flavors of a theme for recreational programmers heavily inspired by the [Gruber](https://github.com/rexim/gruber-darker-theme) emacs theme.
<details>
<summary>Flavors
</summary>
<table>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/gruber-theme-zed/raw/main/assets/gruber-dark-banana.png" width="450"></td>
<td><img src="https://github.com/bIaqat/gruber-theme-zed/raw/main/assets/gruber-light-banana.png" width="450"></td>
</tr>
</table>
<table>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/gruber-theme-zed/raw/main/assets/gruber-dark-apple.png" width="450"></td>
<td><img src="https://github.com/bIaqat/gruber-theme-zed/raw/main/assets/gruber-light-apple.png" width="450"></td>
</tr>
</table>
<table>
<tr>
<td rowspan="2"><img …

Add Gruber Flavors Theme

---

.gitmodules
extensions.toml

Add Quiet Light Theme

---

extensions.toml

Update Nord dark theme to v0.0.7

---

extensions.toml

Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.4

Update one-dark-pro to v0.0.4

---

extensions.toml

Includes https://github.com/zed-industries/zed/pull/15866/

Bump Gleam, HTML, PHP for new annotation queries

---

extensions.toml

Fixes indentations, and changes to README

Update GDScript to v0.3.3

---

extensions.toml

This pull request updates the vscode-dark-modern theme from `v0.0.3` to `v0.0.4`/
- Add some colors by @nikeee in https://github.com/kcamcam/vscode_dark_modern.zed/pull/1
- Update git status colors by @2zqa in https://github.com/kcamcam/vscode_dark_modern.zed/pull/7
- Use generated values by @2zqa in https://github.com/kcamcam/vscode_dark_modern.zed/pull/8
- Add missing colors by @2zqa in https://github.com/kcamcam/vscode_dark_modern.zed/pull/5

Update vscode-dark-modern to v0.0.4

---

.gitmodules

Hi there! @grndctrl, the original author of the Godot/GDScript language support extension, transferred the repository. I'll be the new maintainer moving forward. This PR updates the submodule path to match the new repository location. Please let me know if you need me to do anything else. Thanks!

Update GDScript submodule URL following extension repository transfer

---

.gitmodules
extensions.toml

Adding basic syntax highlighting support and c3-lsp.

Add C3 extension

---

extensions.toml

Reduced background translucency

Update Ultimate Dark Neo to v0.0.5

---

extensions.toml

This PR updates the LilyPond extension to v0.0.3.

Update LilyPond extension to v0.0.3

---

extensions.toml

Release notes:
https://github.com/xqsit94/zed-xqsit-theme/releases/tag/v0.1.3

Update exquisite theme to v0.1.3

---

.gitmodules
extensions.toml

This is a port of [aylin](https://github.com/AhmedAbdulrahman/aylin-vscode-theme) as well as a variant based off [aylin.vim](https://github.com/AhmedAbdulrahman/aylin.vim).
<table>
<tr>
<td rowspan="1"><img src="https://github.com/bIaqat/aylin-theme-zed/raw/main/assets/aylin.png" width="500"></td>
<td><img src="https://github.com/bIaqat/aylin-theme-zed/raw/main/assets/aylin-selene.png" width="500"></td>
</tr>
</table>

Add Aylin Theme

---

extensions.toml

- To fix syntax highlighting issues.
- To add language server support.

Bump ada to v0.2.0

---

.gitmodules
extensions.toml

Add TSARCASM theme

---

extensions.toml

Updates: `Added Dark themes`
-----
> Itg Dark gold
> Ayu Mirage

Update Hex light theme to v0.0.2

---

extensions.toml

Introduces support for a new `trust` keyword that is being added in the upcoming language release.

Update Amber extension to v0.1.1

---

.gitmodules
extensions.toml

LTeX LSP implements a language server
according to the Language Server Protocol (LSP)
and provides grammar and spelling errors
in markup documents: LATEX, Markdown, etc..
The documents are checked with LanguageTool.
This is how it works in action:
See also:
- https://github.com/valentjn/ltex-ls

Add LTeX extension

---

.gitmodules
extensions.toml

Add Nebula Pulse theme 0.0.1
https://github.com/foxoman/nebula-pulse-zed-theme

Add Nebula Pulse theme

---

.gitmodules
extensions.toml

Adds syntax highlighting to `.http` files.

Add http extension

---

extensions.toml

Changes in this release:
- feat: add ability to change the language server remote host and port
- feat: add outline support
- improvement: add support for angular brackets
- fix: fix indentation being lost after code blocks and line losing indentation when inserting a line above

Update gdscript to v0.4.0

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.1.0

Update macos-classic to v0.1.0

---

.gitmodules
extensions.toml

Updating highlighting and tree sitter hash

Update C3 to v0.0.2

---

extensions.toml

Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.5

Update one-dark-pro to v0.0.5

---

extensions.toml

Update Adwaita Pastel Theme to include new `title_bar.inactive_background` colour.

Update Adwaita Pastel Theme to v0.0.2

---

.gitmodules
extensions.toml

This pull request adds the Atomize theme as a submodule to the Zed repository.

Add atomize theme

---

.gitmodules
extensions.toml

Bitbake language support (Requested at #727)
Repository: https://github.com/anikinmd/zed_bitbake
Support for Bitbake syntax.
- Tree Sitter: [tree-sitter-bitbake](https://github.com/tree-sitter-grammars/tree-sitter-bitbake)
- Language Server: [language-server-bitbake](https://github.com/yoctoproject/vscode-bitbake)

Add bitbake extension

---

.gitmodules
extensions.toml

PR Oxocarbon IBM Carbon theme
[![Version](https://img.shields.io/badge/version-1.0.0-blue.svg)](https://github.com/Takk8IS/oxocarbon-theme-for-zed)
[![Licence](https://img.shields.io/badge/licence-CC--BY--4.0-green.svg)](https://creativecommons.org/licenses/by/4.0/)
[![GitHub issues](https://img.shields.io/github/issues/Takk8IS/oxocarbon-theme-for-zed.svg)](https://github.com/Takk8IS/oxocarbon-theme-for-zed/issues)
[![GitHub stars](https://img.shields.io/github/stars/Takk8IS/oxocarbon-theme-for-zed.svg)](https://github.com/Takk8IS/oxocarbon-theme-for-zed/stargazers)
The "Oxocarbon Theme for Zed" brings the sleek, modern aesthetics inspired by IBM Carbon Design System to your Zed editor. This theme is meticulously crafted to offer a refined and professional visual experience, available in …

Add Oxocarbon IBM Carbon theme

---

.gitmodules
extensions.toml

Add https://github.com/rgbkrk/python-lsp-zed-extension as another Python LSP option. Motivated by requests and pain points in https://github.com/zed-industries/zed/issues/7296.

Add pylsp extension

---

extensions.toml

This PR updates the LilyPond extension to v0.0.4.

Update LilyPond extension to v0.0.4

---

.gitmodules
extensions.toml

[Snakemake](https://snakemake.readthedocs.io/en/stable/) is a workflow management system similar to Makefiles widespread in science, especially bioinformatics.
This extension extends Zed to handle Snakefiles.

Add snakemake extension

---

extensions.toml

This PR updates the jsonnet extension to the latest version v0.2.0

Update jsonnet extension to v0.2.0

---

.gitmodules
extensions.toml

Adds [iceberg](https://github.com/cocopon/iceberg.vim/) theme to zed extensions.

Add Iceberg Theme

---

.gitmodules
extensions.toml

Updating Vale to v0.0.2 make it executable after downloading the binary.

Update vale to v0.0.2

---

.gitmodules

This repo was transferred over to me so I've updated the submodule path

Update path to Cobalt2 theme

---

extensions.toml

Increases visibility of suggestions thanks to @jaybrueder 🎉

Bump `tokyo-night` to v0.4.0

---

extensions.toml

Bump playdate extension to v0.1.1

---

.gitmodules
extensions.toml

Add Relay extension

---

extensions.toml

Fixed scrollbar track caused by new Zed update

Update modest-dark to v0.1.3

---

extensions.toml

Forgot to bump the module version numbers [last time](https://github.com/zed-industries/extensions/pull/1234) so none of the updates showed (my fault)
Bumping Aquarium, Aylin, Cyan-Light, Ember, Gruber, Panda, Polar, Quiet Light, Tomorrow, and Yue themes to next version
- Added Indent Colors to all themes auto generated from the terminal colors as well 
- Added indent colors for the non rainbow indent guides
- Fixed element.highlight colors
- Fixed the AI modified/deleted code colors
<table>
<tr>
<td>Old</td>
<td>New</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/42b313e4-8f65-41a3-bbee-9531cbe29869" width="500"></td>
<td><img src="https://github.com/user-attachments/assets/ded41ccc-440b-439a-8d85-a82bca92204f" width="500"></td>
</tr>
<tr>
<td><img …

Bump various themes to next version

---

extensions.toml

Fix typo in the url in the extension.toml

bitbake: Update to v0.0.2

---

extensions.toml

- Improved highlighting
- Improved intelligence
- Outline support

Update SCSS to v0.0.4

---

.gitmodules
extensions.toml

Add wakatime extension

---

extensions.toml

New features:
- bibtex grammar
- better highlighting with available themes
- additions to language injections (lua and sagemath)
- brackets
- expose texlab configurations to workspace settings

Update LaTeX to v0.0.5

---

extensions.toml

This PR updates the nim extension submodule to version 0.0.3 and updates the version in extensions.toml

Update nim extension to v0.0.3

---

.gitmodules
extensions.toml

Referenced [here](https://x.com/_laurynas/status/1829511925077811289)
This extension allows querying traces stored in the local [Fiberplane Studio](https://fiberplane.com) in the Assistant panel.

Add extension for Fiberplane Studio

---

extensions.toml

Release notes:
https://github.com/trbutler4/zed-cairo/releases/tag/v0.0.5

Update cairo to v0.0.5

---

.gitmodules
extensions.toml

C++2 as implemented by the [cppfront](https://github.com/hsutter/cppfront) compiler.

Add cpp2 extension

---

.gitmodules
extensions.toml

Martianized is a red and brown dark color scheme

Add Martianized color scheme

---

extensions.toml

Changes to some of the used models, simplifying the extension a little bit.

Update Fiberplane Studio extension to v0.1.1

---

extensions.toml

Update biome extension to v0.1.2

---

.gitmodules
extensions.toml

Add support for the [Typos Language Server](https://github.com/tekumara/typos-lsp).
Typos is a spell checker, this extension will help having a bit of spell checking available while waiting for https://github.com/zed-industries/zed/issues/5305

Add typos extension

---

extensions.toml

Changelog: https://github.com/lv37/zed-v/compare/v0.2.0...v0.3.0

Update V to v0.3.0

---

extensions.toml

just updated the aiken extension to the latest version

Update Aiken to v1.0.0

---

extensions.toml

This PR updates the nebula-pulse extension submodule to version 0.0.3 and updates the version in extensions.toml

Update nebula-pulse theme extension to v0.0.3

---

.gitmodules
extensions.toml

<b>A darkened variant with enhanced contrast of One Dark theme</b>
[Repository](https://github.com/pavles6/one-dark-darkened)
Preview:

Add One Dark Darkened theme

---

extensions.toml

Replaced tree-sitter to a newer version and improved syntax highlighting

Update Bitbake to v0.0.3

---

.gitmodules
extensions.toml

Minimal, easy on the eyes theme inspired by [flatwhite syntax](https://github.com/biletskyy/flatwhite-syntax) from Atom

Add Flat Theme

---

extensions.toml

- Added new dark ember variants (one background blurred)
- Added minimal versions for missing variants
Updates Preview:

Bump Ember & Tomorrow Theme to v0.9.0

---

extensions.toml

Update github-theme to v0.1.0

---

.gitmodules
extensions.toml

Since it's been requested I'm adding the theme shown in this issue https://github.com/zed-industries/zed/pull/16747#issue-2483038581

Add Monokai Reversed theme

---

extensions.toml

Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.7

Update one-dark-pro to v0.0.7

---

extensions.toml

Fixed this https://github.com/mikasius/zed-nord-theme/issues/11

Update Nord to v0.0.9

---

extensions.toml

Update github-theme to v0.1.1

---

.gitmodules
extensions.toml

DevceTree language support 
Tree-sitter: https://github.com/joelspadin/tree-sitter-devicetree
LSP: https://github.com/igor-prusov/dts-lsp

Add DeviceTree extension

---

extensions.toml

Add colors to error and warning popups.

Update Melange theme to v0.0.4

---

.gitmodules
extensions.toml

Tree-sitter support for https://flatbuffers.dev

Add FlatBuffers language extension

---

.gitmodules
extensions.toml

[The First HTML LSP That Reports Syntax Errors](https://kristoff.it/blog/first-html-lsp)

Add superhtml extension

---

extensions.toml

This PR updates the nim extension submodule to version 0.0.4 and updates the version in extensions.toml

Update nim extension to v0.0.4

---

extensions.toml

Release notes:
https://github.com/clseibold/zed-odin/releases/tag/v0.1.1

Update odin to v0.1.1

---

extensions.toml

This PR updates the LilyPond extension to v0.0.5.

Update LilyPond extension to v0.0.5

---

.gitmodules
extensions.toml

- [elliotfontaine/zed-cylc](https://github.com/elliotfontaine/zed-cylc) (Extension)
- [elliotfontaine/tree-sitter-cylc](https://github.com/elliotfontaine/tree-sitter-cylc) (Grammar)
- [cylc/cylc-flow](https://github.com/cylc/cylc-flow) (Supported)

Add Cylc language extension

---

.gitmodules
extensions.toml

This time everything is alright, so it has to pass finally all the checks.

Add vscode-classic-theme

---

extensions.toml

discord-presence: Update to v0.2.1

---

.gitmodules
extensions.toml

Hi! Here's my Vercel light and dark theme!

Add Vercel Theme

---

.gitmodules
extensions.toml

This PR adds support for FSM, a new language to describe typed state machines for ECMAScript.

Add FSM extension

---

.gitmodules
extensions.toml

Ported Twilight theme from Textmate.

Add Twilight theme

---

.gitmodules
extensions.toml

I could not find a more contrasty light theme for Zed, so I have created a port of the TextMate Eiffel theme for myself, and I thought others could use it too.
I'm happy to make any changes to get this acceptable for merging, let me know!

Add Eiffel theme

---

.gitmodules
extensions.toml

Heavily inspired by https://marketplace.visualstudio.com/items?itemName=nichabosh.minimalist-dark.
Very easy on eyes and helps on concentration!
https://github.com/aerendem/oasis-zed-theme

Add Oasis theme

---

extensions.toml

zed-extensions/java#7 was merged 🥳

Bump Java to v1.0.0

---

.gitmodules
extensions.toml

Ported one of my favourite [VS Code themes](https://github.com/kenziebottoms/vscode-theme-replicant) over to Zed, so the whole world can use it :)

Add Replicant theme

---

extensions.toml

PR Update Hacker Night Vision theme
The theme includes two primary variants:
The "Hacker Night Vision" is designed to provide a clean and focused coding experience. Inspired by the sleek and covert aesthetics of secret agency operating systems, this theme brings a sense of mystery and sophistication to your workspace. The dark version features a vibrant black background with greyscale text, creating a stark contrast that's easy on the eyes. The light version inverts this palette, offering a bright background with dark text for those who prefer a lighter aesthetic. Both versions maintain a consistent monochromatic scheme that enhances readability and reduces distractions during long coding sessions.

Update Hacker Night Vision theme to v2.0.0

---

.gitmodules
extensions.toml

I've been using [Mosel](https://github.com/Domeee/mosel.nvim) in neovim for a long time - figured it would be a good idea to port it to Zed :)

Add Mosel theme

---

.gitmodules
extensions.toml

Adds a new dark theme which is essentially a port of the one that I created for [Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=devzaidi.batman)
https://github.com/devzaidi/batman-theme-zed

Add The Batman theme

---

.gitmodules
extensions.toml

- Add Firebase Security Rules language extension v0.0.1

Add Firebase Security Rules language extension

---

.gitmodules
extensions.toml

- https://github.com/zed-industries/zed/pull/19098
- https://github.com/zed-extensions/ruby/pull/1
- https://github.com/zed-extensions/ruby/pull/2

ruby: Bump to version 0.2.2

---

extensions.toml

See: https://github.com/zed-industries/zed/pull/19249

Update Astro to v0.1.1

---

extensions.toml

See:
- https://github.com/zed-industries/zed/pull/19250

Update Elixir to v0.1.0

---

extensions.toml

- https://github.com/zed-industries/zed/pull/19251

Update HTML to v0.1.3

---

extensions.toml

- https://github.com/zed-industries/zed/pull/19252

Update Zig to v0.3.1

---

.gitmodules
extensions.toml

Add material theme for Zed, inspired by Mattia Astorino's Material Theme for [Visual Studio Code](https://github.com/material-theme/vsc-material-theme).

Add material theme

---

.gitmodules
extensions.toml

- Adding dark, light and dawn inspired variations of the Ariake themes
[Preview available](https://github.com/artivilla/zed-ariake-theme)

Add Ariake theme extension

---

.github/workflows/ci.yml

- See: https://github.com/zed-industries/zed/issues/19351

ci: Stop running CI on forks

---

extensions.toml

- https://github.com/zed-extensions/java/pull/15
Full changelog: https://github.com/zed-extensions/java/compare/v2.0.0...v2.1.0

java: Bump to v2.1.0

---

.github/workflows/danger.yml
dangerfile.ts
package.json
pnpm-lock.yaml

This PR sets up Danger to help manage incoming PRs.
One of its responsibilities will be to warn PR authors when they haven't touched `extensions.toml`:

Setup Danger

---

.gitmodules
extensions.toml

Requested port of [Nordic VSCode](https://marketplace.visualstudio.com/items?itemName=bonchol.nordic-vscode) theme.

Add Nordic Theme

---

.gitmodules
extensions.toml

Requested theme based off of the theme used on the [tailwind docs](https://tailwindcss.com/)

Add Tailwind Syntax Theme

---

.gitmodules
extensions.toml

A requested theme based off of the theme used on [v0.dev/chat](https://v0.dev/chat)
Includes light variant as well

Add v0 Theme

---

extensions.toml

Release notes:
https://github.com/tsoj/zed-cpp2/releases/tag/v0.1.0

Update cpp2 to v0.1.0

---

.gitmodules
extensions.toml

A very minimal variant of [poimandres](https://github.com/mshaugh/poimandres.zed). Instead of green, just bluer. It's a personal theme but would like to publish it if anyone else wants to use it. (idk if there's demand haha).
Thanks in advance!

Add Blankeos Zen theme

---

extensions.toml

Release notes:
https://github.com/mikasius/zed-nord-theme/releases/tag/v0.0.11

Update Nord theme to v0.0.11

---

.gitmodules
extensions.toml

Updating the URL for the meson extension, cc @notpeter

Bump Meson language to v0.2.0

---

.gitmodules
extensions.toml

Add [Vector Remap Language (VRL)](https://vrl.dev) support for Zed.

Add VRL extension

---

extensions.toml

Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.2.1

Update macos-classic theme to v0.2.1

---

.gitmodules
extensions.toml

Add Nuisance theme

---

.gitmodules
extensions.toml

This PR updates the Dart extension to v0.1.3.
The Dart extension now resides at [`zed-extensions/dart`](https://github.com/zed-extensions/dart).

dart: Bump to v0.1.3

---

.gitmodules
extensions.toml

Adech Theme extension added as a new Extension for the Editor.

Add Adech Theme extension

---

extensions.toml

This PR updates the nim extension submodule to version 0.0.5 and updates the version in extensions.toml

Update nim extension to  v0.0.5

---

extensions.toml

See the changelog [here](https://github.com/zed-extensions/java/releases/tag/v3.0.0).

Bump java to v3.0.0

---

.gitmodules
extensions.toml

- Closes: https://github.com/zed-industries/extensions/issues/1568
- See also: https://github.com/zed-industries/zed/issues/11138

Add `org` extension

---

.gitmodules
extensions.toml

ActionScript syntax highlighting

Add ActionScript extension

---

extensions.toml

This PR updates the nim extension submodule to version 0.1.0 and updates the version in extensions.toml

Update nim extension to  v0.1.0

---

.gitmodules
extensions.toml

closes #1592
a made a few small changes to the highlighting, some fixes and some just kinda personal preference
the ts seems to work somewhat strangely with `export` (hares `pub`) which makes it appear next to function declarations rather than as part of them so i couldnt figure out how to get it to show up nicely in the outline, just left them out :man_shrugging:

Add Hare language extension

---

.gitmodules
extensions.toml

This adds support for RPM Spec language used to create system packages on RPM-based Linux distributions
Thanks

Add RPM Spec language extension

---

.gitmodules
extensions.toml

🍈 https://github.com/isunjn/hami-melon-zed

Add Hami Melon Theme

---

.gitmodules
extensions.toml

Hello,
This adds syntax highlighting support for the Gettext PO format.
Thank you,

Add PO language extension

---

.gitmodules
extensions.toml

Adds Sorbet language server as a Ruby extension for Zed.
Source is here: https://github.com/notchairmk/zed-sorbet

Add Sorbet extension

---

extensions.toml

- rollback inlay hints coloiring
- update active tab coloring
- chore: adjust JSON theme output

Bump catppuccin to 0.2.13

---

.gitmodules
extensions.toml

Adds linter extension for [Oxlint](https://oxc.rs/docs/guide/usage/linter)

Add oxlint linter extension

---

.gitmodules
extensions.toml

This extension provides syntax highlighting for the [Vento](https://vento.js.org) templating language.

Add Vento extension

---

.gitmodules
extensions.toml

Replace/Re-Add Odin language extension

---

.gitmodules
extensions.toml

Add yellowed theme to Zed.
https://github.com/Gael-Lopes-Da-Silva/YellowedZed

Add yellowed theme extension

---

extensions.toml

- See: https://github.com/zed-extensions/swift/pull/25

Bump Swift language extension to v0.3.2

---

.gitmodules
extensions.toml

Add nyxvamp-theme

---

.gitmodules
extensions.toml

This PR adds the Postgres Context Server extension.

Add Postgres Context Server

---

extensions.toml

- Add typst language
- Remove dead code

Update typos to v0.0.4

---

extensions.toml

- Windows fixes (https://github.com/Stef16Robbe/harper_zed/pull/4)

Update harper to 0.0.4

---

extensions.toml

- some button color adjustments
- some hover color adjustments
- syntax updates

Bump catppuccin to 0.2.15

---

.gitmodules
extensions.toml

I made a new theme called One Dark Flat as a port of [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) to Zed

Add One Dark Flat theme

---

extensions.toml

- language server integration revamp
- grammar tiny update

Bump ada to v0.3.0

---

extensions.toml

Includes:
- https://github.com/zed-extensions/beancount/pull/3

Bump beancount language to v0.0.4

---

.gitmodules
extensions.toml

This adds a Zed extension for [CONL](https://github.com/ConradIrwin/conl).

Add CONL language

---

.gitmodules
extensions.toml

Hey, we made some improvement in the theme so I'm pushing the changes, thanks!
@chungweileong94

Update Vercel Theme to 0.0.2

---

.gitmodules
extensions.toml

Hey there! 
Would like to contribute a new theme to the extension store, more details here: 
https://github.com/stevedylandev/pinata-theme-zed

Add Pinata Theme extension

---

extensions.toml

[diff](https://github.com/JuliaEditorSupport/zed-julia/compare/bdad85f4880e71f82e100a0f3c6047e6f8a2b7df..c25853f9f731349851b1325555c56652909261ab)

Bump Julia to 0.1.3

---

.gitmodules
extensions.toml

Adding a new theme extension for Zed editor. The extension called "brook-code-theme"

Add brook-code theme

---

extensions.toml

Release notes:
https://github.com/hugginsio/zed-cooklang/releases/tag/v1.3.3

Update cooklang to v1.3.3

---

.gitmodules
extensions.toml

This is a port of the default Neovim themes

Add neovim-default theme

---

extensions.toml

To erlang, haskell, lua, php, prisma, prolog, proto, toml, zig

Add textobject queries

---

extensions.toml

- Closes: https://github.com/zed-industries/zed/issues/17845

Add Perplexity Slash Command Extension

---

extensions.toml

- Fixed surface background color
- Changed the border color of an icon to match the background
- Changed error color

Bump One Black Theme to v0.0.3

---

.gitmodules
extensions.toml

Added libsql-context-server as a submodule. Updated extensions.toml and .gitmodules accordingly.

Add libsql-context-server extension

---

.gitmodules
extensions.toml

Add extension that completes unicode

Add unicode extension

---

.gitmodules
extensions.toml

Improve the development experience of writing [Gem](https://github.com/mantou132/gem) elements.
- inline HTML/CSS/Style snippets
- inline HTML/CSS highlight support // extend zed typescript
- inline HTML/CSS hover info
- inline HTML/CSS auto completion

Add gem extension

---

.gitmodules
extensions.toml

This pr adds https://github.com/taciturnaxolotl/catppuccin-blur-zed

Add catppuccin-blur-plus theme
