zed-industries/extensions

- extensions.toml
Release notes:
https://github.com/0PandaDEV/zed-one-dark-flat/releases/tag/v0.1.0
> Update one-dark-flat to v0.1.0

- .gitmodules
- extensions.toml
The Zed Grey Theme is a minimalist and modern light theme designed for developers who prefer a clean and subtle interface. This theme focuses on simplicity and readability, with carefully chosen colors to reduce eye strain while maintaining clarity in your code and interface elements.
> Add Grey-theme

- extensions.toml
This PR updates the LilyPond extension to v0.0.6.
> Update LilyPond to v0.0.6

- .gitmodules
- extensions.toml
This PR adds a new language extension for Yara (I also created a Tree-sitter plugin to support this extension since one did not exist).
Example:
> Add Yara language extension

- extensions.toml
- Fix file explorer background color
- Set icon and text accent color
- Add the search match background color
- Add the main background color
- Add extension.toml
> Update Gentle Dark to v0.1.1

- extensions.toml
- Fix: update LanguageServer.jl on precompile failure
- Add section "Using Zed in the REPL" to README.md
> Bump Julia to 0.1.4

- .gitmodules
- extensions.toml
This PR adds a new language extension to support the [rhai](rhai.rs) scripting language.
> Add zed-rhai extension

- extensions.toml
> Update Github Theme to v0.1.3

- extensions.toml
Releasing version 1.0 🥳 
- Update theme schema to version 0.2.0
- Adjust the colors on the tab bar/tabs so the active tab is more visible
- Add missing color values to reflect the theme color palette
> Update Gentle Dark Theme to v1.0.0

- extensions.toml
- Improved highlighting for markers in commands like `\label` and `\ref`
- Better context aware self closing brackets
> Bump LaTeX to 0.1.4

- .gitmodules
- extensions.toml
Adds a new Underground theme to Zed extensions.
> Add Underground theme 1.0.0

- extensions.toml
> Update Cython to v0.2.0

- extensions.toml
Added support of `.conf`, `.cfg`, `.config` extensions
> Update ini to `v0.0.3`

- .gitmodules
- extensions.toml
It's my personal theme, but I think some people would enjoy it. A bit work in progress, but certainly good enough for daily use.
> Add phine theme 0.0.1

- extensions.toml
I added "players" colors, and darkened terminal yellow colors.
> Update Eiffel-Theme to v0.0.2

- extensions.toml
Minor fix release 😅 
- Fix the scrollbar transparency
- Set terminal and conflict colors
- Lighten the status bar background
> Update Gentle Dark Theme to v1.0.1

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/21666
- https://github.com/zed-industries/zed/pull/20206
> Bump Elixir to v0.1.2

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/20206
> Bump Astro to v0.1.2

- extensions.toml
Minor fix release
- Color adjustments
- Fixed light theme
Thanks in advance, and thanks again for accepting to integrate my theme into Zed 🙌
> Update Wakfu Theme to v0.1.1

- extensions.toml
- Updates monospace-theme version to 0.1.3
> Update monospace-theme to v0.1.3

- extensions.toml
I would like to update Yellowed from 0.0.1 to 0.0.2
> Update yellowed to v0.0.2

- extensions.toml
Updated some variables of the Vercel Theme to fix UI issues.
cc @chungweileong94
> Update Vercel theme to v0.0.4

- extensions.toml
New features:
* outline
* indents
> Update kconfig to v0.1.0

- extensions.toml
CI issues causing the large version bump lol
> Update Catppuccin-blur to v0.1.22

- extensions.toml
See: https://github.com/zed-extensions/ocaml/pull/9
- Includes: https://github.com/zed-extensions/ocaml/pull/6
> Update OCaml to v0.1.4

- extensions.toml
added support for LSP in `v0.0.2` release
> Update COBOL extension to v0.0.2

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22579
> Update Elixir to v0.1.3

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/18728
> Update Racket to v0.0.2

- .gitmodules
- extensions.toml
Adds syntax highlighting support for the [`whkd`](https://github.com/LGUG2Z/whkd) configuration format.
> Add whkd extension

- extensions.toml
This PR updates the jsonnet extension to the latest version.
> Update jsonnet extension to 0.3.1

- .gitmodules
- extensions.toml
New extension with OpenSCAD language support
> Add OpenSCAD extension

- .gitmodules
- extensions.toml
Theme based on [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) and [Jane Two](https://marketplace.visualstudio.com/items?itemName=dotcypress.vscode-jane) themes.
> Add Aystra theme v0.0.1

- extensions.toml
Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.8
> Update one-dark-pro to v0.0.8

- .gitmodules
- extensions.toml
This extension works pretty much the same internally as the wakatime extension that is already published in this repo
> Add activitywatch extension

- extensions.toml
New update provides fixes and refinement of theme colors.
<p align="center">
</p>
<p align="center">
</p>
> Update Dune Theme to v1.1.0

- extensions.toml
Fixed the scrollbar transparency
cc @ferothefox
> Update vercel-theme to v0.0.5

- extensions.toml
Adds support for syntax highlighting of the content around Tera templating! https://github.com/uncenter/zed-tera#embeddedinjected-language-support
> Update Tera extension to v1.1.0

- .gitmodules
- extensions.toml
- Language Server: [IWE - Markdown LSP server](https://github.com/iwe-org/iwe)
- Extension Repo: [iwe-org/zed-iwe](https://github.com/iwe-org/zed-iwe/)
> Add IWE extension

- extensions.toml
> Update Maya to v0.4.5

- extensions.toml
Hello, I would like to update the yellowed theme to version 0.0.3.
> Update Yellowed to v0.0.3

- extensions.toml
This makse some minor changes to the Axolosin theme:
- Changed ghost element hover and select colours to improve visibility of hovers/selections in popup lists (e.g., code completions)
- Added theme-specific cursor and text selection colours to better match the theme
- Simplified the theme description by removing the vague term "resin"
- Updated copyright in the license to reflect the new year, 2025
> Update Axolosin theme to v1.1.0

- .gitmodules
- extensions.toml
Yaka Theme
https://github.com/edgarkanyes/yaka
> Add Yaka theme v0.0.1

- .gitmodules
- extensions.toml
Decorative Stitch theme
https://github.com/keithrowell/zed-theme-decorative-stitch
> Add Decorative Stitch theme v1.0.0

- .gitmodules
- extensions.toml
There is already an auto-generated vitesse theme in Zed, but this one corrects color inaccuracies and fills in missing colors.
https://github.com/colinlienard/zed-vitesse-theme-refined
> Add vitesse theme refined

- .gitmodules
- extensions.toml
- fix extension schema version
> Update Yaka theme to v0.0.2

- extensions.toml
Release notes:
https://github.com/kadena-community/pact-zed/releases/tag/v0.0.3
> Update pact to v0.0.3

- .gitmodules
- extensions.toml
Extension repository: https://github.com/lczerniawski/ObsidianSunset-Zed
> Add Obsidian Sunset theme

- .gitmodules
- extensions.toml
Main repo: https://github.com/blopker/codebook
Thanks!
> Add Codebook, a code aware spell checker

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22055
- https://github.com/zed-industries/zed/pull/22268
> elixir: Bump to v0.1.4

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22609
> haskell: Bump to v0.1.3

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/20752
- https://github.com/zed-industries/zed/pull/22268
> html: Bump to v0.1.5

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22936
> csharp: Bump to v0.1.1

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/15181
- https://github.com/zed-industries/zed/pull/16955
- https://github.com/zed-industries/zed/pull/22609
> purescript: Bump to v0.1.0

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/23532
- https://github.com/zed-industries/zed/pull/22268
Submodule changes for PHP were accidentally included in:
- https://github.com/zed-industries/extensions/pull/1946/files
> php: Bump to v0.2.4

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22609
> zig: Bump to v0.3.3

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/18728
- https://github.com/zed-industries/zed/pull/20206
> scheme: Bump to v0.0.2

- extensions.toml
Includes:
- https://github.com/zed-industries/zed/pull/22268
> terraform: Bump to v0.1.2

- extensions.toml
Improved theme
@chungweileong94 (sorry for the delay since your pr)
> Update Vercel Theme to v0.0.6

- .gitmodules
- extensions.toml
Sqruff: fast SQL formatter/linter
language server: https://github.com/quarylabs/sqruff
> Add sqruff extension v0.1.0

- extensions.toml
> Update CSpell to v0.0.2

- .gitmodules
- extensions.toml
I'm finally making the move completely over to Zed from VSCode, and that means that I'd love to be able to use [my custom theme!](https://marketplace.visualstudio.com/items?itemName=Chadderbox.monokai-vibrant-amped)
Thanks to you all for helping to make an incredible editor.
> Add Monokai Vibrant Amped v0.0.1

- extensions.toml
Includes:
- https://github.com/zed-extensions/vue/pull/7
> Bump Vue to v0.1.3

- .gitmodules
- extensions.toml
This PR adds WebAssembly (wat) language support via:
- language server: [g-plane/wasm-language-tools](https://github.com/g-plane/wasm-language-tools) `wat_server`
- tree-sitter: https://github.com/wasm-lsp/tree-sitter-wasm
> Add WebAssembly Text Format extension

- .gitmodules
- extensions.toml
[ISLE language](https://github.com/bytecodealliance/wasmtime/tree/main/cranelift/isle) support :)
> Add ISLE language extension

- .gitmodules
- extensions.toml
This PR adds a [Workflow Description Language (WDL)](https://openwdl.org) extension to Zed. 
Current features include syntax highlighting and support for `wdl-lsp`.
Repo: https://github.com/broadinstitute/zed-wdl
> Add WDL (Workflow Description Language) extension

- .gitmodules
- extensions.toml
> Add Moonlight theme

- .gitmodules
- extensions.toml
This PR adds a new extension for Flutter code snippets.
> Add flutter-snippets extension

- .gitmodules
- extensions.toml
> Add Snowfall theme

- .gitmodules
- extensions.toml
Add vCard extension.
- https://github.com/TitouanReal/zed-vcard
- https://github.com/TitouanReal/tree-sitter-vcard
> Add vCard extension

- extensions.toml
- Added a variant for light themes and tweaked some icons for better visibility
> Update vscode-icons to v0.2.0

- .gitmodules
- extensions.toml
Catppuccin Icons for Zed 🎉 
These initially appeared "low-res," but https://github.com/zed-industries/zed/pull/24332 fixed this.
Planning to move repo under official https://github.com/catppuccin org eventually
closes https://github.com/catppuccin/zed/issues/75
> Add catppuccin-icons theme

- .gitmodules
- extensions.toml
Add VSCode Great Icons theme which is sourced from [VS Code Great Icons](https://github.com/EmmanuelBeziat/vscode-great-icons).
> Add VSCode great icons theme

- extensions.toml
Includes:
- https://github.com/zed-extensions/nu/pull/6
https://github.com/zed-extensions/nu/commit/60685fe14f44f59d2d3fabf78373c1a07525b1f4
> Bump nu to 0.0.4

- .gitmodules
- extensions.toml
> Add Lydia theme

- .gitmodules
- extensions.toml
This repo is a demo of another zed-related tool, but I thought it'd be nice to publish it as an extension too so you can see the example. If the unrelated files causes trouble, I can move it to another repository.
> Add not-material-theme

- extensions.toml
> Update LaTeX to v0.1.10

- .gitmodules
- extensions.toml
- package.json
Add JetBrains New UI Icons Theme extension
> Add JetBrains New UI Icons Theme extension

- .gitmodules
- extensions.toml
This PR adds Bearded Icon theme
> Add Bearded Icons theme

- extensions.toml
includes:
- https://github.com/tree-sitter-perl/zed-perl/pull/3
> Bump Perl to v0.1.1

- .gitmodules
- extensions.toml
Hello team Zed,
Add Symbols Icons theme which is sourced from [Symbols](https://github.com/miguelsolorio/vscode-symbols).
Thank You.
> Add Symbols icon theme v0.1.0

- .gitmodules
- extensions.toml
- src/lib/validation.js
This PR adds Zed's legacy themes as an extension as we plan to remove them from Zed soon.
> Add zed-legacy-themes

- .gitmodules
- extensions.toml
> Add openmoji-icons icon theme v0.1.0

- .gitmodules
- extensions.toml
Add simple language support for [Agda](https://github.com/agda/agda)
- Tree sitter: [tree-sitter/tree-sitter-agda](https://github.com/tree-sitter/tree-sitter-agda)
- Extension: [haohanyang/agda-zed](https://github.com/haohanyang/agda-zed)
> Add Agda language extension v0.1.0

- extensions.toml
Includes:
- https://github.com/zed-extensions/scheme/pull/2
> Bump Scheme to v0.0.4

- extensions.toml
Release notes:
https://github.com/denix666/zed-theme/releases/tag/v0.0.9
> Update denix to v0.0.9

- extensions.toml
Hi, this PR updates Modus Themes to v0.0.9 which includes a tiny fix for selection colors of players by increasing their contrast.
Release page is here: https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.9
Thanks!
> Update Modus Themes to v0.0.9

- extensions.toml
> Update 0x96f theme to v1.2.5

- extensions.toml
This PR updates bearded icon theme
> Update bearded icon theme to v0.3.0

- extensions.toml
Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.9
> Update one-dark-pro to v0.0.9

- extensions.toml
https://github.com/biomejs/biome-zed/issues/54#issuecomment-2659393509
> Update biome to v0.1.4

- extensions.toml
Updated to the new tree-sitter release
> Update Odin extension to v0.2.1

- extensions.toml
- Handling for latest default files
- Prepares for next version using latest icon schema
> Update openmoji-icons to v0.2.0

- .gitmodules
- extensions.toml
Add language support for [Bicep](https://docs.microsoft.com/azure/azure-resource-manager/bicep/)
Closes #1772
> Add Bicep extension

- extensions.toml
Includes:
- https://github.com/zed-extensions/php/pull/7
> Update PHP to v0.2.7

- extensions.toml
Includes:
- https://github.com/zed-extensions/svelte/pull/16
> Update svelte to v0.2.3

- extensions.toml
Update [JetBrains New UI Icons Theme](https://github.com/ankddev/zed-jetbrains-newui-icons) plugin to v2.0.2.
> Update jetbrains-new-ui-icons to v2.0.2

- .gitmodules
- extensions.toml
This is an icon theme, which is based on the official zed monochrome icons, except this theme colors them!
The repository is here: https://github.com/TheRedXD/zed-icons-colored-theme
> Add colored-zed-icons-theme

- .gitmodules
- extensions.toml
+ update repo url to new org repo
> Bump catppuccin-icons to v1.17.3

- extensions.toml
Documentation update as per oWretch/zed-extension-bicep#1
> Update Bicep to v1.0.1

- extensions.toml
Includes:
- https://github.com/zed-extensions/svelte/pull/18
> Update Svelte to v0.2.4

- extensions.toml
Update Codebook to support C, and better logging support.
Thanks!
> Update Codebook to v0.1.3

- extensions.toml
Fixes % in vue templates in vim mode
> Vue v0.2.1

- extensions.toml
Closes someone13574/zed-slate-theme#1
> Update slate to v0.0.3

- extensions.toml
Closes someone13574/zed-monolith-theme#1
> Update monolith to v0.0.4

- extensions.toml
Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.2.3
> Update macos-classic to v0.2.3

- extensions.toml
Fix deprecated usage https://github.com/dotcypress/aystra/issues/1
> Update Aystra to v0.0.3

- extensions.toml
Fixes https://github.com/xhyrom/zed-discord-presence/issues/33
> Update discord-presence to v0.2.3

- .github/workflows/ci.yml
- .gitmodules
- extensions.toml
Fixes Deprecated `scrollbar_thumb.background` usage
> Update nstlgy-dark theme to v0.0.2

- extensions.toml
fixes https://github.com/dracula/zed/issues/20
> Update Dracula to v0.9.3

- extensions.toml
Migrate to `extension.toml` + fix deprecated `scrollbar_thumb.background`
> Update BlackFox theme to v0.2.0

- extensions.toml
- Migrated to scrollbar.thumb.background
(fixes https://github.com/bIaqat/v0-theme-zed/issues/2)
- Fixed Button Colors: https://github.com/bIaqat/v0-theme-zed/issues/1
- Small other text clarity changes
> Update v0-theme to v0.6.0

- .gitmodules
- extensions.toml
Hey there I want to publish my extension which is based on the gitlab-ci-ls project. See: https://github.com/alesbrelih/gitlab-ci-ls
> Add gitlab-ci-ls extension

- .gitmodules
- extensions.toml
Adds the Ezio theme to Zed as an extension.
> Add Ezio theme

- extensions.toml
Update to the latest nu https://github.com/zed-extensions/nu/pull/8
> Update nushell to v0.0.6

- extensions.toml
(I made a mistake in the the submodule revision in the PR I closed just earlier)
> Update LaTeX to v0.1.11

- extensions.toml
Release notes:
https://github.com/Imgkl/the-dark-side/releases/tag/v0.3.0
> Update the-dark-side to v0.3.0

- extensions.toml
[Release notes](https://docs.ruuda.nl/rcl/changelog/#080)
> Update RCL to v0.8.0

- .gitmodules
- extensions.toml
> Add railscast theme

- extensions.toml
- Fixes author's name and email
> Update Stylelint to v0.0.2

- .gitmodules
- extensions.toml
> Add Sequoia theme extension

- extensions.toml
This update includes:
- patched issue when running server in latest zed
- add color swatches 
- some minor improvements
> Update unocss to v0.0.2

- extensions.toml
Update JetBrains New UI Icon Theme extension to version 2.1.0.
> Update JetBrains New UI Icon Theme to v2.1.0

- .gitmodules
- extensions.toml
> Add Severance theme

- extensions.toml
Change property colour to old variable colour
> Update modest-dark to v0.1.7

- extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.8
> Update r to v0.0.8

- extensions.toml
This updates add more than 1000+ icons.
> Update bearded icon theme to v0.4.0

- extensions.toml
Resolves [Bug folders](https://github.com/sebastiandotdev/zed-symbols/issues/2)
> Update symbols to v0.2.1

- extensions.toml
Release notes: https://github.com/Bikossor/Perfect-Dusk-Zed/releases/tag/1.0.1
> Update Perfect Dusk to v1.0.1

- extensions.toml
Release notes:
https://github.com/MordFustang21/zed-one-dark-pro/releases/tag/v0.0.10
> Update one-dark-pro to v0.0.10

- extensions.toml
> Update Codebook to v0.1.4

- .gitmodules
- extensions.toml
Adds the `charmed-icons` extension
(hopefully i did this correctly :smiley: )
> Add `charmed-icons` extension

- extensions.toml
> Update Stylelint to v0.0.3

- extensions.toml
Fixes https://github.com/sebastiandotdev/zed-symbols/issues/4
> Update Symbols to v0.2.2

- .gitmodules
- extensions.toml
This theme more closely follows [Ethan Schoonover's Solarized color palette](https://ethanschoonover.com/solarized/), compared to NeoSolarized and Solarized FP, particularly in syntax highlighting.
> Add Solarized theme

- extensions.toml
Use lighter color for borders in Vercel Dark
@chungweileong94
> Update Vercel Theme to v0.0.7

- .gitmodules
- extensions.toml
Added Git Sub-module Steps 1 - 3 on publishing extension.
Here is a port of an awesome vim theme jellybeans.vim
>  Add Jellybeans theme extension

- extensions.toml
- Fixed colours for HTML tags and attributes.
> Update Visual Assist Dark theme to v0.0.5

- extensions.toml
This PR updates the nim extension submodule to version 0.2.0 and updates the version in extensions.toml
> Update nim extension to  v0.2.0

- extensions.toml
- Update text accent color
- Update panel indent guide color
> Update 0x96f theme to v1.2.6

- .gitmodules
- extensions.toml
This theme is based on the Filter Machine variant of [Zedokai](https://github.com/slymax/zedokai).
There's small modifications of the background and some of the syntax colors.
> Add zedokai-darkest-machine theme

- extensions.toml
https://github.com/rose-pine/zed/releases/tag/v1.1.3
> Update rose-pine-theme to v1.1.3

- extensions.toml
Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.3.1
> Update nvim-nightfox to v0.3.1

- extensions.toml
- Switches to maintained upstream grammars project
- Adds tasks and runnables
- Adds outlines
> Update make to v1.1.0

- extensions.toml
https://github.com/rose-pine/zed/releases/tag/v1.2.0
> Update rose-pine-theme to v1.2.0

- .gitmodules
- extensions.toml
This PR integrates BrowserTools MCP with Zed, bringing browser-based tooling directly into the editor.
- **Zero Context Switching**: Analyze web pages without leaving ZED
- **Audit Suite**: Run lighthouse-based checks (accessibility, SEO, performance) via slash commands
- **Deep Browser Integration**: Screenshot, monitor logs, inspect DOM elements 
- **Dev Workflow Optimization**: Troubleshoot frontend issues with powerful debugging tools
> Add browser-tools-context-server extension

- extensions.toml
Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.4.0
> Update nvim-nightfox to v0.4.0

- .gitmodules
- extensions.toml
I have prepared a snippets package for Nestjs developments. I will continue to develop and enrich it additionally.
https://github.com/ayberkgezer/nestjs-snippets
> Add nestjs-snippets extension

- extensions.toml
- Update UI element colors such as borders, scrollbar, buttons and menus (base, active, hover)
- Update code syntax colors
> Update 0x96f theme to v1.3.0

- extensions.toml
Release notes:
https://github.com/elmarco/zed-rst/releases/tag/v0.0.2
> Update rst to v0.0.2

- extensions.toml
https://github.com/borngraced/monosami/releases/tag/0.1.3
> Update monosami to 0.1.3

- .gitmodules
- extensions.toml
This PR adds an extension for the [Axiom MCP Server](https://github.com/axiomhq/mcp-server-axiom).
> Add Axiom MCP Server extension

- extensions.toml
https://github.com/rose-pine/zed/releases/tag/v1.3.0
> Update rose-pine-theme to v1.3.0

- .gitmodules
- extensions.toml
An Icon theme using [Phosphor](https://phosphoricons.com/)
> Add Phosphor Icons theme

- .gitmodules
- extensions.toml
https://github.com/rubiojr/zed-risor
> Add Risor language extension

- .gitmodules
- extensions.toml
repo @ https://github.com/vikpe/synthwave-alpha-zed
Screenshot
> Add Synthwave Alpha theme

- extensions.toml
Release notes:
https://github.com/phibr0/zed-min-theme/releases/tag/v0.1.11
> Update min-theme to v0.1.11

- extensions.toml
This PR updates the nebula-pulse extension submodule to version 0.0.5 and updates the version in extensions.toml
> Update nebula-pulse theme to v0.0.5

- extensions.toml
Release notes:
https://github.com/hnatiukr/zed-mariana-theme/releases/tag/v1.1.1
> Update sublime-mariana-theme to v1.1.1

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-scss/releases/tag/v0.0.5
> Update scss to v0.0.5

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-laravel-blade/releases/tag/v0.0.5
> Update blade to v0.0.5

- .gitmodules
- extensions.toml
I use this over the existing jinja extension since it provides a bit cleaner highlighting for HTML.
~Its a quick hack so I'm fine with not merging this and waiting for a nicer solution down the line. Just putting it out there if someone might find it useful for now.~
Update: Actually ended up forking the tree-sitter-html repository to flesh this out more and handle some edge cases better. Updated README. Works great already.
> Add HTML-Jinja extension

- extensions.toml
Release notes:
https://github.com/devzaidi/batman-theme-zed/releases/tag/v0.0.3
> Update batman to v0.0.3

- extensions.toml
> Upadate Codebook to v0.1.5

- extensions.toml
Changed the schema_version from 2 to 1 to fix the marketplace visiblity.
> Update t3-theme to v0.0.2

- extensions.toml
Includes:
- https://github.com/zed-extensions/swift/pull/26
> Update Swift to v0.4.0

- extensions.toml
Includes:
- https://github.com/zed-extensions/elixir/pull/3
> Update Elixir to v0.1.7

- .gitmodules
- extensions.toml
https://github.com/zed-extensions/mcp-server-puppeteer
> Add mcp-server-puppeteer

- extensions.toml
This PR updates the LilyPond extension to v0.0.7.
> Update LilyPond extension to v0.0.7

- .gitmodules
- extensions.toml
https://github.com/zed-extensions/mcp-server-brave-search
> Add mcp-server-brave-search

- .gitmodules
- extensions.toml
This extension is a syntax highlighter for Logstash configuration files.
Logstash is part of [the elastic stack](https://www.elastic.co).
> Add Logstash extension

- .gitmodules
- extensions.toml
Hey,
i added new theme which i like and hope you too ❤️
> Add Anysphere Theme

- extensions.toml
Includes:
- https://github.com/zed-extensions/elm/pull/1
See:
- https://github.com/zed-extensions/elm/pull/3
> Update Elm to v0.2.0

- extensions.toml
https://github.com/rose-pine/zed/releases/tag/v1.3.1
> Update Rose Pine Theme to v1.3.1

- extensions.toml
Release notes: https://github.com/pavles6/one-dark-darkened/releases/tag/v0.0.2
> Update one-dark-darkened to v0.0.2

- extensions.toml
Upgrade the halcyon extension to version 0.1.0 and synchronize the submodule commit accordingly.
> Update halcyon extension to v0.2.0

- extensions.toml
> Update Codebook to v0.1.6

- extensions.toml
Update the halcyon subproject to version 0.2.3 and change the commit reference to the latest version.
> Update halcyon theme to v0.2.3

- extensions.toml
Add new version control colors
> Update vitesse-theme-refined to v0.1.0

- extensions.toml
> Update GraphQL extension to v1.0.1

- .gitmodules
- extensions.toml
In this PR, I add an MCP Server for [Sequential Thinking](https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking)
> Add Sequential Thinking MCP Server

- .gitmodules
- extensions.toml
In this PR, I introduce an extension that integrates the [official MCP server from Webflow](https://github.com/webflow/mcp-server).
> Add Webflow MCP Server extension

- extensions.toml
- Add markup list marker color
- Update elevated surface background
- Update UI element background
- Update status bar, title bar, tab bar and panel background
> Update 0x96f theme to v1.3.1

- extensions.toml
Release notes:
https://github.com/Jean-Tinland/zed-theme-day-shift/releases/tag/v1.0.2
> Update day-shift to v1.0.2

- extensions.toml
Release notes:
https://github.com/Jean-Tinland/zed-theme-night-shift/releases/tag/v1.0.2
> Update night-shift to v1.0.2

- extensions.toml
Includes:
- https://github.com/zed-extensions/php/pull/21
- https://github.com/zed-extensions/php/pull/20
- https://github.com/zed-extensions/php/pull/19
- https://github.com/zed-extensions/php/pull/15
- https://github.com/zed-extensions/php/pull/10
> Update PHP to v0.2.8

- .gitmodules
- extensions.toml
Support [XDR: External Data Representation](https://en.wikipedia.org/wiki/External_Data_Representation)
Tree-sitter: https://github.com/algebnaly/tree_sitter_naive_xdr.git
fixes Extension IDs to kebab-cased(https://github.com/zed-industries/extensions/pull/2320#issuecomment-2755779464).
> Add XDR syntax highlight

- extensions.toml
Added icon theme, increase comment contrast.
Release notes:
- https://github.com/phibr0/zed-min-theme/releases/tag/v0.2.0
> Update min-theme to v0.2.0

- extensions.toml
This PR updates the LilyPond extension to v0.0.8.
> Update LilyPond extension to v0.0.8

- extensions.toml
This enhances the syntax highlighting queries for D.
> Bump D language extension to 0.0.9

- .gitmodules
- extensions.toml
Please add SuperGreatMonokai theme to Zed
> Add SuperGreatMonokai Theme

- .gitmodules
- extensions.toml
A [MoonBit](https://www.moonbitlang.com/) extension for [Zed](https://zed.dev).
> Add MoonBit extension

- extensions.toml
Release [v0.1.1](https://github.com/kartikvashistha/zed-ansible/pull/10) for the Ansible extension.
> Update Ansible to v0.1.1

- .gitmodules
- extensions.toml
This PR adds the cursor dark theme, which is ported from the cursor editor
> Add Cursor Dark theme

- extensions.toml
I couldn't find a way to add the "theme" tag to the extension, but I would like that added in this revision of the extension :)
> Bump gruber-darker to v0.0.8

- .gitmodules
- extensions.toml
I have added a new theme extension called marble. You can find it 
[here](extensions/marble) and if it doesnt work, its called marble
Also my first PR (so I apologise if I did something wrong)
> Add marble theme extension

- extensions.toml
Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.4.1
> Update nvim-nightfox to v0.4.1

- extensions.toml
3 new snippets: 
- `sv-head`
- `sv-window`
- `sv-global-style`
> Update svelte-snippets to v0.0.3

- extensions.toml
Includes:
- https://github.com/zed-extensions/haskell/pull/1
- https://github.com/zed-extensions/haskell/pull/2
> Update haskell to v0.1.5

- .gitmodules
- extensions.toml
PR adds Dark Pop ui custom theme. Thanks!
> Add dark pop UI theme

- extensions.toml
- Update UI hover and selected colors
> Update 0x96f theme to v1.3.2

- .gitmodules
- extensions.toml
Hello Zed team! This extension adds Andromeda theme - a port of a popular VScode theme that became an indispensable part of my setup.
Here's the preview:
> Add Andromeda theme extension

- .gitmodules
- extensions.toml
- Language: [Cassandra Query Language (CQL)](https://docs.datastax.com/en/cql/hcd/reference/cql-reference-about.html)
- Extension: [Akzestia/zed-cql](https://github.com/Akzestia/zed-cql)
- Tree-sitter: [Akzestia/tree-sitter-cql](https://github.com/Akzestia/tree-sitter-cql)
> Added CQL (Cassandra Query Language) language

- .gitmodules
- extensions.toml
This PR updates the extension version. Thanks!
> Update Dark Pop UI theme to v0.0.2

- extensions.toml
- Update wrap guide color to make it visible
> Update 0x96f theme to v1.3.3

- .gitmodules
- extensions.toml
- MCP: [exa-labs/exa-mcp-server](https://github.com/exa-labs/exa-mcp-server)
- Zed Extension: [exa-labs/zed-exa-mcp-extension](https://github.com/exa-labs/zed-exa-mcp-extension)
> Add Exa MCP extension

- extensions.toml
Added a new experimental theme with different tokens
> Update Lydia theme to v0.0.3

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-laravel-blade/releases/tag/v0.1.0
> Update blade to v0.1.0

- extensions.toml
Release notes:
https://github.com/0PandaDEV/zed-one-dark-flat/releases/tag/v1.0.0
> Update one-dark-flat to v1.0.0

- .gitmodules
- extensions.toml
Hey there! Here's a new dark theme inspired by RustRover's default dark theme
> Add RustRover Dark Theme

- extensions.toml
Changes:
* refactor!(d2): split injection queries from highlights to fix language conflict by @jasonkradams in https://github.com/gabeidx/zed-d2/pull/7
* docs: add credits to tree-sitter-d2 by @gabeidx in https://github.com/gabeidx/zed-d2/pull/2
* style: format examples with d2 fmt by @gabeidx in https://github.com/gabeidx/zed-d2/pull/3
* docs: add readme example image by @gabeidx in https://github.com/gabeidx/zed-d2/pull/4
* docs: add readme install example by @gabeidx in https://github.com/gabeidx/zed-d2/pull/5
> Update D2 to v0.2.1

- .gitmodules
- extensions.toml
Created a theme for zed based on a theme i created in vscode recently. It's a sleek, high-contrast dark blue theme with rich blues and a futuristic aesthetic. It combines deep oceanic tones with arctic highlights.
> Add Arctic Depth theme

- .gitmodules
- extensions.toml
Extension: https://github.com/akbxr/zed-mcp-server-context7
MCP npm: https://github.com/upstash/context7-mcp
> Add Context7 MCP Server

- extensions.toml
Adds Haskell support
Thank you!
> Update Codebook to v0.1.7

- .gitmodules
- extensions.toml
This PR supports Lean 4.
- Extension: [blackbird314/lean4](https://github.com/blackbird314/lean4)
- Tree-sitter: [tree-sitter-lean](https://github.com/Julian/tree-sitter-lean)
- Language Server: [leanprover/lean4](https://github.com/leanprover/lean4/tree/master/src/Lean/Server)
> Add Lean4 Extension

- .gitmodules
- extensions.toml
This pull request adds support for the [Elle](https://github.com/acquitelol/elle) programming language to Zed.
- Extension: https://github.com/acquitelol/elle/tree/rewrite/editors/zed
- Tree-sitter: [acquitelol/tree-sitter-elle](https://github.com/acquitelol/tree-sitter-elle)
- LSP: https://github.com/acquitelol/elle/tree/rewrite/src/lsp
> Add elle language extension

- extensions.toml
Opened another PR , bumped up the extension version to v0.0.2 in both submodule and main extension.toml, so should be good to go.
- Improved wildcard characters highlighting.
- Fixed AS keyword  being not properly highlighted after function definition.
- Added highlights for embedded code blocks.
- Proper number(integer, float) highlighting inside function arguments, IN () clause etc.
- Added Special highlights for Graph Engine & Graph Engine Types.
> Update CQL (Cassandra Query Language) Extension to v0.0.2

- extensions.toml
With this update:
- Improved highlighting for Astro
- Improved terminal colors
> Update Andromeda theme to v0.1.1

- extensions.toml
This PR updates the jsonnet extension to the latest version.
> Update jsonnet to v0.3.2

- .gitmodules
- extensions.toml
**What this PR does:**
This pull request introduces the Shades of Purple theme to the Zed editor.
**Basis and Inspiration:**
This theme is a port of the popular [Shades of Purple](https://github.com/ahmadawais/shades-of-purple-vscode) theme for VSCode. The aim is to bring this vibrant and distinctive color scheme to the Zed editing environment, offering users an exciting new option for customizing their editor's appearance.
**Testing:**
I have tested this theme locally in my Zed editor to ensure that the colors are applied correctly to various UI elements and that the theme provides a comfortable and productive coding experience.
**Checklist:**
Looking forward to your review!
> Add shades-of-purple-theme extension

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-scss/releases/tag/v0.0.6
> Update scss to v0.0.6

- extensions.toml
Release notes:
https://github.com/irmhonde/shades-of-purple-theme/releases/tag/v0.0.2
> Update shades-of-purple-theme to v0.0.2

- extensions.toml
Includes:
- https://github.com/zed-extensions/vue/pull/30
> Update vue to v0.2.4

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-scss/releases/tag/v0.1.0
Switch tree-sitter:
- from: https://github.com/tree-sitter-grammars/tree-sitter-scss
- to: https://github.com/savetheclocktower/tree-sitter-scss
> Update scss to v0.1.0

- .gitmodules
- extensions.toml
* Added a dark theme variant
* Increased contrast for selection background readability
> Upgrade eiffel-theme to v0.1.0

- .gitmodules
- extensions.toml
See https://bennypowers.com/design-tokens-language-server
> Add design-tokens-language-server

- .gitmodules
- extensions.toml
This PR adds a bold neo-brutalist theme with vibrant syntax highlighting and high-contrast UI for Zed.
**Pitch:**
Brings aesthetic diversity and accessibility to Zed with complete syntax coverage, inspired by the raw, high-impact style of neo-brutalism.
Looking forward to your review!
> Add neo-brutalism theme

- extensions.toml
> Update chai-theme to v0.0.2

- .gitmodules
- extensions.toml
This PR adds the [Sonokai](https://github.com/sainnhe/sonokai) theme to Zed
> Add Sonokai theme

- .gitmodules
- extensions.toml
Synthax highlighting and LSP for KCL lang
> Add KCL extension

- extensions.toml
This release includes basic support for outlines
> Update Blueprint to v0.3.0

- .gitmodules
- extensions.toml
This is a custom Nightfox theme.
There is a new option called `midnight_m` I am personally using.
> Add nightfox_m theme

- extensions.toml
Hi, this pull request updates the Ruby extension to v0.5.6, which includes many goodies and fixes. You can find the full list of changes on the release page [here](https://github.com/zed-extensions/ruby/releases/tag/v0.5.6). I'm also copying it below for your convenience:
```
1. Remove default tasks.json by @vitallium in https://github.com/zed-extensions/ruby/pull/36
2. Remove else from outdent triggers by @vitallium in https://github.com/zed-extensions/ruby/pull/42
3. Add completion_query_characters by @smitbarmase in https://github.com/zed-extensions/ruby/pull/49
4. Add minimal README by @andyw8 in https://github.com/zed-extensions/ruby/pull/54
5. Specify ? and ! as word characters by @andyw8 in https://github.com/zed-extensions/ruby/pull/58
6. Add some basic tasks by @andyw8 in …
```
> Update Ruby extension to v0.5.6

- extensions.toml
Use ts plugin alternative language services
- language-server:
- from: [npm ts-gem-plugin](https://www.npmjs.com/package/vscode-gem-languageservice)
- to: [npm ts-gem-plugin](https://www.npmjs.com/package/ts-gem-plugin) ([source](https://github.com/mantou132/gem/tree/main/packages/ts-gem-plugin))
> Update gem extension

- extensions.toml
Release notes:
https://github.com/irmhonde/shades-of-purple-theme/releases/tag/v0.0.4
> Update shades-of-purple-theme to v0.0.4

- extensions.toml
Release notes:
https://github.com/akbxr/zed-mcp-server-context7/releases/tag/v0.0.2
> Update mcp-server-context7 to v0.0.2

- extensions.toml
https://github.com/rzukic/zed-latex/releases/tag/v0.2.1
> Update LaTeX to v0.2.1

- .gitmodules
- extensions.toml
[Tombi](https://github.com/tombi-toml/tombi) is a TOML language Server with a different implementation than taplo.
It provides features such as auto sorting using JSON Schema, and goto definitions between workspaces in [`Cargo.toml`](https://x.com/tombi_toml/status/1914710904236851320) and `uv.toml`.
> Add tombi extension

- extensions.toml
Release notes:
https://github.com/akbxr/firecrawl-mcp-zed/releases/tag/v0.0.2
> Update mcp-server-firecrawl to v0.0.2

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-unocss/releases/tag/v0.0.3
> Update unocss to v0.0.3

- extensions.toml
Diff: https://github.com/wingyplus/zed-powershell/compare/0.1.0...0.3.0
> Update PowerShell to v0.3.0

- extensions.toml
Extension Diff: https://gitlab.com/flukejones/zed-slint/-/compare/16566c...af1487
Tree-sitter Diff: https://github.com/slint-ui/tree-sitter-slint/compare/acc77c93ef4b73ba8c3a581b8c99d95b55f7178b...4e2765d4cac1f03ada6f635eeb6008d1d0aff5a3
> Update slint to version v0.0.6

- extensions.toml
> Update: tombi 0.1.1

- extensions.toml
Hi! This is an exciting update to the Ruby extension that introduces the new Process API. This version aims to improve the initial DX when starting the LSP, as well as enhance the overall DX of the Ruby extension. You can find the short changelog here: https://github.com/zed-extensions/ruby/releases/tag/v0.7.0 
Thanks!
> Update Ruby to v0.7.0

- .gitmodules
- extensions.toml
> Add seti-icons

- extensions.toml
> Update 0x96f theme to v1.3.4

- extensions.toml
> Update Tombi to v0.1.2

- extensions.toml
from: https://github.com/zed-extensions/vue/pull/36
> Update vue to 0.2.5

- extensions.toml
from: https://github.com/zed-extensions/astro/pull/10
> Update astro to 0.1.7

- extensions.toml
[Update terminal ANSI blue colors for improved visibility](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/63d4ce5b1184baa08e9764d528dd84ee96584d83)
[Update terminal ANSI magenta colors for improved visibility](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/34ad5235d9356ef94de304d3fa71a4990c73641b)
[Update theme configuration for more Options](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/227f18c49928b72a4fbce919dcc1b0293aa9b835)
[Update version control & file explorer colors in theme configuration](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/28db92fb04307e31600b2308903d67152e12464e)
> Update supergreatmonokai to V0.0.2

- extensions.toml
Release notes:
https://github.com/trbutler4/zed-cairo/releases/tag/v0.1.0
> Update cairo to v0.1.0

- extensions.toml
Release notes:
https://github.com/jmesrje/zed-charmed-icons/releases/tag/v0.7.1
> Update charmed-icons to v0.7.1

- .gitmodules
- extensions.toml
A vibrant and purposeful theme family: https://github.com/mnemonic-theme/zed
> Add mnemonic themes

- .gitmodules
- extensions.toml
> Added Noir & Blanc theme

- extensions.toml
This PR updates the LilyPond extension to v0.0.9.
> Update LilyPond extension to v0.0.9

- extensions.toml
Tweak colors of error and warning popups in dark theme.
> Update Melange theme to v0.0.5

- extensions.toml
Release notes:
https://github.com/hnatiukr/zed-mariana-theme/releases/tag/v1.1.2
> Update sublime-mariana-theme to v1.1.2

- .gitmodules
- extensions.toml
This PR adds the [Snazzy](https://github.com/Eivs/zed-snazzy) theme to Zed
> Add Snazzy theme

- .gitmodules
- extensions.toml
Adding an adaptation of Jellybeans theme
> Add Beanseeds Pro theme

- .gitmodules
- extensions.toml
Light and dark themes: https://github.com/artemevsevev/zed-theme-jetbrains
> Add JetBrains themes

- .gitmodules
- extensions.toml
Reverts zed-industries/extensions#2641
Failed action run: https://github.com/zed-industries/extensions/actions/runs/14995271378/job/42127884448
> Revert "Add Vue snippets extension"

- .gitmodules
- extensions.toml
Previously:
- https://github.com/zed-industries/extensions/pull/2645
- https://github.com/zed-industries/extensions/pull/2641
> Add Vue snippets (with correct extension ID...)

- extensions.toml
Release notes:
https://github.com/appelgriebsch/zed-crates-lsp/releases/tag/v0.1.1
> Update crates-lsp to v0.1.1

- .gitmodules
- extensions.toml
Codebase: https://github.com/semioz/zed-slack-mcp
NPM package used: https://www.npmjs.com/package/@modelcontextprotocol/server-slack
> Add mcp-server-slack

- .gitmodules
- extensions.toml
This PR adds an MCP server for [Buildkite](https://buildkite.com)
> Add mcp-server-buildkite

- .gitmodules
- extensions.toml
A comprehensive VSCode Dark Modern theme. I've found the other VSCode themes were not aesthetic enough for my taste so I created a version which has in my opinion better contrasts, colour coding, etc - using the official VSCode theme values as much as possible.
> Add vscode-dark-polished

- extensions.toml
Added opacity to scrollbar background for minimap support
> Update modest-dark to v0.1.8

- extensions.toml
See:
- https://github.com/zed-extensions/elixir/pull/11
Includes:
- https://github.com/zed-extensions/elixir/pull/6
- https://github.com/zed-extensions/elixir/pull/9
- https://github.com/zed-extensions/elixir/pull/10
> Update Elixir to v0.1.8

- extensions.toml
v0.0.2
fix scrollbar thumb styles
> Update jetbrains-themes to v0.0.2

- extensions.toml
- https://github.com/mantou132/zed-cspell/issues/6
- https://github.com/mantou132/zed-cspell/issues/5
> Update cspell extension

- .gitmodules
- extensions.toml
Add the MCP extension for Polar: https://github.com/polarsource/zed-polar-context-server
> Add polar-context-server

- extensions.toml
Fixed some inaccuracies in the theme to stay truer to the VSCode Dark Modern theme.
> Update vscode-dark-polished submodule

- .gitmodules
- extensions.toml
This extension adds some highlight bindings from the Tree-Sitter TCL grammar to highlight TCL files. Let me know if I named something poorly.
Thanks!
> Add tcl extension

- .gitmodules
- extensions.toml
This is an extension that adds language features for CSS Modules.
https://github.com/mizdra/css-modules-kit/pull/180
Links
- Extension: https://github.com/mizdra/css-modules-kit/tree/main/crates/zed
- package: https://www.npmjs.com/package/@css-modules-kit/ts-plugin
- package repo: https://github.com/mizdra/css-modules-kit/tree/main/packages/ts-plugin
> Add css-modules-kit

- extensions.toml
Update emerald-night submodule to version 0.0.2
> Update emerald-night to v0.0.2

- .gitmodules
- extensions.toml
This PR introduces the Azutiku Dark theme, with a gentle, soft palette that's easy on the eyes:
Source repo: https://github.com/bwind/zed-azutiku-theme
> Add azutiku-theme

- .gitmodules
- extensions.toml
Added snippet definitions for all basic tags.
> Update Liquid-snippets to v0.0.2

- extensions.toml
Improve contrast between comment/predictive and text.
> Update Melange theme to v0.0.6

- extensions.toml
Release notes:
https://github.com/akbxr/zed-mcp-server-context7/releases/tag/v0.0.3
> Update mcp-server-context7 to v0.0.3

- .gitmodules
- extensions.toml
- removes a default brown color that was hard to read on the gray background 
- changes some UI elements to be more readable in general
> Update Ezio Theme to v0.0.6

- extensions.toml
Improves indentation
- Includes: https://github.com/zed-extensions/swift/pull/30
- Diff: https://github.com/zed-extensions/swift/compare/8d710c0..c63b25a
> Update Swift to v0.4.1

- extensions.toml
Adds support for the [kotlin-lsp](https://github.com/kotlin/kotlin-lsp)
> Update Kotlin to v0.1.2

- extensions.toml
Includes: 
- https://github.com/zed-extensions/prisma/pull/10
- https://github.com/zed-extensions/prisma/pull/9
- https://github.com/zed-extensions/prisma/pull/5
> Update Prisma to v0.1.1

- extensions.toml
Release notes:
https://github.com/jmesrje/zed-charmed-icons/releases/tag/v0.9.1
> Update charmed-icons to v0.9.1

- extensions.toml
> Update Julia to v0.1.5

- extensions.toml
- Add missing syntax highlights
> Update 0x96f theme to v1.3.5

- .gitmodules
- extensions.toml
I have updated my extensions theme (added a light version of my existing theme)
> Update marble theme to v0.2.0

- .gitmodules
- extensions.toml
Add neon-pulse-theme (https://github.com/ArnoldWW/neon-pulse-theme)
> Add neon-pulse-theme

- extensions.toml
Scrollbar thumbs had a new active_background element added, so let's do the same!
> Update monokai-nebula to 0.2.1

- extensions.toml
Closes oWretch/zed-extension-bicep#3
> Update Bicep to v1.1.0

- extensions.toml
Release notes:
https://github.com/appelgriebsch/zed-crates-lsp/releases/tag/v0.2.0
> Update crates-lsp to v0.2.0

- extensions.toml
See:
- https://github.com/zed-extensions/vue/pull/44
> Update Vue to v0.2.6

- .gitmodules
- extensions.toml
- package.json
- Add Blackrain theme as a new submodule
- Register Blackrain theme in the extensions configuration
> Add Blackrain theme

- extensions.toml
better syntax highlighting and correct an previously invalid extension.toml
> Update Angular to v0.0.3

- extensions.toml
Release notes:
https://github.com/JacobCallahan/monokai-nebula-zed/releases/tag/v0.2.2
> Update monokai-nebula to v0.2.2

- .gitmodules
- extensions.toml
This PR adds a new extension named React Snippets, designed for JavaScript and JSX development with React. It includes a collection of helpful snippets such as functional components, console.log, and common hooks to speed up the development process in React projects.
> Add react-snippets extension

- extensions.toml
https://github.com/caius/zed-make/releases/tag/v1.1.1
> Upgrade make extension to v1.1.1

- .gitmodules
- extensions.toml
An MCP server extension for [Resend](https://resend.com/docs/knowledge-base/mcp-server).
> Add Resend MCP server

- extensions.toml
> Update version and add fixes to the Resend MCP extension

- extensions.toml
Update theme Rainbow to v1.0.0
> Update Rainbow theme to v1.0.0

- extensions.toml
[fix: Set text accent color for readability](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/f564e7a857aef2cb8b38b1806b1fd002f06cef41)
[feat: Add player cursor and selection colors to theme configuration](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/0db9a12fe08755548b433763be49a448ac119913)
[add: new config options for scrollbar.thumb.active_background](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/5de717e18c6d2ff6c48a456001a57ee783057bff)
[feat: Add minimap thumb colors and border to theme configuration](https://github.com/SuperGregM/SuperGreatMonokai-Zed/commit/f5201449442eb98644b89c30104823c5f8d05969)
> Update supergreatmonokai to v0.0.3

- extensions.toml
Update neon pulse theme V1.1.0
https://github.com/ArnoldWW/neon-pulse-theme/releases/tag/v1.1.0
> Update neon-pulse-theme to v1.1.0

- .gitmodules
- extensions.toml
A new theme that blends really well with the new [native macOS tabs feature](https://github.com/zed-industries/zed/pull/32238)
> Add Spiceflow theme

- .gitmodules
- extensions.toml
- package.json
> Update blackrain-theme to v0.1.1

- .gitmodules
- extensions.toml
- updated `README` to remove unneccessary dependency
- updated `extension.toml` and `cargo.toml` to reflect semver bump
- updated `.gitignore` to ignore a debugging script and `cargo.lock`
- updated `src/lib.rs` to use different language server binary
- added `.gitbook.yaml` to enable gitbook functionality
> Update sieve to v0.1.7

- extensions.toml
Brings in the version that updates the treesitter grammar and slightly improves the highlighting queries
> Update Unison to v0.0.6

- .gitmodules
- extensions.toml
add sqlc-snippets to extensions zed
> Add sqlc-snippets

- .gitmodules
- extensions.toml
I have added new theme Supaglass which is inpsired from supabase and bring to Zed IDE Extension theme.
> Add Supaglass Theme

- .gitmodules
- extensions.toml
Hi Zed Team 👋
This PR adds a new extension as a Git submodule:
🔗 https://github.com/Konstantinos-Ps/zed-nextjs-react-snippets
It includes useful snippets for modern Next.js + React workflows, including:
App Router-based structure
API endpoints
Component templates
Tailwind + ShadCN-friendly patterns
Let me know if anything needs adjusting. Appreciate everything you’re doing!
— Konstantinos
> Add nextjs-react-snippets

- .gitmodules
- extensions.toml
> Add fastapi-snippets extension

- extensions.toml
Fix title bar inactive background color
> Update jetbrains-themes to v0.0.4

- extensions.toml
Release notes:
https://github.com/JacobCallahan/monokai-nebula-zed/releases/tag/v0.2.3
> Update monokai-nebula to v0.2.3

- .gitmodules
- extensions.toml
- Jetbrains Rider Light Theme
- Jetbrains Rider Dark Theme
> Add jetbrains-rider theme extension

- extensions.toml
https://github.com/biomejs/biome-zed/releases/tag/v0.2.0
> Update biome to v0.2.0

- .gitmodules
An MCP server to retrieve Material UI documentation data.
> Add the Material UI MCP server extension

- extensions.toml
Fixing a problem with the binary installation location upon trying to configure this server.
> Fix Material UI MCP server binary

- extensions.toml
See: 
- https://github.com/zed-extensions/dart/pull/19
Includes:
- https://github.com/zed-extensions/dart/pull/17
> Update Dart to v0.2.1

- extensions.toml
Release notes:
https://github.com/JacobCallahan/monokai-nebula-zed/releases/tag/v0.2.4
> Update monokai-nebula to v0.2.4

- extensions.toml
Changes in this release:
- Added support for language GDShader
- Added missing constructor method in outline for the GDScript language
> Update gdscript to v0.5.0

- extensions.toml
Release notes:
https://github.com/treffynnon/zed-Paraiso/releases/tag/1.0.2
> Update paraiso to v1.0.2

- .gitmodules
- extensions.toml
https://github.com/huacnlee/color-lsp
> Add color-highlight

- .gitmodules
- extensions.toml
Add [GitHub Plus Themes](https://github.com/thenikso/github-plus-theme-zed)
> Add github-plus-theme extension

- .gitmodules
- extensions.toml
> Add IBM 5151 theme extension

- extensions.toml
Update to v0.0.3
- Add new style attributes
- Make Git blame less distracting
> Update Alabaster Dark to v0.0.3

- extensions.toml
- Improve CSS colors
- fix the colors of the debugger panel
> Update jetbrains-themes to v0.0.5

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-laravel-blade/releases/tag/v0.1.2
> Update blade to v0.1.2

- extensions.toml
Release notes:
https://github.com/DogukanUrker/DogiZed/releases/tag/1.0.3
> Update dogi to v1.0.3

- .gitmodules
- extensions.toml
Adding a new theme extension. Hopefully got all the things sorted out right.
https://github.com/snapsnapturtle/retrofit-zed
> Add retrofit theme extension

- .gitmodules
- extensions.toml
Added missing $schema line to martianized.json
> Update Martianized to v1.0.1

- extensions.toml
Release notes: https://github.com/valentinegb/zed-groovy/releases/tag/v1.2.0
> Update groovy to v1.2.0

- extensions.toml
Update scrollbar.thumb colors so the Minimap uses the right colors
- scrollbar.thumb.hover_background
- scrollbar.thumb.background
> Update gentle-dark to v1.2.1

- extensions.toml
This PR updates the Lua extension to v0.1.3.
> lua: Update to v0.1.3

- extensions.toml
> Update Codebook to v0.1.8

- extensions.toml
Release notes:
https://github.com/Jean-Tinland/zed-theme-night-shift/releases/tag/v1.0.3
> Update night-shift to v1.0.3

- extensions.toml
Adds Solidity support.
Release notes:
https://github.com/Stef16Robbe/harper_zed/releases/tag/v0.0.5
> Update harper to v0.0.5

- .gitmodules
- extensions.toml
This PR adds a new theme to the Zed extensions library called "Darkmatter"
> Add Darkmatter theme

- .gitmodules
- extensions.toml
> Add Forest Night Theme

- .gitmodules
- extensions.toml
Add support for [Typespec](https://typespec.io/).
- Tree-sitter: https://github.com/happenslol/tree-sitter-typespec
- Language server: `tsp-server` from https://www.npmjs.com/package/@typespec/compiler
Closes: https://github.com/zed-industries/extensions/issues/2587
> Add typespec extension

- extensions.toml
- Adds TypeScript to supported languages
> Update Stylelint to 1.0.1

- extensions.toml
Diving deep into some issues I suspected. Hoping this works properly because NixOS makes testing hard. Also trying to add an LSP...
> Update Fountain to v0.2.0

- extensions.toml
Release notes:
https://github.com/Stef16Robbe/harper_zed/releases/tag/v0.0.6
> Update harper to v0.0.6

- extensions.toml
- justfile
Hi, this PR updates the slint extension to the latest + adds a command to justfile to help update an extension (I though it would come in handy to other people).
> Slint: update to `0.0.9`

- .gitmodules
- extensions.toml
Adds a port of the Tron Legacy extension to zed. 
https://github.com/bcomnes/zed-theme-tron-legacy#
> Add tron-legacy theme

- extensions.toml
tree-sitter diff: https://github.com/smrtrfszm/tree-sitter-blueprint/compare/b3a05548b37cf28bb901a2a3a07e7bfe6b299f73...d7548077ad2f2cb2288e9e5d5ecf24ac5b7921f4
> Update Blueprint to v0.3.1

- extensions.toml
> Update jetbrains-themes to v0.0.7

- extensions.toml
See: 
- https://github.com/zed-extensions/git_firefly/pull/19
> Update git-firefly to v0.1.0

- extensions.toml
This PR updates the Code::Stats extension to v0.2.7.
> code-stats: Update to v0.2.7

- extensions.toml
Includes: 
- https://github.com/zed-extensions/git_firefly/pull/23
> Update git-firefly to v0.1.1

- extensions.toml
- Add overlay background and hover colors
- Add version control conflict markers
> Update vitesse-theme-refined to v0.2.0

- extensions.toml
Release notes:
- https://github.com/cange/nightfox.zed/releases/tag/v0.5.1
- https://github.com/cange/nightfox.zed/releases/tag/v0.5.0
> Update nvim-nightfox to v0.5.1

- extensions.toml
This PR updates the Gleam extension to v0.5.1.
> gleam: Update to v0.5.1

- extensions.toml
Release notes:
https://github.com/JacobCallahan/monokai-nebula-zed/releases/tag/v0.2.5
> Update monokai-nebula to v0.2.5

- extensions.toml
Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.5.2
> Update nvim-nightfox to v0.5.2

- .gitmodules
- extensions.toml
- Use a color within the existing palette for labels
> Bump Yaka theme to v0.0.4

- extensions.toml
- Bumped cql extension version to v1.0.1
- Updated submodule reference to the latest upstream commit
- Tree Sitter minor [bug fixes](https://github.com/Akzestia/tree-sitter-cql/commit/d059d417fd9b8dc1acaeab7a9333835a5ba5ff4b)
- Language server release [v1.0.1](https://github.com/Akzestia/cql-lsp/releases/tag/v1.0.1)
> Update CQL extension to v1.0.1

- .gitmodules
- extensions.toml
At the moment there is only 2 snippets but tomorrow i will add some more
> Add rust-snippets extension

- .gitmodules
- extensions.toml
I like this theme is VS Code and the current Zed implementations did not feel complete enough:
I intend on adding variable monaspace fonts for LLMs eventually, and enhancing the glow effect further.
> Add synthwave84 theme

- .gitmodules
- extensions.toml
> Add Cursor Theme

- .gitmodules
- extensions.toml
This extension supports TON Blockchain languages: Tolk, Tact, Func, Fift and TL-B
- Extension: https://github.com/Bionic2113/ton-zed/
- Tree-sitters:
- https://github.com/ton-blockchain/tree-sitter-tolk
- https://github.com/tree-sitter-grammars/tree-sitter-func
- https://github.com/nickshatilo/tree-sitter-tlb
- https://github.com/tact-lang/tree-sitter-tact
- https://github.com/Bionic2113/tree-sitter-fift
- Language servers:
- https://github.com/ton-blockchain/ton-language-server
- https://github.com/tact-lang/tact-language-server
> Add TON extension

- .gitmodules
- extensions.toml
This adds the Shader Language Server extension.
LSP: https://github.com/antaalt/shader-sense/tree/main/shader-language-server
> Add Shader-ls extension

- .gitmodules
- extensions.toml
Adds the Autumnal Marscape theme, an original red, pink, and orange theme.
> Add autumnal-marscape theme

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-laravel-blade/releases/tag/v0.2.0
> Update blade to v0.2.0

- extensions.toml
Includes:
- https://github.com/zed-extensions/dart/pull/23
> Update dart to v0.2.2

- extensions.toml
fix the error and warning colors
> Update oldbook-theme to v1.5.0

- extensions.toml
Includes:
- https://github.com/nathansbradshaw/zed-angular/pull/53
> Update Angular to v0.0.4

- extensions.toml
> Update oldbook-theme to v1.5.1

- extensions.toml
Includes:
- https://github.com/zed-extensions/ty/pull/11
> Update ty to v0.0.3

- extensions.toml
TS Diff: https://github.com/padenot/tree-sitter-webidl/compare/92f2fd41f79a9d11ec12199b7f6b5240cf35fcc4...e6870d31a485bf021f12e0f72a44eefc57173f93
> Update webidl to v0.0.2

- extensions.toml
> Update catppuccin-blur to v0.3.0

- extensions.toml
- Improves constants colors
- Aligns background colors with the VSCode ones
- Stabilizes the experimental theme
> Update Lydia theme to 0.0.4

- extensions.toml
Release notes:
https://github.com/DogukanUrker/DogiZed/releases/tag/1.0.4
> Update dogi to v1.0.4

- extensions.toml
- Update package-swift-lsp extension to version 1.1.0
- Update submodule to latest commit
- Sync version in extensions.toml with extension.toml
- extensions.toml: version 1.0.0 → 1.1.0
- extensions/package-swift-lsp: updated to latest commit
> Update package-swift-lsp to v1.1.0

- extensions.toml
https://github.com/scalameta/metals-zed/releases/tag/0.1.4
> Update Scala to v0.1.4

- extensions.toml
This improves contrast and readability, particularly for function and
type scopes. Adds explicit styling for interfaces.
> Update jetbrains-themes to v0.0.8

- .gitmodules
- extensions.toml
This theme bathes the Zed editor in a warm palette of rosé pink, banana yellow, and lavender, based on the PinkCatBoo VS Code theme.
> Add Rosévin (rosevin) theme

- .gitmodules
- extensions.toml
Changes:
- Fixed editor.subheader.background visibility issue in Matrix theme
- Improved ghost_element.selected contrast for better readability
- Updated repository URL to new maintainer
> Update hacker-theme to v1.0.1

- .gitmodules
- extensions.toml
Adds [Elderberry](https://github.com/IronGeek/zed-theme-elderberry) theme.
> Add Elderberry theme

- extensions.toml
- add deleted.background and deleted.border
- update success and hint colors
> Update oldbook-theme to v1.5.4

- .gitmodules
- extensions.toml
An extension bringing syntax highlighting to JSP files
> Add JSP (JavaServer Pages) language extension

- .gitmodules
- extensions.toml
Extension: [BlockLune/zed-wxml](https://github.com/BlockLune/zed-wxml)
TreeSitter: [BlockLune/tree-sitter-wxml](https://github.com/BlockLune/tree-sitter-wxml)
> Add WXML extension

- .gitmodules
- extensions.toml
Extension: [yuna0x0/zed-ink](https://github.com/yuna0x0/zed-ink)
Tree-sitter: [rhizoome/tree-sitter-ink](https://github.com/rhizoome/tree-sitter-ink)
Language Server: [yuna0x0/ink-lsp](https://github.com/yuna0x0/ink-lsp/releases)
> Add Ink extension

- extensions.toml
* adds spicedb lsp support, there's some missing functionality, but i think it's do to the zed editor, I have a thread in discord open to speak about it in both spicedb, and zed
> Update authzed to v0.0.2

- .gitmodules
- extensions.toml
> Update Cursor theme to v1.1.2

- extensions.toml
- Fix indent
- Add example story FadingEchoes
**Full Changelog**: https://github.com/yuna0x0/zed-ink/compare/v0.0.1...v0.0.2
> Update Ink to v0.0.2

- extensions.toml
Release notes:
https://github.com/cange/nightfox.zed/releases/tag/v0.6.0
> Update nvim-nightfox to v0.6.0

- extensions.toml
Add match syntax highlight to blackrain theme
> Update blackrain-theme to v0.1.3

- .gitmodules
- extensions.toml
> Add Kiro Theme

- .gitmodules
- extensions.toml
adds an extension for the zwirn live coding language
> Add Zwirn extension

- .gitmodules
- extensions.toml
This time I removed dots from extension IDs which caused its instant removal (#2983).
> Add todotxt extension

- extensions.toml
Release notes:
https://github.com/oWretch/zed-extension-bicep/releases/tag/v1.2.1
> Update bicep to v1.2.1

- .gitmodules
- extensions.toml
see https://bennypowers.dev/cem
> Add cem extension

- .gitmodules
- extensions.toml
The grammar is from https://github.com/flurie/tree-sitter-jq
A screenshot:
> Add jq extension

- .gitmodules
- extensions.toml
- src/lib/validation.js
- 🚀 Zed extension publishing workflow.
- 🔧 reorganize test files and update project configuration.
- 🐛 Pass file path to PHPCS for linting of file properties.
> Update PHPCS to v0.1.5

- .gitmodules
- extensions.toml
Hi! I would like to add [Zoegi theme](https://github.com/nikitapashinsky/zoegi-theme) to the extension gallery.
> Add Zoegi theme

- extensions.toml
Follow-up to https://github.com/zed-industries/extensions/pull/2447
> Remove denix extension from `extensions.toml`

- extensions.toml
- Added light theme
- Added script helpers to generate the theme JSON file
- Updated status (error, success) color backgrounds to be same as other panels
> Update Monospace theme to 0.2.0

- .gitmodules
- extensions.toml
> Add slang extension

- extensions.toml
[Release notes](https://docs.ruuda.nl/rcl/changelog/#0100)
> Update RCL to v0.10.0

- extensions.toml
Release notes:
https://github.com/pest-parser/zed-pest/releases/tag/v0.1.1
> Update pest to v0.1.1

- .gitmodules
- extensions.toml
Add new cpp language server [clice](https://github.com/clice-project/clice).
clice is a next-generation language server designed for modern C++. Through excellent asynchronous task scheduling and intelligent caching, it achieves a lower memory footprint and faster response times.
> Add clice extension

- extensions.toml
Release notes:
https://github.com/huacnlee/color-lsp/releases/tag/zed-v0.1.2
> Update color-highlight to v0.1.2

- extensions.toml
Includes: 
- https://github.com/zed-extensions/elixir/pull/36
> elixir: Update to v0.2.3

- .gitmodules
- extensions.toml
fix <https://github.com/oxc-project/zed-oxc/issues/13>
> Update oxc to v0.3.2

- .gitmodules
- extensions.toml
This update brings an improvement in parsing complex EdgeJS files.
> Update Edge to v0.2.0

- extensions.toml
- Update new snippets
- Create simple README.md
> Update fastapi-snippets to v0.2.0

- extensions.toml
Added initial support for language server from [vscode-as3mxml](https://github.com/BowlerHatLLC/vscode-as3mxml/tree/main/language-server).
Closes #269
> Update ActionScript to v0.1.0

- .gitmodules
- extensions.toml
This adds a Zed theme based on the [vscode-chester-atom](https://github.com/ceckenrode/vscode-chester-atom) theme for VS Code.
> Add Lonely Planet theme

- extensions.toml
- [⚙️ Add GitHub action](https://github.com/zarifpour/zed-solidity/pull/18)
- [🚚 Move release.yml](https://github.com/zarifpour/zed-solidity/commit/14ffe9f74a1393adc92bbdababdc3c5b0e642ca0)
- [⚙️ Update cargo, extension version, and deps](https://github.com/zarifpour/zed-solidity/pull/19)
- [🖍️ Add missing highlights](https://github.com/zarifpour/zed-solidity/pull/24)
- [📦 Fix extension packaging config](https://github.com/zarifpour/zed-solidity/pull/25)
- [⚙️ Fix/update cargo lock (#26)](https://github.com/zarifpour/zed-solidity/pull/26)
> Bump Solidity to v0.1.5

- .gitmodules
- extensions.toml
- src/lib/validation.js
Adding PHPMD extension based on my PHPCS extension.
https://github.com/GeneaLabs/zed-phpmd-lsp
PS: sorry for the messy commit history -- I cloned the PHPCS repo and I forgot that it would leave the entire PHPCS repo history in there.
> Add PHPMD extension

- extensions.toml
Update mcp-server-tavily extension to v0.0.2
Fix chlorodose/zed-mcp-server-tavily#2
> Update tavily extension to v0.0.2

- .gitmodules
- extensions.toml
This adds the treesitter grammar for textproto published here: https://github.com/PorterAtGoogle/tree-sitter-textproto
This is the extension: https://github.com/mikn/zed-textproto
> Add textproto extension

- extensions.toml
Updates crimson theme to 0.0.2
> Update Crimson Theme to v0.0.2

- .gitmodules
- extensions.toml
Fixed missing `function.method` color
> Update Vynora theme to v0.0.3

- extensions.toml
Release notes:
https://github.com/bajrangCoder/zed-scss/releases/tag/v0.1.2
> Update scss to v0.1.2

- extensions.toml
Release notes:
https://github.com/vitallium/zed-marksman/releases/tag/v0.2.0
> Update marksman to v0.2.0

- extensions.toml
[Changelog](https://github.com/11bit/zed-extension-graphql/blob/main/CHANGELOG.md)
> Update graphql to v1.0.3

- extensions.toml
* Fix some snippets 
* Add >= operator
> Update VHDL extension to v0.0.2

- extensions.toml
Changes:
- Do not use bold font
- Update link colors
> Update jetbrains-themes to v0.1.2

- extensions.toml
This update introduces a language server for Stan.
> Update stan to v1.0.0

- .gitmodules
- extensions.toml
Adds comprehensive HTML snippets extension with 95+ snippets covering all HTML5 elements.
Features:
- Complete HTML5 coverage
- Smart placeholders
- Semantic elements
- Form controls
- Media elements
> Add HTML Snippets extension

- extensions.toml
> Bump cspell to 0.5

- .gitmodules
- extensions.toml
A comprehensive collection of TypeScript snippets for [Zed editor](https://zed.dev/), designed to accelerate TypeScript development with intelligent type support and modern patterns.
- **Complete TypeScript Coverage**: 200+ snippets covering types, interfaces, generics, and advanced features
- **Type-First Approach**: All snippets include proper TypeScript type annotations
- **Short & Convenient Prefixes**: VSCode-inspired short prefixes for faster coding
- **Smart Placeholders**: Tab-navigable placeholders for efficient coding
- **Modern TypeScript**: Support for latest TypeScript features including utility types, decorators, and more
- **Async/Await Support**: Modern asynchronous programming patterns with proper typing
- **Advanced Types**: Generics, conditional types, mapped types, and …
> Add TypeScript Snippets extension

- extensions.toml
Release notes:
https://github.com/akbxr/firecrawl-mcp-zed/releases/tag/v0.0.4
> Update mcp-server-firecrawl to v0.0.4

- extensions.toml
Updated grammar and potentially fix windows installation bug
> Update wgsl-wesl extension
