.gitmodules, extensions.toml
Adds some basic syntax highlighting for assembly files (`.asm`, `.s`, `.S`)
Example:
=> Add Assembly Syntax Extension

.gitmodules, extensions.toml
This adds [the Srcery theme](https://srcery.sh/) for Zed, created by importing the srcery theme for vscode.
=> Add srcery theme

extensions.toml
This commit bumps the base16 theme to `v0.0.3`, which adds specific colors for:
- The background of tabs when they are being dragged
- The heading of search results
- Predictive text
=> Bump base16 to v0.0.3

.gitmodules, extensions.toml
Initial attempt, allows `Makefile` language to show up and hard tabs be configured in the settings to make editing the files easier. Doesn't contain any syntax highlighting yet as I can't get a valid `highlights.scm` file in place so far.
Haven't looked if the language toml or extension toml can set hard tabs or tab width settings, it's just in the readme for now for people to add to their Zed settings by hand.
This is extracted from https://github.com/zed-industries/zed/pull/7402 as that didn't land before Extensions came into the world 😻
=> Add caius/zed-make for Makefile support

extensions.toml
Which adds support for base-16-black-metal-bathory.
=> Bump base16 theme to v0.0.4

package.json, pnpm-lock.yaml, src/package-extensions.js, tsconfig.json
This PR sets up the packaging script to be type-checked using TypeScript.
Note that the files themselves are still 100% plain JS, so no transpilation step is needed. This is solely so we can get some more type safety in the code.
=> Type-check packaging script using TypeScript

vite.config.mjs
This PR changes the Vitest config to use `root` instead of `dir` to locate the right test files.
`dir` is what we want, as we just want to change where we're looking for tests, not what Vitest thinks is the root directory.
=> Use `dir` instead of `root` in Vitest config

.github/workflows/ci.yml, src/package-extensions.js
This PR changes the packaging script to only checkout the submodules for extensions that need publishing.
This should make CI run faster, as we don't need to checkout all of the submodules up front.
=> Only checkout submodules of extensions that need publishing

extensions.toml
- Bumped version to `1.0.0`
- Adjusted error background color from `null` to `#d19a66` which fixes https://github.com/zed-industries/zed/issues/8254
=> Smooth Theme: Bump version to 1.0.0

.gitmodules, extensions.toml
This pull request introduces the "Material Dark" theme to the Zed IDE, offering a sleek and modern dark theme that aligns with the Material Design guidelines. The theme is designed to provide a visually appealing and comfortable development environment, especially for developers who prefer dark mode for extended coding sessions.
- Added the Material Dark theme as a submodule in the `extensions/material-dark-theme` directory.
- Updated the `extensions.toml` file to include the new Material Dark theme with the following entry:
```toml
[material-dark-theme]
path = "extensions/my-material-dark-theme"
version = "1.0.0"
```
The theme has been tested locally within the Zed IDE to ensure compatibility and a consistent user experience across various file types and programming languages. It adheres …
=> Add Material Dark Theme Extension

.gitmodules, extensions.toml
Prev: [#7048](https://github.com/zed-industries/zed/issues/7048), Let's roll git highlighting back into the extension
> Because tree-sitter-gitcommit slows down the compilation of zed 😅 (https://github.com/zed-industries/zed/pull/7147#issuecomment-1937722323 / https://github.com/zed-industries/zed/issues/7048#issuecomment-1979620553)
Support syntax highlighting 
- git_commit
- git_config
- git_rebase
- git_diff(.diff)
- gitignore
- gitattributes
cc @williamdes @SomeoneToIgnore
=> Add git-firefly

src/lib/validation.js
This PR updates the validation rules to disallow "Zed" at the end of extension names and IDs, just like at the start.
=> Disallow "Zed" at the end of extension names and IDs

extensions.toml
Bump GraphQL extension to v0.0.2
[Release notes](https://github.com/11bit/zed-extension-graphql/blob/main/CHANGELOG.md#002--2024-12-04)
=> Bump GraphQL extension to v0.0.2

src/lib/git.js, src/lib/validation.js, src/lib/validation.test.js, src/package-extensions.js
This PR adds some validation for `.gitmodules` to prevent non-HTTPS submodule URLs.
Cloning down submodules that don't use HTTPS is a hassle in CI, so we want to enforce this.
=> Validate `.gitmodules` to prevent non-HTTPS URLs

.github/workflows/ci.yml
This PR bumps the version of the extension CLI to https://github.com/zed-industries/zed/commit/adcb591629cbcbd5e75fdaf775de267f64eff064.
=> Bump extension CLI to `adcb591`

.github/workflows/ci.yml, .gitmodules, extensions.toml, src/lib/git.js, src/package-extensions.js
These extensions are currently included in the Zed repo. Because they use a newer version of the Zed extension schema, they will not be shown in the extension view for Zed versions < 0.129.
=> Add Svelte, Gleam, and Uiua extensions

.gitmodules, extensions.toml
This theme is adapted to Zed from the [VS Code theme of the same name][vscode-theme], which in turn is based on the [TextMate theme][tm-theme] of the same name.
[vscode-theme]: https://github.com/treffynnon/paraiso-dark-vscode-theme "Paraíso VS Code theme"
[tm-theme]: https://github.com/idleberg/Paraiso.tmTheme "Paraíso TextMate theme"
Licenced under the [Creative Commons Attribution-ShareAlike 3.0 Unported][licence] licence.
```
Name:    Paraíso (dark)
Author:  Jan T. Sott
License: Creative Commons Attribution-ShareAlike 3.0 Unported License
URL:     https://github.com/idleberg/Paraiso.tmTheme
Inspired by the art of Rubens LP (http://www.rubenslp.com.br)
Base16 template for TextMate by Chris Kempson (https://github.com/chriskempson)
```
[licence]: …
=> Add Paraíso theme

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/053d05f6f5da63440aa35c92a9553a650ae8f98f.
=> Bump extension CLI version to `053d05f`

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/5adc51f113c6646306e74fc22f4c1d1292b5daa5.
=> Bump extension CLI version to `5adc51f`

extensions.toml
This PR adds the Prisma extension.
Prisma support was extracted from Zed in https://github.com/zed-industries/zed/pull/9820.
=> Add Prisma extension

extensions.toml
This PR adds the PureScript extension.
PureScript support was extracted from Zed in https://github.com/zed-industries/zed/pull/9824.
=> Add PureScript extension

extensions.toml
This PR adds the Astro extension.
PureScript support was extracted from Zed in https://github.com/zed-industries/zed/pull/9835.
=> Add Astro extension

extensions.toml
This PR updates the Gleam extension to v0.0.2.
This version of the extension will now respect any `gleam` binary on the PATH.
=> Update Gleam to v0.0.2

extensions.toml
This PR adds the Zig extension.
Zig support was extracted from Zed in https://github.com/zed-industries/zed/pull/9893.
=> Add Zig extension

extensions.toml
Now contains Makefile syntax highlighting!
Also upgraded to the new `extensions.toml` configuration and tidied up some bits in the repository.
Loaded as a Dev Extension in Zed Preview and it functions as expected locally.
=> Upgrade Make to 1.0.0

extensions.toml
Updates the extension to use the [freshly documented](https://github.com/zed-industries/extensions/commit/6ab7d4253b6de77025a586e6afc808f668098eac) extension.toml format instead of extension.json.
=> Update Paraíso to extension.toml format

.github/workflows/ci.yml
This PR updates the extension CI to cache the `zed-extension` CLI and only download it from the blob store when needed.
I've been seeing some slow, multi-minute downloads every once in a while, so it seems like the caching may be worth it.
=> Cache the `zed-extension` CLI

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/764e2567557da7c6cf1beeba1462e79cf7260f98.
=> Bump extension CLI version to `764e256`

extensions.toml
This PR adds the PHP extension.
PHP support was extracted from Zed in https://github.com/zed-industries/zed/pull/9966.
=> Add PHP extension

extensions.toml
This PR adds the C# extension.
C# support was extracted from Zed in https://github.com/zed-industries/zed/pull/9971.
=> Add C# extension

.github/workflows/ci.yml
This PR updates the cache key we use for the `zed-extension` binary to have some additional context than just the Git SHA.
=> Update `zed-extension` cache key

extensions.toml
This PR adds the Erlang extension.
Erlang support was extracted from Zed in https://github.com/zed-industries/zed/pull/9974.
=> Add Erlang extension

extensions.toml
I mostly copied the gleam extension, and I believe this works well, however I would love some feedback on the extension's code. 
And how important is it to support aarch platforms? I only support x86_64 right now
=> Use the binary release for Markdown Oxide

extensions.toml
- closes https://github.com/zed-industries/zed/issues/10024
- use `extension.toml` instead of `extension.json`
=> Bump catppuccin to 0.2.4

extensions.toml
This PR adds the Clojure extension.
Clojure support was extracted from Zed in https://github.com/zed-industries/zed/pull/10088.
=> Add Clojure extension

extensions.toml
This adds support for LSP via serve-d.  LSP configuration is not yet present, but this already provides useful guidance from DScanner, as well as rudimentary Find References, Rename symbol and similar.
=> Bump D extension to 0.0.3

extensions.toml
This PR adds the HTML extension.
HTML support was extracted from Zed in https://github.com/zed-industries/zed/pull/10130.
=> Add HTML extension

extensions.toml
- Fixes unreadable bright-black in terminal
- Fixes incorrect property colors
- Tunes transparent colors to be more consistent across opaque/blurred/transparent
=> Update Dracula to 0.7.3

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/b6857ca469293112a89784817fba0685b1553892.
=> Bump extension CLI version to `b6857ca`

extensions.toml
This PR adds the Dart extension.
Dart support was extracted from Zed in https://github.com/zed-industries/zed/pull/10212.
Note: The Dart extension requires a minimum Zed version of v0.131.x.
=> Add Dart extension

extensions.toml
Tested to work in zed 0.130.3 and up, locally. Zed 0.129.2 too, but only JavaScript support.
https://github.com/zed-industries/zed/issues/10256
=> Update biome extension to 0.0.2

extensions.toml
This PR updates the Gleam extension to v0.1.0.
This version of the extension contains improved completion labels:
This version of the Gleam extension requires Zed v0.131.x or higher.
=> Update Gleam to v0.1.0

extensions.toml
This PR updates the Haskell extension to v0.1.0.
This version of the extension contains improved symbol labels:
This version of the Haskell extension requires Zed v0.131.x or higher.
=> Update Haskell to v0.1.0

extensions.toml
This PR updates the Emmet extension to v0.0.2.
This version of the extension adds support for PHP and ERB files with Emmet (when using Zed v1.131.0 and above).
=> Update Emmet to v0.0.2

extensions.toml
- Remove Redrum theme
- Increase remaining themes' background opacity from #xxxxxx77 to #xxxxxxAA
=> Update Glazier to 0.0.2

extensions.toml
Release notes:
https://github.com/navi-language/zed-navi/releases/tag/v0.2.0
=> Update navi to 0.2.0

extensions.toml
Release notes:
https://github.com/huacnlee/zed-csv/releases/tag/v0.0.2
=> Update csv to 0.0.2

extensions.toml
This PR updates the PHP extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10480 for the changes in this version.
=> Update PHP to v0.0.2

extensions.toml
This PR updates the Zig extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/10481 for the changes in this version.
=> Update Zig to v0.1.0

extensions.toml
This PR updates the TOML extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/10482 for the changes in this version.
=> Update TOML to v0.1.0

extensions.toml
This PR adds the Elm extension.
Elm support was extracted from Zed in https://github.com/zed-industries/zed/pull/10432.
=> Add Elm extension

extensions.toml
This PR adds the GLSL extension.
GLSL support was extracted from Zed in https://github.com/zed-industries/zed/pull/10433.
=> Add GLSL extension

extensions.toml
This PR adds the Scheme extension.
Scheme support was extracted from Zed in https://github.com/zed-industries/zed/pull/10442.
=> Add Scheme extension

extensions.toml
This PR adds the Racket extension.
Racket support was extracted from Zed in https://github.com/zed-industries/zed/pull/10442.
=> Add Racket extension

extensions.toml
This PR adds the Lua extension.
Lua support was extracted from Zed in https://github.com/zed-industries/zed/pull/10437.
=> Add Lua extension

extensions.toml
This PR adds the OCaml extension.
OCaml support was extracted from Zed in https://github.com/zed-industries/zed/pull/10450.
=> Add OCaml extension

extensions.toml
This PR adds the Terraform extension.
Terraform support was extracted from Zed in https://github.com/zed-industries/zed/pull/10479.
Note that the Terraform extension requires Zed v0.132.x (which will be released this coming Wednesday) in order for some problematic code action kinds to be filtered out from the language server.
=> Add Terraform extension

extensions.toml
This PR adds the Vue extension.
Vue support was extracted from Zed in https://github.com/zed-industries/zed/pull/10486.
Note that the Terraform extension requires Zed v0.132.x (which will be released this coming Wednesday) in order for some problematic code action kinds to be filtered out from the language server.
=> Add Vue extension

src/lib/fs.js, src/package-extensions.js
This PR adds a warning when an `extension.json` manifest is detected.
`extension.toml` should be preferred instead.
=> Warn when using `extension.json`

extensions.toml
This fixes a failure to load the extension, since the previous version relied on Tree-sitter C++ external scanners, which is no longer supported.
=> Bump beancount to 0.0.2

extensions.toml
This PR updates the Zig extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/10645 for the changes in this version.
=> Update Zig to v0.1.1

extensions.toml
This PR updates the Gleam extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/10648 for the changes in this version.
=> Update Gleam to v0.1.1

extensions.toml
This PR updates the Clojure extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10650 for the changes in this version.
=> Update Clojure to v0.0.2

extensions.toml
This PR updates the C# extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10651 for the changes in this version.
=> Update C# to v0.0.2

extensions.toml
This PR updates the Terraform extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10653 for the changes in this version.
=> Update Terraform to v0.0.2

.gitmodules, extensions.toml
This extension uses a tree-sitter grammar and adds syntax highlighting for CFEngine policy files to Zed.
All major features of the langauge are implemented, I don't know of anything which is broken, so far.
Extension: https://github.com/olehermanse/zed-cfengine
Grammar: https://github.com/olehermanse/tree-sitter-cfengine
Example:
=> Add CFEngine extension

extensions.toml
This PR updates the SQL extension to v1.0.0.
This is a continuation of https://github.com/zed-industries/extensions/pull/482.
cc @evrsen
=> Update SQL to v1.0.0

extensions.toml
This PR updates the Prisma extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10689 for the changes in this version.
=> Update Prisma to v0.0.2

.gitmodules, extensions.toml
This adds a Cap'n Proto extension to the Zed extension registry.
https://github.com/cmackenzie1/zed-capnp
https://capnproto.org
=> Add Cap'n Proto extension

extensions.toml
This PR updates the GLSL extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/10734 for the changes in this version.
=> Update GLSL to v0.1.0

extensions.toml
- fix hint coloring
- [catppuccin/alacritty](https://github.com/catppuccin/alacritty/) terminal coloring
=> Bump catppuccin to 0.2.6

AUTHORING_EXTENSIONS.md
The extensions section in Zed v0.131.6 has an `Install Dev Extension` button, while the docs still refer to it as `Add Dev Extension`.
=> Correct docs "Add Dev Extension" -> "Install Dev Extension"

extensions.toml
Updates the path_suffixes to correctly specify ReScript file extensions "res" and "resi"
=> Update ReScript extension

extensions.toml
**What's new**
- The extension should be able to read the binary from the node_modules
=> Bump biome to 0.0.6

extensions.toml
This PR adds the Deno extension.
Deno support was extracted from Zed in https://github.com/zed-industries/zed/pull/10912.
=> Add Deno extension

extensions.toml
This PR updates the Dart extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/10940 for the changes in this version.
=> Update Dart to v0.0.2

.gitmodules, extensions.toml
Let me know if anything is missing!
=> Add initial Unison support

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/5ef75919f09e31c28b75c09e695946b6c4d9c3ee.
=> Bump extension CLI version to `5ef7591`

extensions.toml
This PR adds the Elixir extension.
Elixir support was extracted from Zed in https://github.com/zed-industries/zed/pull/10948.
Since the Elixir extension provides three different language servers,
you'll need to use the `language_servers` setting to select the one you
want to use:
```json
{
"languages": {
"Elixir": {
"language_servers": [ "elixir-ls", "!next-ls", "!lexical", "..."]
}
}
}
```
```json
{
"languages": {
"Elixir": {
"language_servers": [ "next-ls", "!elixir-ls", "!lexical", "..."]
}
}
}
```
```json
{
"languages": {
"Elixir": {
"language_servers": [ "lexical", "!elixir-ls", "!next-ls", "..."]
}
}
}
```
=> Add Elixir extension

.gitmodules, extensions.toml
Moved the changes made in this [PR](https://github.com/zed-industries/zed/pull/8813) to a Java extension. As mentioned in this discussion, @louisnicolas-longheval-vinci doesn't have time to support it. @valentinegb and I have already put a lot of effort not only into LSP support but also into proper syntax highlighting. Because of that, I have decided to create a separate extension for it.
In [extension repository](https://github.com/ABckh/zed-java-language-support-jdtls) I have added list of future improvements, which will be added to the extension
It would close #500
=> Add Java LSP Support

extensions.toml
- fix `inlay_hints` and similar "hint" coloring
- adjust hover and selection coloring on some menus
- more syntax definitions
=> Bump catppuccin to 0.2.7

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.2
=> Update r to 0.0.2

extensions.toml
Update `java-eclipse-jdtls` to version v0.2.0 which introduced completion labels
=> Update java-eclipse-jdtls to v0.2.0

extensions.toml
Added LSP support, by hardcoding `ncat` and adding it as a requirement for the language server in the README.
=> Update Unison extension

extensions.toml
This PR updates the Elixir extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/11303 for the changes in this version.
=> Update Elixir to v0.0.2

extensions.toml
In #649, The PR update new style with extension format(old use .json) and gitignore path_suffixes contains .dockerignore
/cc @eth0net
=> Update git-firefly to v0.0.3

extensions.toml
This PR updates the Elixir extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/11358 for the changes in this version.
=> Update Elixir to v0.0.3

extensions.toml
This PR updates the Elixir extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/11359 for the changes in this version.
=> Update TOML to v0.1.1

.gitmodules, extensions.toml
In this PR, I introduce the work @mrnugget and I did to add Liquid syntax highlighting.
This extension is young, but it ensures that Liquid files are highlighted in Zed. This valuable for Shopify developers and others using Liquid.
Begins work on #331
=> Add Liquid syntax highlighting extension

.gitmodules
The Liquid extension submodule in #668 wasn't added correctly.
This PR fixes that.
=> Fix liquid submodule

.gitmodules, extensions.toml
I've moved the typst extension repo to GitHub, so it would be easier for people to report issues. This also adds passing the shell environment to the lsp, which might be unnecessary, but still is a good thing to do
=> Move typst extension to GitHub for contributor convenience

.gitmodules, extensions.toml
Adds the initial version of the `wit` extension (v0.1.0). This extension currently adds basic language support for WIT (Wasm Interface Type).
=> Add `wit` extension

extensions.toml
Added support for semicolons, for: https://github.com/weartist/zed-rainbow-csv/issues/2
=> Update rainbow-csv to v0.0.2

extensions.toml
This PR updates the Elixir extension to v0.0.4.
See https://github.com/zed-industries/zed/pull/11446 for the changes in this version.
=> Update Elixir to v0.0.4

extensions.toml
This PR updates the Zig extension to v0.1.2.
See https://github.com/zed-industries/zed/pull/11447 for the changes in this version.
=> Update Zig to v0.1.2

extensions.toml
This PR adds the Ruby extension.
Ruby support was extracted from Zed in https://github.com/zed-industries/zed/pull/11360.
=> Add Ruby extension

extensions.toml
This PR updates the Vue extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/11747 for the changes in this version.
=> Update Vue to v0.0.2

extensions.toml
the new version just changes first_line_pattern  to  `"^\\d*\\s?execve\\("` to detect strace files that starts with pid number (when strace is used with -f)
=> Update strace to 0.0.2

.gitmodules, extensions.toml
Adds language grammar support for [Cedar policy](https://cedarpolicy.com/) source code (`*.cedar`).
=> Add Cedar extension

.gitmodules, extensions.toml
This pull request adds a new extension for [Stimulus LSP](https://github.com/marcoroth/stimulus-lsp). Zed support was requested in https://github.com/marcoroth/stimulus-lsp/issues/268 and this PR closes [this issue](https://github.com/zed-industries/extensions/issues/709).
=> Add Stimulus LSP

extensions.toml
This PR updates the Ruby extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/11769 for the changes in this version.
=> Update Ruby to v0.0.2

extensions.toml
This PR updates the Gleam extension to v0.1.2.
See https://github.com/zed-industries/zed/pull/11803 for the changes in this version.
=> Update Gleam to v0.1.2

extensions.toml
This PR updates the PHP extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/11832 for the changes in this version.
=> Update PHP to v0.0.3

extensions.toml
This PR updates the Ruby extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/11833 for the changes in this version.
=> Update Ruby to v0.0.3

extensions.toml
This PR updates the Astro extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/11834 for the changes in this version.
=> Update Astro to v0.0.2

extensions.toml
This updates the Scala extension to 0.0.2: https://github.com/scalameta/metals-zed
=> Update Scala extension to 0.0.2

extensions.toml
This updates the Scala extension to include the fix for `tailwindcss-language-server` support: https://github.com/scalameta/metals-zed/pull/8
=> Update Scala to v0.0.3

.gitmodules, extensions.toml
Adds the initial version of [zed-groovy](https://github.com/valentinegb/zed-groovy). See [here](https://github.com/valentinegb/zed-groovy/releases/tag/v1.0.0) for release notes.
Closes #489 and closes #195.
=> Add Groovy v1.0.0

.gitmodules, extensions.toml
This adds the `serendipity` theme extension from [https://github.com/meocoder31099/Serendipity-Theme-Zed](https://github.com/meocoder31099/Serendipity-Theme-Zed)
=> Add `serendipity` extension

.gitmodules, extensions.toml
Tested under Manjaro Linux x86_64 Zed 0.135.2
For tree sitter used [uyha/tree-sitter-cmake](https://github.com/uyha/tree-sitter-cmake)\
I'm not proficient with tree-sitter grammar so I took it from [helix](https://github.com/helix-editor/helix/tree/master/runtime/queries/cmake). Used a little higher tree-sitter version though (v0.3.0 instead of pre-v0.2.0 commit)
For LSP used [Decodetalkers/neocmakelsp](https://github.com/Decodetalkers/neocmakelsp) (that's why extension called neocmake). Another option would be [regen100/cmake-language-server](https://github.com/regen100/cmake-language-server), but it's written in python and says "Alpha Stage, work in progress." in the README.md
=> Add neocmake extension

extensions.toml
Sorry for releasing another version so soon after v1.0.0. 😅
---
Release notes:
https://github.com/valentinegb/zed-groovy/releases/tag/v1.1.0
=> Update groovy to 1.1.0

extensions.toml
This PR updates the Gleam extension to v0.1.3.
See https://github.com/zed-industries/zed/pull/12000 for the changes in this version.
=> Update Gleam to v0.1.3

extensions.toml
Hi, this PR bumps the Ruby extension version to 0.0.4. Thanks.
See https://github.com/zed-industries/zed/pull/12101
=> ruby: Bump to 0.0.4

.gitmodules, extensions.toml
This pull request adds a port of Visual Studio Code's [Dark Modern](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_modern.json) theme to Zed.
- https://github.com/kcamcam/vscode_dark_modern.zed
=> Add vscode-dark-modern theme

.gitmodules, extensions.toml
This PR brings the [CodeSandbox theme from VSCode](https://marketplace.visualstudio.com/items?itemName=CodeSandbox-io.codesandbox-projects-theme) over to Zed, done using Zed's tool to convert VSCode themes. Works great from my testing. It has been requested [here](https://github.com/zed-industries/extensions/issues/544).
I have no affiliation with CodeSandbox in any way, hence the mentions of this theme being unofficial. 
I request this theme to be merged into the extensions repo and made available through the extensions store by the maintainers. Any feedback highly appreciated!
=> Add CodeSandbox Theme

extensions.toml
Includes: https://github.com/zed-industries/zed/pull/12237
=> php/ruby: Bump versions to 0.0.5

extensions.toml
This PR updates the Ruby extension to v0.0.6.
See https://github.com/zed-industries/zed/pull/12395 for the changes in this version.
=> Update Ruby to v0.0.6

extensions.toml
- add new theme variant Midnight Minimal
- add new no italic theme variant
- Increase contrast
- Add color support for indent guides (Zed v0.138.0-pre and above)
=> Update serendipity to v0.0.4

.gitmodules, extensions.toml
This is a start to F# support in Zed. I have copied the `.scm` files from [here](https://github.com/ionide/tree-sitter-fsharp) and have fsautocomplete working.
Automatic installation doesn't seem to be possible as the extension api does not support installing through dotnet tools, but maybe I can implement this manually? I wasn't sure if this was an accepted way of doing it.
I've come across one issue which seems to break fsautocomplete because there is a hidden character (FEFF) - which you can manually delete and fsautocomplete works as usual. Unsure if this is a me issue or a Zed issue.
Happy to take suggestions, as I'm pretty new to all this.
Would close #141 if accepted
=> Add F# extension

.gitmodules, extensions.toml
Still need some help with troubleshooting, it seems to work at first.
Dev extension works. Vale errors and warnings are shown.
Quickly after, the language server shuts down.
Any pointers on how to troubleshoot it further?
```bash
> tail -f ~/Library/Logs/Zed/Zed.log
2024-05-06T14:44:50+02:00 [INFO] compiling rust extension /Users/jan/git/github.com/koozz/zed-vale
2024-05-06T14:44:51+02:00 [INFO] finished compiling extension /Users/jan/git/github.com/koozz/zed-vale
2024-05-06T14:44:52+02:00 [INFO] rebuilt extension index in 20.117417ms
2024-05-06T14:44:52+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-05-06T14:44:52+02:00 [INFO] Initializing default prettier with plugins {}
2024-05-06T14:44:52+02:00 [INFO] starting language servers for Markdown: …
```
=> Add Vale extension for style and spellchecking

.gitmodules, extensions.toml
📺 This PR adds the Green Monochrome Monitor CRT Phosphor theme for Zed.
=> Add Green Monochrome Monitor CRT Phosphor theme

extensions.toml
- Fixed Rust `type.interface` incorrect coloring
- Add Serendipity-style coloring for Cursor and Selection
-  Some minor syntax highlighting changes to make it similar to the Serendipity VSCode theme
=> serendipity: Bump to v0.0.5

src/package-extensions.js
This PR improves the way extensions are retrieved from the blob store to ensure that we're accounting for when they all don't fit in a single page of results.
I had noticed some issues where were starting to drop some extensions towards the end of the list when diffing to determine which extensions need to be published.
=> Paginate results from the blob store

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.3
=> Update r to 0.0.3

src/package-extensions.js
This PR upgrades the warning about using `extension.json` to an error.
`extension.toml` must be used instead.
=> Enforce `extension.toml`

extensions.toml
This PR updates the poimandres extension to v0.0.2.
Changes:
- https://github.com/mshaugh/poimandres.zed/pull/2
=> Update poimandres to v0.0.2

extensions.toml
This PR updates the Vue extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/12656 for the changes in this version.
=> Update Vue to v0.0.3

extensions.toml
Changelog: https://github.com/lv37/zed-v/compare/v0.1.0...v0.2.0
=> Update V to v0.2.0

extensions.toml
Small update that introduces PR [zed_neocmake#1](https://github.com/k0tran/zed_neocmake/pull/1)
=> Update neocmake to v0.0.2

justfile, package.json, src/lib/extensions-toml.js, src/package-extensions.js, src/sort-extensions.js
This PR adds a script for sorting `extensions.toml` and `.gitmodules`.
This was already done as part of the `package-extensions` script, but this standalone script will make it easier to run when you just care about the sorting.
It can be run with either `pnpm sort-extensions` or `just sort-extensions`.
=> Add a script for sorting `extensions.toml` and `.gitmodules`

AUTHORING_EXTENSIONS.md
This PR documents how to sort `extensions.toml` and `.gitmodules` to ensure they pass CI.
Resolves #919.
=> Document sorting `extensions.toml` and `.gitmodules`

.gitmodules, extensions.toml
📺 This PR adds the Amber Monochrome Monitor CRT Phosphor theme for Zed.
The "Amber Monochrome Monitor CRT Phosphor" theme brings the nostalgic essence of vintage amber phosphor monitors to your Zed editor. This theme is crafted to offer a unique and immersive visual experience, capturing the original charm of early computing displays. Available in both dark and light versions, the Amber Monochrome Monitor CRT Phosphor Theme transforms your coding environment with its distinct amber-on-black and amber-on-light-amber aesthetics.
The theme includes eight distinct variants, each designed to emulate specific types of CRT phosphors:
The "Amber Monochrome Monitor CRT Phosphor" is designed to evoke the look and feel of classic CRT monitors, emphasizing simplicity and readability. The dark …
=> Add Amber Monochrome Monitor CRT Phosphor theme

.gitmodules, extensions.toml
📺 This PR adds the ChatGPT theme for Zed.
The "ChatGPT" theme brings the clean and modern aesthetic of the ChatGPT interface to your Zed editor. Inspired by the sleek design and intuitive color scheme of ChatGPT, this theme offers a refreshing and visually appealing coding experience. Available in a dark version, the theme transforms your coding environment with its elegant and readable color palette.
The "ChatGPT" theme is designed to enhance readability and reduce eye strain during long coding sessions. The dark version features a predominantly black background with subtle highlights and accent colors, maintaining a consistent and professional look.
-   **Accent Colours**: Various shades of green and blue for borders, highlights, and syntax elements.
-   **Syntax Highlighting**: …
=> Add ChatGPT theme

extensions.toml
This pull request updates the VS Code Dark Modern Them from `v0.0.1` to `v0.0.2`.
The new release simply fixes typo in the `extension.toml` file. Thanks for [pointing that out](https://github.com/kcamcam/vscode_dark_modern.zed/commit/4d2d1bd3a60d7fd2251dda0606022978c673c7c9) Moshyfawn.
The repository link was broken, https://github.com/kcamcma/vscode_dark_modern.zed (kcamcma), when it should have been https://github.com/kcamcam/vscode_dark_modern.zed (kcamcam).
=> Update VS Code Dark Modern theme to 0.0.2

.gitmodules, extensions.toml
Adds a theme based on the default GNOME apps but with more exciting syntax highlighting.
This theme differs from Zedwaita in that it provides better contrast for some frequently-used UI elements and takes a bolder approach to colors.
=> Add Adwaita Pastel Theme

.github/workflows/ci.yml, src/package-extensions.js
This PR updates CI to show warnings surfaced by the Zed extension CLI.
This PR also bumps the extension CLI version to https://github.com/zed-industries/zed/commit/2e87e1d26e86d0ce6f3d94b5d72782636330d24f.
This version includes the warnings about the deprecated theme key: https://github.com/zed-industries/zed/pull/13081
=> Log errors surfaced by the Zed extension CLI

.gitmodules, extensions.toml, package.json
Adds support for the Luau programming language.
Resolves https://github.com/zed-industries/extensions/issues/171.
Note: Diagnostics won't work in release builds until https://github.com/zed-industries/zed/pull/13102 is there. It will work if you temporarily build from main instead, as the PR is merged.
=> Add Luau extension

extensions.toml
updating cairo extension to version 0.0.2 which includes the official tree-sitter grammar from starkware
=> Update Cairo to v0.0.2

extensions.toml
Bumps grammar commit to fix a couple syntax highlighting issues.
=> Update Luau to v0.1.2

extensions.toml
We have pushed a new release of this extension here: https://github.com/StyraInc/zed-rego/releases/tag/v0.0.2
=> Update Rego extension to v0.0.2

.gitmodules, extensions.toml
[BQN](https://mlochbaum.github.io/BQN/), while relatively niche, is an amazing language, and Zed deserves support for it.
I've implemented all the features Zed has currently. The [readme](https://github.com/DavidZwitser/zed-bqn/blob/main/README.md) describes the decisions.
=> Add extension for the BQN language

extensions.toml
Update graphql extension to v0.0.3
- Add `graphqls` file extension for schema files
=> Update GraphQL extension to v0.0.3

extensions.toml
This PR updates the Zig extension to v0.1.3.
=> Update Zig to v0.1.3

src/lib/validation.js, src/lib/validation.test.js
This PR adds additional validation for extension IDs to ensure they only contain valid characters.
Extension IDs must only consist of lowercase letters, numbers, and hyphens (`-`).
=> Validate extension IDs

extensions.toml
This PR updates the Prisma extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/13739 for the changes in this version.
=> Update Prisma to v0.0.3

extensions.toml
Updates `tokyo-night` to v0.1.2 - fixes contrast issues.
=> Update Tokyo Night to v0.1.1

extensions.toml
This PR updates the OCaml extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/13864 for the changes in this version.
=> Update OCaml to v0.0.2

extensions.toml
This PR updates the Lua extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/13882 for the changes in this version.
=> Update Lua to v0.0.3

extensions.toml
This PR updates the Beancount extension to v0.0.3.
Changes:
- https://github.com/zed-extensions/beancount/pull/1
=> Update Beancount to v0.0.3

extensions.toml
This PR updates the Clojure extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/13935 for the changes in this version.
=> Update Clojure to v0.0.3

.gitmodules, extensions.toml
Adds support for [Slim templates](https://github.com/slim-template/slim) (#140).
This is based on https://github.com/kolen/tree-sitter-slim, ~but currently uses my fork as some PRs are still open upstream that will (hopefully) be merged soon~.
=> Add Slim template language support

extensions.toml
This PR updates the Fortran extension to 0.0.2.
Changes: https://github.com/Xavier-Maruff/zed-fortran/pull/1
=> Bump Fortran to v0.0.2

extensions.toml
This pull request updates the VSCode Dark Modern Theme from `v0.0.2` to `v0.0.3`.
Changes: 
- https://github.com/kcamcam/vscode_dark_modern.zed/pull/1 by @nikeee
Active line background
Highlighted line background
Active line background
Highlighted line background
=> Update VSCode Dark Modern theme to v0.0.3

extensions.toml
This PR updates the PHP extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/14607 for the changes in this version.
Of note, this version of the PHP extension now supports [Phpactor](https://github.com/phpactor/phpactor) as a language server.
=> php: Bump to v0.1.0

extensions.toml
This PR updates the PHP extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/14647 for the changes in this version.
=> php: Bump to v0.1.1

extensions.toml
This PR updates the Svelte extension to v0.0.3.
See https://github.com/zed-industries/zed/pull/14650 for the changes in this version.
=> svelte: Bump to v0.0.3

extensions.toml
This PR updates the Zig extension to v0.1.4.
See https://github.com/zed-industries/zed/pull/14651 for the changes in this version.
=> zig: Bump to v0.1.4

extensions.toml
This PR updates the Elixir extension to v0.0.6.
See https://github.com/zed-industries/zed/pull/14657 for the changes in this version.
=> elixir: Bump to v0.0.6

extensions.toml
This pull request updates the Ruby extension to v0.0.8.
Please see https://github.com/zed-industries/zed/pull/14707 for the changes in this version.
=> ruby: Bump to v0.0.8

extensions.toml
This PR updates the Vue extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/14748 for the changes in this version.
=> vue: Bump to v0.1.0

extensions.toml
This PR updates the PHP extension to v0.1.2.
See https://github.com/zed-industries/zed/pull/14808 for the changes in this version.
=> php: Bump to v0.1.2

.gitmodules, extensions.toml
Port of chriskempson's [Tomorrow Theme](<https://github.com/chriskempson/tomorrow-theme?tab=readme-ov-file>)  as well as some specific alternate versions: (VSCode's [_Tomorrow Night Blue_](<https://arc.net/l/quote/nbuipqzx>), [mdBook](<https://rust-lang.github.io/mdBook/for_developers/preprocessors.html>)'s _Coal_, and [_rusty.nvim_](<https://github.com/namrabtw/rusty.nvim?tab=readme-ov-file>)).
Comes with the variants specified in the Tomorrow Theme repo as well as 2 minimal variants for less highlights.
<table>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/tomorrow-theme-zed/raw/main/assets/tomorrow-night.png" width="500"></td>
<td><img src="https://github.com/bIaqat/tomorrow-theme-zed/raw/main/assets/tomorrow.png" width="250"></td>
</tr>
<tr>
<td><img …
=> Add Tomorrow Theme

extensions.toml
This PR updates the Astro extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/15172 for the changes in this version.
=> astro: Update to v0.1.0

extensions.toml
This PR updates the Deno extension to v0.0.2.
See https://github.com/zed-industries/zed/pull/15173 for the changes in this version.
=> deno: Update to v0.0.2

extensions.toml
This PR updates the Terraform extension to v0.0.4.
See https://github.com/zed-industries/zed/pull/15174 for the changes in this version.
=> terraform: Update to v0.0.4

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/5e44f5fa448f4405af38993794cf5736b822e265.
=> Bump extension CLI version to `5e44f5f`

extensions.toml
This PR updates the Zig extension to v0.1.5.
See https://github.com/zed-industries/zed/pull/15203 for the changes in this version.
=> zig: Bump to v0.1.5

extensions.toml
This PR updates the Kotlin extension to v0.1.0.
See https://github.com/zed-extensions/kotlin/pull/18 for the changes in this version.
=> kotlin: Bump to v0.1.0

extensions.toml
Release notes:
https://github.com/MordFustang21/zed-github-dark/releases/tag/v1.0.5
=> Update github-dark-default to v1.0.5

.gitmodules, extensions.toml
Adds LSP and syntax highlighting support for [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) (.blp) files.
=> Add Blueprint extension

.gitmodules, extensions.toml
This adds [`zed-curry`](https://github.com/fwcd/zed-curry), an extension providing language support for the [Curry programming language](https://en.wikipedia.org/wiki/Curry_(programming_language)).
=> Add Curry extension

extensions.toml
This adds improvements in syntax handling for newer D editions, and improved highlighting for embedded escape sequences.
=> Bump D extension to v0.0.7

extensions.toml
Fix missing `element.background` in Melange Dark.
=> Update Melange theme to v0.0.2

.gitmodules, extensions.toml
=> Add basedpyright extension

extensions.toml
workaround for https://github.com/zed-industries/zed/issues/15383
=> Bump catppuccin to v0.2.10

.gitmodules, extensions.toml
This adds [`zed-rst`](https://github.com/elmarco/zed-rst), an extension providing language support for the [reStructuredText markup syntax](https://docutils.sourceforge.io/rst.html).
#1168
=> Add rst extension

extensions.toml
Release notes:
https://github.com/MordFustang21/zed-github-dark/releases/tag/v1.0.6
=> Update github-dark-default to v1.0.6

.gitmodules, extensions.toml
@billgo simply copied the [zedokai](https://github.com/slymax/zedokai) extension and changed the name without permission or attribution.
Except for name and author, the extension is identical to zedokai.
=> Revert "Add Monokai Theme"

.gitmodules, extensions.toml
Add [notpeter/playdate-zed-extension](https://github.com/notpeter/playdate-zed-extension).
Includes syntax highlighting for Panic PlaydateSDK custom formats:
- [tree-sitter-pdxinfo](https://github.com/notpeter/tree-sitter-pdxinfo)
- [tree-sitter-animationtxt](https://github.com/notpeter/tree-sitter-animationtxt)
=> Add playdate extension

extensions.toml
This PR updates the Elixir extension to v0.0.7.
See https://github.com/zed-industries/zed/pull/15867 for the changes in this version.
=> elixir: Bump to v0.0.7

extensions.toml
This PR reverts the v0.1.4 version bump of the Gleam extension from #1215, as it isn't ready to be released.
=> gleam: Revert v0.1.4 bump

.gitmodules, extensions.toml
I wrote a LSP implementation, powered by `libcst`, to support basic refactoring support - [`cst-lsp`](https://github.com/rowillia/cst-lsp)
Currently it just supports "Extract Method" but adds the framework needed to support more refactoring easily. 
https://github.com/user-attachments/assets/53edc63a-8aa3-425e-bd9e-4e05ba17042e
=> Add Python Refactoring extension

extensions.toml
Updating my meson extension from `0.1.0` to `0.1.1`, fixing the LSP not being executable.
=> Update meson extension to v0.1.1

.gitmodules, extensions.toml
`perm` files are used by [Permify](https://github.com/Permify/permify) to define authorization schemas within their DSL. This extension provides basic highlighting support for some keywords.
=> Add perm extension for perm file support

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/423c7b999a07d5f5ab82c58ac99f6b0684be50d0.
=> Bump extension CLI version to `423c7b9`

extensions.toml
This pull request updates the Ruby extension to v0.1.0.
Please see https://github.com/zed-industries/zed/pull/15855 for the changes in this version.
=> ruby: Bump to v0.1.0

.gitmodules, extensions.toml
Add highlighting support for Go Checksum files. Addresses [this](https://github.com/zed-industries/zed/pull/7139#issuecomment-1919761603).
=> Add gosum extension

.gitmodules, extensions.toml
This adds the https://github.com/rcl-lang/zed-rcl extension, which contains a grammar for https://rcl-lang.org/.
(I am the author of both.)
=> Add RCL configuration language extension

.gitmodules, extensions.toml
This commit add a PowerShell extension by support 2 features, the grammar and the language server. But at this moment, the language server still needs to configure the PowerShellEditorServices directory though the `lsp` configuration.
The grammar, I use https://github.com/airbus-cert/tree-sitter-powershell. And the language server uses https://github.com/PowerShell/PowerShellEditorServices.
Closes #496
=> Add PowerShell extension

extensions.toml
This PR updates the Haskell extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/16228 for the changes in this version.
=> haskell: Bump to v0.1.1

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/18aff55f342448401a4dd40747f106a639b73e25.
=> Bump extension CLI version to `18aff55`

extensions.toml
This PR updates the Gleam extension to v0.2.0.
See https://github.com/zed-industries/zed/pull/16258 for the changes in this version.
=> gleam: Bump to v0.2.0

extensions.toml
This PR updates the Zig extension to v0.2.0.
See https://github.com/zed-industries/zed/pull/16261 for the changes in this version.
=> zig: Bump to v0.2.0

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/6b7664ef4a87d006425a8ce260b00c8e8befaf54.
=> Bump extension CLI version to `6b7664e`

extensions.toml
Fix Inline Assist background colors
- Add `deleted.background` to dark and light variants
- Modify `info.background` in dark and light variants
- Lighten `surface.background` in light variant
=> Update Melange theme to v0.0.3

extensions.toml
Release notes:
https://github.com/janezpodhostnik/cadence.zed/releases/tag/v0.0.2
=> Update Cadence to v0.0.2

extensions.toml
This PR updates the Elixir extension to v0.0.8.
See https://github.com/zed-industries/zed/pull/16495 for the changes in this version.
=> elixir: Bump to v0.0.8

extensions.toml
- Fix lsp path for linux
- Add aarch64 support for MacOS
=> Update neocmake extension to v0.0.5

extensions.toml
Release notes:
https://github.com/FyraLabs/zed-vala/releases/tag/v0.2.0
=> Update vala to v0.2.0

.gitmodules, extensions.toml
This pull request adds the Malibu theme as a submodule to the Zed repository. 
The theme is located in the `extensions/malibu-theme` directory and is registered in the `extensions.toml` file with version 0.0.1.
=> Add Malibu Theme

.gitmodules, extensions.toml
👋🏽 Hi all!
Here is my attempt at integrating Ansible Language Server for Zed. Please refer to [this](https://github.com/kartikvashistha/zed-ansible/blob/main/README.md) for the current observations and challenges with this implemenation, and as such wouldn't mind some support to further improve it :) 
If you are an Ansible user, please give this extension a try and let me know of your thoughts! I am really excited to listen to any and all feedback! 
Thanks!
Issue: https://github.com/zed-industries/extensions/issues/151
=> Add Ansible extension

.gitmodules, extensions.toml
Does not currently support the LSP, because AFAICT Zed only supports LSPs hosted on Github
=> Add Fennel extension

extensions.toml
This PR updates the Kotlin extension to v0.1.1.
See https://github.com/zed-extensions/kotlin/pull/21 for the changes in this version.
=> kotlin: Bump to v0.1.1

extensions.toml
This PR updates the Swift extension to v0.3.1.
See https://github.com/zed-extensions/swift/pull/16 for the changes in this version.
=> swift: Bump to v0.3.1

.gitmodules, extensions.toml
adds the [gruvbox-ish](https://github.com/LeoDog896/zed-gruvbox-ish) theme ([original](https://github.com/graceful-potato/gruvbox-ish)).
**Note**: I have not explicitly licensed the previous repository. I've contacted the author of `gruvbox-ish` by email, where they said "Of course you can port/modify or do whatever you want with it." If there's some extra requirement for licensing, I can ask for explicit licensing 👍
=> Add Gruvbox-ish

extensions.toml
This PR updates the Elixir extension to v0.0.9.
See https://github.com/zed-industries/zed/pull/16879 for the changes in this version.
=> elixir: Bump to v0.0.9

.gitmodules, extensions.toml
Closes https://github.com/zed-industries/extensions/issues/499
GitHub repository: https://github.com/xhyrom/zed-discord-presence
It's done by LSP right now but once Zed gets normal extension support i'll rewrite it :+1:
=> Add Discord presence extension

.gitmodules, extensions.toml
This PR adds an extension for using Zed with [Code::Stats](https://codestats.net/).
=> Add Code::Stats extension

extensions.toml
This PR updates the Code::Stats extension to v0.2.0.
=> code-stats: Bump to v0.2.0

extensions.toml
This PR updates the Code::Stats extension to v0.2.1.
=> code-stats: Bump to v0.2.1

extensions.toml
Update Scala extension to the newest available version. Includes:
* https://github.com/scalameta/metals-zed/pull/15
* https://github.com/scalameta/metals-zed/pull/18
* https://github.com/scalameta/metals-zed/pull/19
* https://github.com/scalameta/metals-zed/pull/20
=> Update Scala to v0.0.4

.gitmodules, extensions.toml
[Sourcepawn](https://github.com/alliedmodders/sourcepawn) is a fork of a language called "Pawn", formerly known as "Small", which is a C-like language generally used for scripting. Sourcepawn was mainly made for [Sourcemod](https://www.sourcemod.net/), which is a modding framework for the Source engine.
Throughout the years, Sourcepawn has completely diverged from Pawn, both syntax-wise and back-end wise, becoming completely different from Pawn, so before anyone says "can't the support be added to Pawn then?", no, it can't.
The extension works fine. It correctly highlights code & the LSP functions correctly. Unfortunately Zed's themes are extremely barebones due to their small number of captures, so some specific highlights do not work. But this is not a big problem.
=> Add Sourcepawn language extension

extensions.toml
This PR updates the Code::Stats extension to v0.2.2.
=> code-stats: Bump to v0.2.2

extensions.toml
- Changed colors of hint popups to be less bright
- Also changed Sublime Mariana's hints to match the colors in sublime (thanks @unixtensor)
- Added indent colors for rainbow and normal indent guidelines
- Fixed minor contrast highlights (element.select and a few others)
<table>
<tr>
<td rowspan="2"><img src="https://github.com/user-attachments/assets/89ecc10b-9a04-48fb-9f94-5588ffac88da" width="500"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/facfa6d0-f033-4754-b714-f5353805bf37" width="500"></td>
</tr>
</table>
<table>
<tr>
<td rowspan="2"><img src="https://github.com/user-attachments/assets/dd6acd7b-73f4-4165-bd4e-b5f1efde04db" width="500"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/aa158849-73f2-4d0d-ab11-0931afd80eb2" …
=> Bump Mariana to v0.9.0

.gitignore
This PR adds the lock files for other Node package managers to the `.gitignore`, as we only want to use pnpm.
=> Ignore lock files for other package managers

extensions.toml
Please see https://github.com/zed-industries/zed/pull/17128 for list of changes. Thanks!
=> ruby: Bump version to v0.2.0

extensions.toml
Just [a maintenance release](https://github.com/vitallium/zed-stimulus/releases/tag/v0.0.2) to upgrade the `zed-extensions-api` crate to v0.1.0. Thanks!
=> stimulus: Bump version to v0.0.2

extensions.toml
Just [a maintenance release](https://github.com/vitallium/zed-marksman/releases/tag/v0.0.2) to upgrade the `zed-extensions-api` crate to v0.1.0. Thanks!
=> marksman: Bump version to v0.0.2

extensions.toml
support players for Itg flat Dark.
=> Update Hex themes to v0.0.3

extensions.toml
This PR updates the Svelte extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/17364 for the changes in this version.
=> svelte: Bump to v0.1.0

extensions.toml
This PR updates the Terraform extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/17365 for the changes in this version.
=> terraform: Bump to v0.1.0

extensions.toml
This PR updates the Svelte extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/17414 for the changes in this version.
=> svelte: Bump to v0.1.1

extensions.toml
Tree-sitter grammar had some false matches that I tried to improve before but didn't manage. Now I managed by adding a match for false character names with higher priority and making sure scene descriptions cannot be empty.
=> Update Fountain to v0.0.7

.gitmodules, extensions.toml
Monochrome theme based on github's light mode syntax highlighting
=> Add GitHub Monochrome theme extension

.gitmodules, extensions.toml
Theme, that imitates Sublime Text 4's Mariana theme.
The Mariana color scheme is known for its cool, muted tones that provide a soothing yet vibrant coding environment, making it easy on the eyes during long coding sessions. This theme avoids the use of _cursive or italic_ styles, ensuring a consistent and clean look across all text elements for enhanced readability and focus.
There are two distinct variations: `Sublime Mariana` and Sublime Breakers. Theme variation closely mirrors the original, offering a cool, muted color scheme that’s easy on the eyes.
> [!NOTE]  
> I’m aware that a [similar theme](https://github.com/biaqat/mariana-theme-zed/tree/f5a79b6a20628a155c339d19e43a31719e0c7636) already exists, but this version offers some key differences. Notably, it contains only two color …
=> Add Sublime Mariana theme

extensions.toml
New feature:
- Read LSP binary setting for `texlab`
Fix:
- Correct error in outlines
=> Update LaTeX to v0.0.6

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/ccf6f27b8f1bdfb803b9cc0da0b0cf5c9e136dd9.
=> Bump extension CLI version to `ccf6f27`

extensions.toml
This PR updates the PHP extension to v0.2.0.
See https://github.com/zed-industries/zed/pull/17674 for the changes in this version.
=> php: Bump to v0.2.0

extensions.toml
This PR updates the Erlang extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/17679 for the changes in this version.
=> erlang: Bump to v0.1.0

extensions.toml
- Adds syntax highlighting to `.svh` files.
=> Bump verilog to v0.0.4

extensions.toml
This PR updates the OCaml extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/17945 for the changes in this version.
=> ocaml: Bump to v0.1.0

extensions.toml
This PR updates the Ruff extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/17960 for the changes in this version.
=> ruff: Bump to v0.1.0

extensions.toml
Use `extension.toml` instead of `extension.json`.
=> neosolarized: Bump to v0.0.2

extensions.toml
- Improves highlighting
- Updates Zed extension API
- Adds some outline queries
- Changes default language server proxy to use `nc` instead of `netcat`
=> Update Unison extension to v0.0.4

extensions.toml
This PR updates the Lua extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/18246 for the changes in this version.
=> lua: Bump to v0.1.0

extensions.toml
Update kanagawa-themes to v0.1.1
Adds three new themes and a no italics version
=> Update kanagawa-themes to v0.1.1

extensions.toml
The version 0.0.2 of the typos extension adds support for the following languages:
- AsciiDoc
- Astro
- Bash
- Biome
- C#
- C++
- Deno
- Docker
- Emmet
- GLSL
- Groovy
- Luau
- Makefile
- PHP
- Prisma
- Proto
- Python
- R
- Rego
- ReStructuredText
- Scala
- Svelte
- TailwindCSS
- Terraform
- Uiua
- Vue
- Yarn
If there is a way to have a wildcard to enable the extension on all non-binary files instead of having to list them all please tell me.
=> Update typos extension to v0.0.2

extensions.toml
This PR adds the Proto extension.
Haskell support was extracted from Zed in https://github.com/zed-industries/zed/pull/18704.
=> Add Proto extension

.gitmodules, extensions.toml
NED and MSG (extensions .ned and .msg) are DSLs for the OMNeT++ network simulator. They are used by model frameworks for OMNeT++, such as the INET framework, Simu5G, Veins, etc. We are the team that develops [OMNeT++](https://github.com/omnetpp/omnetpp) and the [INET Framework](https://github.com/inet-framework/) and we have created tree-sitter grammars for these languages, as well as an extension for the Zed editor.
=> Add OMNeT++ extension

extensions.toml
This PR updates the Protobuf extension to v0.2.0.
See https://github.com/zed-industries/zed/pull/18814 for the changes in this version.
=> proto: Bump to v0.2.0

extensions.toml
This PR updates the PHP extension to v0.2.1.
See https://github.com/zed-industries/zed/pull/18815 for the changes in this version.
=> php: Bump to v0.2.1

.gitmodules, extensions.toml
Similar to Iceberg, but I find it's easier on the eyes. Screenshots available here: https://github.com/jmsdnns/zed-iceicebergy.
=> Add Ice Ice Bergy theme

extensions.toml
This PR updates the Terraform extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/18382 for the changes in this version.
=> terraform: Bump to v0.1.1

extensions.toml
- Added highlighting support for auto completions and symbol search
- Added runnable tags for the main three ways scala apps can be run
- Set `tab_size` to 2
=> Update Scala to v0.1.0

.gitmodules, extensions.toml
This PR updates the Gleam extension to v0.2.1.
The Gleam extension now resides at [`gleam-lang/zed-gleam`](https://github.com/gleam-lang/zed-gleam).
=> gleam: Bump to v0.2.1

.github/workflows/ci.yml
This PR changes the CI workflow behavior to not cancel any in-progress jobs on `main`.
This means that there will only be one concurrent job running for `main` at a given time, and it will run to completion.
This should allow us to merge multiple PRs concurrently without having to worry about them stomping on each other during the packaging/upload process.
=> ci: Don't cancel in-progress on `main`

.gitmodules, extensions.toml
This adds basic language support for [SageMath](https://www.sagemath.org/).
SageMath is *very* similar to Python: the language adds some Sage-specific syntactic sugar, changes some operators (e.g. ^ is exponentiation). The language is "compiled" down to python before execution. Nonetheless these changes prevent e.g. Python language servers from working correctly, therefore the need for a separate extension for ".sage" files.
Currently the extension works by using the Python grammar, but changes the highlights.scm to add Sage-specific keywords / builtins / constants.
=> Add SageMath language extension

extensions.toml
> [!WARNING]
> This release includes a breaking change for projects that use the `java_home` setting as that setting no longer exists. Please use the `settings.java.home` initialization option instead.
- Fix override method completion label [`4fe9b62`](https://github.com/zed-extensions/java/commit/4fe9b621cea2239071447b26ee2aa90a7dc3f93e)
- https://github.com/zed-extensions/java/pull/11
- Fix constant identifiers syntax highlighting [`e7b511f`](https://github.com/zed-extensions/java/pull/11/commits/e7b511fd2aa66e3da96865de25b00d4913c9db29)
- Fix doc comments syntax highlighting [`cfdedee`](https://github.com/zed-extensions/java/pull/11/commits/cfdedeea8a0df4cc656d51ad5efef2e4009cbe5a)
- https://github.com/zed-extensions/java/pull/12
- https://github.com/zed-extensions/java/pull/13
Full …
=> java: Bump to v2.0.0

extensions.toml
Fix for https://github.com/zed-industries/extensions/pull/1506 not bumping the version number in `extensions.toml` too.
We should probably add a CI test for this.
=> xml: Bunmp to v0.0.7 (fix)

extensions.toml
Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.2.0
=> Update macos-classic to v0.2.0

extensions.toml
Currently, it is observed that the YAML TS parser, when resued within the Ansible extension, is creating a memory leak when working with non-ansible YAML files. 
Since we aren't able to fully narrow down the issue on TS side just yet to rollout the appropriate fix, I'm disabling highlighting temporarily in order for at least the LSP be useful/accessible to the extension users. 
The issue can be tracked here: https://github.com/kartikvashistha/zed-ansible/issues/2
=> Update Ansible to v0.0.2

.gitmodules, extensions.toml
Adds a new syntax-highlighting extension for the [HAML](https://haml.info/) templating language, as requested in this thread: https://github.com/zed-industries/extensions/issues/179.
I put together a first version during the Zed meetup at RustConf in Montreal based on @vitallium's work in https://github.com/vitallium/tree-sitter-haml, but hadn't published it as I wasn't sure what their plans were for the grammar. However, in https://github.com/zed-industries/zed/pull/18787#issuecomment-2397885773 they agreed that this would be the right way forward.
=> Add HAML extension

.gitmodules
This PR adds an extension that provides support for Graphviz: <https://graphviz.org>
It introduces a basic syntax highligthing feature for `.dot` and `.gv` files.
https://github.com/gabeidx/zed-graphviz
=> Add Graphviz extension

extensions.toml
This PR adds the missing entries for the `d2` and `graphviz` extensions, since they were missed in these PRs:
- https://github.com/zed-industries/extensions/pull/1534
- https://github.com/zed-industries/extensions/pull/1536
=> Add missing `d2` and `graphviz` entries to `extensions.toml`

extensions.toml
- Fix LSP binary path on windows
Requested from https://github.com/BaptisteRoseau/zed-typos/issues/2
=> Update Typos extension to v0.0.3

.gitmodules, extensions.toml
This PR adds an extension that provides support for PlantUML: [plantuml.com](https://plantuml.com/)
It introduces a basic syntax highligthing feature for `.wsd`, `.pu`, `.puml`, `.plantuml` and `.iuml` files.
https://github.com/gabeidx/zed-plantuml
=> Add PlantUML extension

.gitmodules, extensions.toml
This PR adds an extension that provides support for Mermaid: [https://mermaid.js.org](https://mermaid.js.org)
It introduces a basic syntax highligthing feature for `.mermaid` and `.mmd` files.
https://github.com/gabeidx/zed-mermaid
=> Add Mermaid extension

extensions.toml
This PR updates the Svelte extension to v0.2.1.
See https://github.com/zed-industries/zed/pull/19420 for the changes in this version.
=> svelte: Bump to v0.2.1

extensions.toml
This PR updates the Vue extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/19421 for the changes in this version.
=> vue: Bump to v0.1.1

extensions.toml
This PR updates the Elixir extension to v0.1.1.
See https://github.com/zed-industries/zed/pull/19437 for the changes in this version.
=> elixir: Bump to v0.1.1

extensions.toml
This update includes LSP support utilizing qmlls. Thanks to @flukejones!
=> Update QML extension to 0.0.2

extensions.toml
Bumps the HAML extension from v0.0.3 to v0.0.4 (https://github.com/davidcornu/zed-haml/releases/tag/v0.0.4).
cc @vitallium
=> Update HAML extension

.gitmodules, extensions.toml
This PR updates the Svelte extension to v0.2.2.
The Svelte extension now resides at [`zed-extensions/svelte`](https://github.com/zed-extensions/svelte).
=> svelte: Bump to v0.2.2

.gitmodules, extensions.toml
Vue moved to a new repository. This is a no-op version bump which switches to that submodule.
=> vue: Bump to v0.1.2

extensions.toml
- Include task to mitigate current issue with build-on-save:
- Fix minor edge-case [bug](https://github.com/rzukic/zed-latex/pull/28) when attempting to download `texlab` (in a situation for which there is no Zed release anyway)
=> Update LaTeX extension to v0.0.8

extensions.toml
This update fixes qmlls path detection mentioned here: https://github.com/zed-industries/extensions/pull/1560#issuecomment-2426830539
It is now using worktree.which to get the full path to either qmlls or qmlls6 if it can be found in $PATH.
The error message when qmlls was not found is now clearer as well, including some docs on how to install it on various distros and MacOS.
=> Update QML extension to v0.0.3

extensions.toml
This PR updates the Dart extension to v0.1.2.
See https://github.com/zed-industries/zed/pull/19835 for the changes in this version.
=> dart: Bump to v0.1.2

.gitmodules, extensions.toml
Adds [SML](https://smlfamily.github.io/) support to Zed with [`tree-sitter-sml`](https://github.com/MatthewFluet/tree-sitter-sml) and [`millet`](https://github.com/azdavis/millet) language server. Closes https://github.com/zed-industries/extensions/issues/133.
https://github.com/omarjatoi/zed-sml
=> Add Standard ML extension

extensions.toml
Updates the name of a deprecated theme option.
=> Bump zedwaita to v0.0.5

extensions.toml
This version makes a few changes.
1. I've synchronized the tree-sitter queries with [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), including switching to [gmlarumbe/tree-sitter-systemverilog](https://github.com/gmlarumbe/tree-sitter-systemverilog) for the grammar as nvim did.
2. I'm now using a hard-coded tag for Verible instead of pulling the latest release.
- The Veridian language server is still built from upstream at release time in my repo, so static commits are already enforced for that.
3. I've bumped the extension api version to 0.1.0 from 0.0.6.
=> Bump verilog to v0.0.5

extensions.toml
This release enables back code highlighting for Ansible files to fix and close [this](https://github.com/kartikvashistha/zed-ansible/issues/2) issue.
Other misc changes include:
- Bump `zed_extension_api` from `0.0.6` to `0.1.0`
- Update project README
PR: https://github.com/kartikvashistha/zed-ansible/pull/5
=> Ansible: Update to v0.1.0 

extensions.toml
This version adds support for tagging ScalaTest tests to enable adding a task to run the tests through the run gutter.
=> Bump scala to v0.1.1

extensions.toml
**Jump to v0.1.0 to signify a noticeable change in experience.**
This release aims to provide a default out of the box experience building LaTeX documents without user configuration when a suitable previewer is detected. With a fresh Zed project with a LaTeX file, a suitable PDF previewer, and no custom LSP configuration in the Zed settings will now have build-on-save and forward-search after save set up automatically. However any setting explicitly set by the user takes priority. More details in the wiki to come shortly.
This extension now automatically may make changes to `texlab` settings, to disable this set "lsp.texlab.settings.texlab.forwardSearch" to an empty object `{}`.
=> Update LaTeX extension to v0.1.0

.gitmodules, extensions.toml
Hi, this is an extension which enforces a specific code style(called "Norme") for *.c/*.h files. It's intended to be used by 42 School students, and it uses a LSP server for [Norminette](https://github.com/42School/norminette), called [norminette_lsp](https://github.com/DavidLee18/norminette_lsp). It would be a lot helpful for students of 42 School if this extension gets on the registry. Thanks.
=> Add norminette extension

extensions.toml
Bumps the HAML extension from v0.0.4 to v0.0.5: https://github.com/davidcornu/zed-haml/releases/tag/v0.0.5
cc @vitallium
=> Update HAML extension to v0.0.5

extensions.toml
Bumps the HAML extension from v0.0.5 to v0.0.6: https://github.com/davidcornu/zed-haml/releases/tag/v0.0.6
cc @vitallium
=> Update HAML extension to v0.0.6

.gitmodules, extensions.toml
This extension adds basic syntax highlighting (and some folding) for hurl.dev files.
=> Add Hurl (hurl.dev) extension

extensions.toml
Version 0.0.7 of this extension allowed users to have `texlab` (LaTeX language server) without explicitly installing it themselves. Users taking advantage of this would then not be able to use `texlab` when launching Zed offline, even if this extension downloaded a `texlab` release previously.
This PR addresses this by adding a fallback for network issues which checks if it can find any versions of `texlab` that it previously downloaded.
Minor extra: duplicate code removed.
=> Update LaTeX extension to v0.1.1

extensions.toml
Release notes:
https://github.com/MordFustang21/zed-github-dark/releases/tag/v1.0.7
=> Update github-dark-default theme to v1.0.7

.gitmodules, extensions.toml
https://github.com/uncenter/zed-tera
Adds a language extension providing [Tera](https://keats.github.io/tera/docs/) syntax highlighting.
=> Add Tera language extension

.gitmodules, extensions.toml
Upstream repo is no longer available.
https://github.com/clseibold/zed-odin
Maintainer has been contacted.
CC: @clseibold
This can be reverted if the source becomes available again.
I've pushed my local clone here: https://github.com/notpeter/zed-odin
But have no intention of maintaining it.
=> Remove Odin Extension

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/b5ce8e7aa500d530389fef4cdd26f4790d013682.
=> Bump extension CLI version to `b5ce8e7`

extensions.toml
This PR updates the HTML extension to v0.1.4.
See https://github.com/zed-industries/zed/pull/20692 for the changes in this version.
=> html: Bump to v0.1.4

extensions.toml
- The color of Git-ignored files is now more distinct.
- Fixed the placeholder text color to match the theme.
- Cyan in the terminal now matches the cyan in the editor.
- `border.variant` now matches other borders.
- Enhanced the visibility of the disabled icon color.
=> Bump One Black Theme to v0.0.2

.gitmodules, extensions.toml
This PR updates the OCaml extension to v0.1.2.
The OCaml extension now resides at [`zed-extensions/ocaml`](https://github.com/zed-extensions/ocaml).
=> ocaml: Bump to v0.1.2

extensions.toml
This PR bumps the Code::Stats extension to v0.2.3.
=> code-stats: Bump to v0.2.3

extensions.toml
This release adds a new setting to add extra directories to TEXINPUTS when invoking `texlab` affecting some LSP functionality and LaTeX compilation. The user may want to consider [alternatives](https://github.com/rzukic/zed-latex/wiki/FAQ#can-i-add-extra-directories-to-be-picked-up-by-the-project) before using this setting.
Example:
```jsonc
{
"lsp": {
"texlab": {
"initialization_options": {
// experimental: visit zed-latex wiki on github to check if setting location has moved
"extra_tex_inputs": [
"/extra/path/1/",
"/extra/path/2/",
]
}
}
}
}
```
=> Update LaTeX extension to v0.1.2

extensions.toml
Changes: https://github.com/someone13574/zed-verilog-extension/releases/tag/v0.0.6
=> Bump verilog to v0.0.6

extensions.toml
Notably changes Tree-sitter repo to [4teapo/tree-sitter-luau](https://github.com/4teapo/tree-sitter-luau) for a bunch of syntax highlighting fixes and additions.
=> Bump Luau to v0.2.1

extensions.toml
Bumps the HAML extension from v0.0.6 to v0.0.7: https://github.com/davidcornu/zed-haml/releases/tag/v0.0.7
Upstream diff: https://github.com/vitallium/tree-sitter-haml/compare/f99259f8a2e6600f5cd5f87b42648db2519e6f73...5dedefd955eaaadec309357879a46edf932945cf
cc @vitallium
=> Update HAML extension to v0.0.7

.gitmodules, extensions.toml
This extension adds highlighting support for X12 EDI documents.
Please let me know if any changes are required on my end. Thank you all for your hard work building Zed.
=> Add EDI X12 language support

.gitmodules, extensions.toml
This extension adds support for Cooklang, [a recipe markup language](https://cooklang.org).
Preview:
=> Add Cooklang language support

extensions.toml
Changelog [here](https://github.com/nathanjcollins/zed-fsharp/releases/tag/0.0.4), but this just adds a couple of file extensions
=> Bump fsharp to 0.0.4

extensions.toml
Release notes:
https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.2.2
=> Update macos-classic to v0.2.2

extensions.toml
Hi, this is just a technical release of the `marksman` extension. See the release changelog here https://github.com/vitallium/zed-marksman/releases/tag/v0.0.3
Thanks!
=> Bump marksman to v0.0.3

extensions.toml
This pull request updates the **vscode-dark-modern** theme from `v0.0.4` to `v0.0.5`.
- Adds git deleted and info background by @zasdaym in https://github.com/kcamcam/vscode_dark_modern.zed/pull/16
=> Update vscode-dark-modern from `v0.0.4` to `v0.0.5`

extensions.toml
Hi!
This release brings version 0.0.4 of the `ltex` extension. The most notable change is the switch from the original [`ltex`](https://github.com/valentjn/ltex-ls) repository, which seems to be unmaintained, to a maintained fork named [`ltex-plus`](https://github.com/ltex-plus/ltex-ls-plus). See [the release page](https://github.com/vitallium/zed-ltex/releases/tag/v0.0.4) for more information (which contains everything I've written here. :-)).
**Full Changelog:** [https://github.com/vitallium/zed-ltex/compare/v0.0.3...v0.0.4](https://github.com/vitallium/zed-ltex/compare/v0.0.3...v0.0.4)
=> Bump `ltex` to v0.0.4

extensions.toml
Fixed sidebar items being the wrong colour in newest zed update.
=> Update modest-dark to v0.1.4

.gitmodules, extensions.toml
[This extension](https://github.com/Frixuu/Zed-Haxe) provides syntax highlighting [\(MIT-licensed\)](https://github.com/vantreeseba/tree-sitter-haxe/blob/12e814cd9b0656b0eaa3e04b0036b3b6625cc0d7/LICENSE.md) and LSP support [\(MIT-licensed\)](https://github.com/vshaxe/haxe-language-server/blob/900c0570372f8f592724b25ac52ababe1ef5717b/LICENSE.md) for the [Haxe](https://haxe.org/) programming language.
Closes #142.
Preview:
=> Add Haxe language extension

extensions.toml
This PR fixes the version for the `libsql-context-server` extension, since it wasn't correct in #1738.
=> libsql-context-server: Fix version

extensions.toml
Bump `ruby` to v0.2.3
Please see the corresponding bump in the `ruby` extension repo https://github.com/zed-extensions/ruby/pull/15
- Update `config.toml` to include additional Ruby-related files (https://github.com/zed-extensions/ruby/pull/5)
- Upgrade `zed_extension_api` to `v0.2.0` (https://github.com/zed-extensions/ruby/pull/12)
- Add label details to `ruby-lsp` completions (https://github.com/zed-extensions/ruby/pull/13)
=> Bump `ruby` to v0.2.3

.gitmodules, extensions.toml
This adds support for [Cython](https://cython.org/) syntax highlighting via https://github.com/lgeiger/zed-cython
Closes https://github.com/zed-industries/zed/discussions/14407
=> Add Cython extension

.gitmodules, extensions.toml
This PR implements an extension for the VHDL language using
* https://github.com/alemuller/tree-sitter-vhdl for the tree-sitter grammar
* https://github.com/VHDL-LS/rust_hdl as the language server
* the zed csharp extension as a reference
This is a reopening of my previous PR #729. The extension should now be fully functioning after the merge of https://github.com/zed-industries/zed/pull/13958
=> Add VHDL extension

extensions.toml
- rename from "Catppuccin **Themes**" to just "Catppuccin"
- update maintainer email
- use `v0.2.0` theme schema
=> Bump catppuccin to 0.2.17

extensions.toml
Release notes:
https://github.com/jenslys/zed-catppuccin-blur/releases/tag/v0.0.6
=> Update catppuccin-blur to v0.0.6

extensions.toml
- tweak active/inactive tab coloring
- use theme key: `accents` properly for `indent_aware` colors
=> Bump catppuccin to 0.2.18

extensions.toml
Release notes:
https://github.com/taciturnaxolotl/catppuccin-blur-zed/releases/tag/v0.1.1
=> Update catppuccin-blur-plus to v0.1.1

extensions.toml
This updates the SageMath extension to:
- Use the SageMath tree sitter grammar instead of python.
- Fix a few other syntax highlighting bugs
- Fix the Github repo link.
=> Update SageMath to v0.1.0

extensions.toml
Quick PR to bump the Yara extension to `0.0.2` which has better highlighting. The next update won't be such a fast-follow. 😅
=> Bump Yara to v0.0.2

extensions.toml
- Adds support for `.pxi`
- Bump tree-sitter-cython ([diff](https://github.com/b0o/tree-sitter-cython/compare/0fe384913becb968bcaaf02c5d33d3a1ff8bd615...5f5468af68899b1013eef19ffe154e3f9c7a5d4a))
=> Update cython to v0.1.1

extensions.toml
- Fix accidental extension id copy pasta (sorry elisp!)
cc: @JosephTLyons
=> Update Brainfuck to v0.0.4

.gitmodules, extensions.toml
This PR adds the `nstlgy-dark` extension to the Zed extensions repository. The submodule has been added under `extensions/nstlgy-dark` and the `extensions.toml` file has been updated accordingly.
=> Add nstlgy-dark extension

.gitmodules
Fix for warning on initial submodule setup:
```
Cloning into '/private/tmp/extensions/extensions/struct-theme'...
warning: redirecting to https://gitlab.com/Fake.User/struct-zed-theme.git/
```
=> Fix git url of extensions/struct-theme

extensions.toml
Bump the Ruby extension to v0.3.3.
See the changelog here https://github.com/zed-extensions/ruby/pull/23
Thanks!
=> ruby: Bump to version v0.3.3

extensions.toml
This PR fixes a typo I made with the repository URL for the Yara extension. 
Previously, it was `https://github.com/egibs/yara-zed` when it should have been `https://github.com/egibs/yara.zed`.
=> Update Yara submodule to pick up URL fix

extensions.toml
Changelog: https://github.com/zed-extensions/java/releases/tag/v4.0.0
=> Bump java to v4.0.0

.gitmodules, extensions.toml
This PR adds initial tree-sitter support for COBOL
- Closes: #132
- See also: #585
=> Add COBOL extension

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v5.0.0
=> Bump Java extension to v5.0.0

.gitmodules, extensions.toml
This PR adds the **chai-theme** to the Zed extensions repository. The chai-theme offers a warm, aesthetically pleasing color palette optimized for coding comfort and focus.
- Added chai-theme as a Git submodule in `extensions/chai-theme`
- Updated `extensions.toml` with version `0.0.1`
- Theme ID: `chai-theme`
- Initial release version: `0.0.1`
=> Add chai-theme v0.0.1

.gitmodules, extensions.toml
Hello.
This PR adds a new extension with Modus Themes. Highly accessible themes for [Zed](https://zed.dev), conforming with the highest standard for color contrast between background and foreground values ([WCAG AAA](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html)). This is a Zed port of the original [Modus Themes](https://protesilaos.com/emacs/modus-themes) built for [GNU Emacs](https://www.gnu.org/software/emacs/).
You can find all screenshots in the repo [here](https://github.com/vitallium/zed-modus-themes?tab=readme-ov-file#screenshots).
Thanks!
=> Add Modus Themes v0.0.1

extensions.toml
Updates Unison to latest tree-sitter grammar and includes some minor highlighting fixes a long the way as well.
=> Update Unison to v0.0.5

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v5.0.1
=> Bump Java to v5.0.1

.gitmodules, extensions.toml
I created a language extension for Zed to support QuakeC. It is based on the the tree-sitter parser by [vkazanov](https://github.com/vkazanov/tree-sitter-quakec).
=> Add quakec language extension

extensions.toml
Hi, this PR bumps the LTeX extension to v0.0.5 to pull the following 2 changes:
- Added option to override the binary path via local settings.
- Prefer using the cached binary in all use cases.
See the release here https://github.com/vitallium/zed-ltex/releases/tag/v0.0.5
Thanks!
=> Bump LTeX extension to v0.0.5

extensions.toml
There was a bug in `v0.0.2` where the downloaded LSP server binary was not marked as executable. This update fixes this issue.
=> Update COBOL to v0.0.3

extensions.toml
This PR updates the C# extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/22617 for the changes in this version.
=> csharp: Bump to v0.1.0

.gitmodules, extensions.toml
This adds support for [psalm](https://psalm.dev/) lsp, a static analysis tool for PHP.
=> Add Psalm extension

.gitmodules, extensions.toml
This PR bumps the Astro extension to v0.1.3.
The Astro extension now resides at [`zed-extensions/astro`](https://github.com/zed-extensions/astro).
=> astro: Bump to v0.1.3

.gitmodules, extensions.toml
This PR bumps the Clojure extension to v0.1.0.
The Clojure extension now resides at [zed-extensions/clojure](https://github.com/zed-extensions/clojure).
=> clojure: Bump to v0.1.0

.gitmodules, extensions.toml
This PR bumps the Racket extension to v0.0.3.
The Racket extension now resides at [zed-extensions/racket](https://github.com/zed-extensions/racket).
=> racket: Bump to v0.0.3

extensions.toml
Release notes:
https://github.com/jkasky/zed-cue/releases/tag/v0.0.4
=> Update cue to v0.0.4

extensions.toml
Hi. This PR update the `modus-themes` to v0.0.3.
Here is the list of changes between v0.0.1 (current) and the target version (v0.0.3):
- Changed Muted text colors (v0.0.3)
- Tweak info and hint colors (v0.0.3)
- Fixed diagnostic popover colors (v0.0.2)
- Added colors for predictive completions (v0.0.2)
https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.3
Thanks!
=> Update Modus Themes to v0.0.3

extensions.toml
This PR bumps the Code::Stats extension to v0.2.4.
=> code-stats: Bump to v0.2.4

extensions.toml
Hi, this PR bumps Modus Themes to v0.0.4. The release page is here https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.4 but here is the list of changes at your convenience:
- [Add `drop_target` color](https://github.com/vitallium/zed-modus-themes/commit/49eaac36900aadca4d2dc4ee73c8e2ed4677bbec)
- [Add tritanopia variants](https://github.com/vitallium/zed-modus-themes/commit/bcd3df9fe6baea3aa8d202ecda0caae72dd92c9a)
- [Add deuteranopia variants](https://github.com/vitallium/zed-modus-themes/commit/4bb89a77fb7c4806f5fc151b71f5a7a6ff52d770)
- Synced all theme colors with the upstream
- [Fix terminal colors for Modus Operandi](https://github.com/vitallium/zed-modus-themes/commit/7a9c6dca47b4145b26faceb2ba96b67a9744ee8c)
Thanks!
=> Update Modus Themes to v0.0.4

.gitmodules, extensions.toml
=> Add CSpell extension

.gitmodules, extensions.toml
Add a darker variant of the Ayu Dark theme. Ported over from [k4yt3x/ayu-vim-darker](https://github.com/k4yt3x/ayu-vim-darker).
The original Ayu Dark, for contrast:
It's my first time working with the Zed ecosystem. I hope I didn't miss anything. If so, please kindly let me know.
=> Add Ayu Darker Theme extension

.gitmodules, extensions.toml
Adds [Dune theme](https://github.com/Anvell/zed-dune-theme) to Zed extensions repository.
Theme ID: `dune-theme`
Initial version: `1.0.0`
<p align="center">
</p>
<p align="center">
</p>
=> Add Dune Theme v1.0.0

extensions.toml
Bumps the HAML extension from v0.0.7 to v0.1.0: https://github.com/davidcornu/zed-haml/releases/tag/v0.1.0
Upstream diff: https://github.com/vitallium/tree-sitter-haml/compare/5dedefd955eaaadec309357879a46edf932945cf...ca002c14a373534affb32079dad6ca4a493451b2
=> Update HAML extension to v0.1.0

extensions.toml
Hi, this PR updates the Modus Themes to v0.0.5 that includes several bug fixes listed on the release page [here](https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.5) but I am copying them here at your convience:
- [Fix the alpha channel for Drag&Drop operations](https://github.com/vitallium/zed-modus-themes/commit/d7f097d787aa92fdd06052a6dcf9b1faf54caffa)
- [Fix the current tab color in Modus Operandi Tinted](https://github.com/vitallium/zed-modus-themes/commit/316f9749fe4dc9de40d67ec1580f04ca8d614a89)
- Fixed https://github.com/vitallium/zed-modus-themes/issues/1
- [Fix button background](https://github.com/vitallium/zed-modus-themes/commit/cfe4747df384371a6d1a54418b4a76b1fc0d359a)
- [Add icon colors](https://github.com/vitallium/zed-modus-themes/commit/508f6ac34c1439bca9992 …
=> Update Modus Themes to v0.0.5

extensions.toml
Release notes:
https://github.com/TheBeyondGroup/zed-shopify-liquid/releases/tag/v0.1.0
=> Update liquid to v0.1.0

extensions.toml
This PR bumps the Clojure extension to v0.1.1.
Changes:
- https://github.com/zed-extensions/clojure/pull/1
=> clojure: Bump to v0.1.1

.gitmodules, extensions.toml
In the repository, there is already a Move plugin, but this plugin only works with the Sui blockchain. move-aptos is an extension that works with the Aptos blockchain. Although they share some syntax.
=> Add move-aptos extension

extensions.toml
Hi! Another small bugfixes only release of Modus Themes - [v0.0.6](https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.6).
- [Fix Hint color](https://github.com/vitallium/zed-modus-themes/commit/4eebdc843a03c29377a156e29d4507bdd7527d64)
- [Fix Predictive foreground color](https://github.com/vitallium/zed-modus-themes/commit/08ac61d55b5ad4949787cdb595bc1da6a8301cce)
- [Fix color of the scrollbar's thumb](https://github.com/vitallium/zed-modus-themes/commit/858b532b4143fedf05b72494e0690fb582d74149)
Thank you!
=> Update Modus Themes to v0.0.6

extensions.toml
- Improve autoconfig so that inverse-search (with sioyek or zathura) works in more scenarios out of the box, such as when zed is installed with flatpak or certain package managers on Linux (https://github.com/rzukic/zed-latex/pull/54)
=> Update LaTeX to v0.1.7

extensions.toml
Changelog: https://github.com/lv37/zed-v/compare/v0.3.0...v0.4.0
=> Update V to v0.4.0

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v5.0.2
=> Bump java to v5.0.2

extensions.toml
Fixes the extension by switching language servers and updating highlights.
Thanks @jannisborgers
- language server:
- old: https://github.com/kaermorchen/twig-language-server
- new: https://github.com/moetelo/twiggy
- pinned to v0.17.0 ([v0.18.0 is current](https://www.npmjs.com/package/twiggy-language-server?activeTab=versions))
- old tree-sitter: https://github.com/gbprod/tree-sitter-twig
- new tree-sitter (fork): https://github.com/jannisborgers/tree-sitter-twig
- [tree-sitter diff](https://github.com/gbprod/tree-sitter-twig/compare/eaf80e6af969e25993576477a9dbdba3e48c1305...jannisborgers:tree-sitter-twig:723926cff978453c40ee11ca8046de0cb248873c)
=> Update Twig extension version to 0.2.0

extensions.toml
Fixed https://github.com/blopker/codebook/issues/1 by switching to using musl instead of libc for building Rust on Linux.
Thank you!
=> Update Codebook to 0.1.1 to work with older Linux builds

extensions.toml
Updated language names to be more human-friendly and fixed highlighting
Rename languages:
- `omnetpp-msg` -> `OMNeT++ MSG`
- `omnetpp-ned` -> `OMNeT++ NED`
=> Update Omnetpp to v0.0.2

.gitmodules, extensions.toml
Adds an extension to support syntax highlighting for SSH config files.
Example:
=> Add SSH-config v0.1.0

extensions.toml
Hi! This pull request updates `Modus Themes` extension to v0.0.7. This version has only bugfixes. You can find the release [here](https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.7) but I also copying its notes here at your convenience. Thanks!
- [Adjust the dimmed foreground color for "Modus Operandi Tinted"](https://github.com/vitallium/zed-modus-themes/commit/165e057561be9a622c3a30d39597c344c2f713e7)
- [Change text.literal fg color to match Modus Themes](https://github.com/vitallium/zed-modus-themes/commit/2b8c96844dae1b454be283d794ecf941949a95d6)
- [Make keyword oblique](https://github.com/vitallium/zed-modus-themes/commit/70c793875f059aad231433c87dcb867cefea9117)
- [Maketype oblique](https://github.com/vitallium/zed-modus-themes/commit/5f8e10230ff62eebf4280193bd8c168583 …
=> Update Modus Themes to v0.0.7

extensions.toml
Update Obsidian Sunset theme extension to v.1.1.0
Repository link: https://github.com/lczerniawski/ObsidianSunset-Zed
=> Update Obsidian Sunset to 1.1.0

extensions.toml
Hi! This pull request updates the `LTeX` extension to v0.0.6. The release page is [here](https://github.com/vitallium/zed-ltex/releases/tag/v0.0.6). This release contains only one bug fix for users who have installed Java and configured `JAVA_HOME` env variable. For some reasone, starting `ltex` LS under such conditions fails with:
```
Language server error: ltex
oneshot canceled
-- stderr--
Error: JAVA_HOME is not defined correctly.
We cannot execute /Users/vslobodin/.local/share/mise/installs/java/21.0.2
[?2004l/bin/java
```
Thanks!
=> Update ltex to v0.0.6

extensions.toml
Whoops! I might have put the name in wrong in the previous PR :sweat:.
=> Update Monokai Vibrant Amped to v0.0.2

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.0.0
=> Bump java to v6.0.0

.gitmodules, extensions.toml
An extension that integrates Confluence pages into the Assistant Panel, enabling users to add their content as context. I believe this could be useful for teams that rely on Confluence for comprehensive documentation.
=> Add Confluence Context Server extension

extensions.toml
This PR updates the Vue extension to v0.2.0.
See https://github.com/zed-extensions/vue/pull/14 for the changes in this version.
=> vue: Bump to v0.2.0

extensions.toml
This PR updates the Gleam extension to v0.3.0.
See https://github.com/gleam-lang/zed-gleam/pull/8 for the changes in this version.
=> gleam: Bump to v0.3.0

extensions.toml
This PR updates the Clojure extension to v0.2.0.
See https://github.com/zed-extensions/clojure/pull/8 for the changes in this version.
=> clojure: Bump to v0.2.0

extensions.toml
`schema_version` was incorrectly set to 2 instead of 1 which prevented the extension from being available to use.
Also add a few color fixes.
=> Update vitesse theme refined to v0.0.2

.gitmodules, extensions.toml
This PR updates the Prisma extension to v0.1.0.
The Prisma extension now lives at https://github.com/zed-extensions/prisma.
See https://github.com/zed-extensions/prisma/pull/1 for the changes in this version.
=> prisma: Bump to v0.1.0

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/9d6c0e57a05209b4a1a46091e9b3450110ee32a1.
=> Bump extension CLI version to `9d6c0e5`

.gitmodules, extensions.toml
This PR adds the [Material Icon Theme](https://github.com/zed-extensions/material-icon-theme).
Note that this requires Zed v0.173.0 or higher in order to use.
=> Add Material Icon Theme

.gitmodules, extensions.toml
Hi, this pull request adds a new extension for proper highlighting and editing of tree-sitter query files (*.scm). The repo is here - https://github.com/vitallium/zed-tree-sitter-query
Here are before&after screenshots:
The only thing is: Scheme language also uses the `scm` extension so there might be a conflict when you open a Scheme file or a Tree-sitter query file. Thanks!
=> Add tree-sitter-query extension

.gitmodules, extensions.toml
Move scheme extension from zed tree to dedicated repo:
- https://github.com/zed-extensions/scheme
No-op otherwise.
=> Bump scheme to v0.0.3

extensions.toml
Add preview and two-way sync for linux+GNOME.
I also add a `textobjects.scm` as per [the docs](https://zed.dev/docs/extensions/languages?highlight=text#text-objects)
defining captures for 'class' but vim-mode movements like `[[` and `]]` seem unaffected. I'm adding here to experiment and see if it's a dev-extension limitation.
=> Update LaTeX to v0.1.9

extensions.toml
- Set drop_target.background color
- Make the text.accent color easier to see
- Set the tag color under syntax
- Set the color editor.document_highlight.bracket_background
- Add black terminal colors that are easy to see
=> Update Gentle Dark to v1.1.0

.gitmodules, extensions.toml
Thank you for implementing support for custom icons in Zed!
This PR adds the [zed-vscode-icons](https://github.com/pranavmangal/zed-vscode-icons) theme, which uses icons from the popular [vscode-icons](https://github.com/vscode-icons/vscode-icons) project.
=> Add VSCode icons theme

extensions.toml
Hi, this PR bumps the Ruby extension to v0.4.4. 
Here is the full list of changes:
All screenshots were made by using the following settings:
- Default theme `One Dark`
- Font `Berkeley Mono v2`, size 15.
- Zed Preview 0.172.8
- [Remove .rdoc from the list of Ruby files](https://github.com/zed-extensions/ruby/commit/1109c8bf3898d501aaacd465e2747f3f70cd874a)
| Before  | After  |
|---------|--------|
| ![rdoc_before](https://github.com/user-attachments/assets/63c529d1-7e83-475a-b244-4ffbfdcfcc61) | ![rdoc_after](https://github.com/user-attachments/assets/5f7a9fbd-d1b4-4afa-8064-f87ca607864f) |
- [Change `identifier` and `global_variable` highlighting](https://github.com/zed-extensions/ruby/commit/a5a818d0a2460973425ffee7d2834063dae7409e)
| Before  | After  |
|---------|--------|
| …
=> Bump Ruby to v0.4.4

extensions.toml
Updated submodule to 0.1.2 tag
https://github.com/scalameta/metals-zed/compare/v0.1.1...v0.1.2
=> Update Scala to v0.1.2

extensions.toml
This PR bumps the Material Icon Theme to v0.1.1.
=> material-icon-theme: Bump to v0.1.1

extensions.toml
This PR updates the Material Icon Theme extension to v0.1.2.
=> material-icon-theme: Bump to v0.1.2

extensions.toml
- See: https://github.com/zed-extensions/beancount/pull/8
- Includes: https://github.com/zed-extensions/beancount/pull/7
=> Bump beancount to v0.0.5

extensions.toml
Hi, this pull request updates Modus Themes to support newly introduced `version.*` color themes settings for the upcoming Git panel.
=> Bump Modus themes to v0.0.8

extensions.toml
Changelog: https://github.com/lv37/zed-v/compare/v0.4.0...v0.4.1
=> Update V to v0.4.1

.gitmodules, extensions.toml
In this PR
* Bumped version to `0.2.0`
* Added icons for `default file` `documents` `heroku` `json` `lock` `metal` `phoenix` `roc` `templates` `v`
* Fixed typo on extension repo
=> Update Bearded Icon Theme to 0.2.0

.gitmodules, extensions.toml
Includes:
- Extraction of PHP extension from [zed-industries](https://github.com/zed-industries/zed/) to [zed-extensions/php](https://github.com/zed-extensions/php)
- https://github.com/zed-industries/zed/pull/24558 (thanks @MrSubidubi!)
See:
- https://github.com/zed-extensions/php/pull/1
=> Bump PHP to v0.2.5

extensions.toml
Just changes the repo URL.
Includes:
- https://github.com/zed-extensions/php/pull/2
=> Bump PHP to v0.2.6

.gitmodules, extensions.toml
Update URL fix to point at new repo: [zed-extensions/legacy-themes](https://github.com/zed-extensions/legacy-themes).
=> Bump Zed Legacy Themes to v0.0.2

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.4
Diff: https://github.com/ocsmit/zed-r/compare/v0.0.3...v0.0.4
=> Update r to v0.0.4

extensions.toml
Release notes:
https://github.com/tecandrew/catppuccin-zed-icons/releases/tag/v1.17.2
=> Update catppuccin-icons to v1.17.2

extensions.toml
Hello! This PR is about updating the Ruby extension to v0.4.5 which has a single improvement for displaying symbols in Ruby test files. Here is a screenshot showing how it appears in action:
Thank you!
=> Update Ruby to v0.4.5

extensions.toml
This PR bumps the Code::Stats extension to v0.2.5.
=> code-stats: Bump to v0.2.5

.gitmodules, extensions.toml
Add `vscode-light-plus` theme extension
> Port of the VSCode Light+ (Default Light+) theme for the Zed code editor
Project: https://github.com/MadLittleMods/zed-theme-vscode-light-plus
=> Add `vscode-light-plus` theme extension

extensions.toml
Bumps fsharp to [0.0.5](https://github.com/nathanjcollins/zed-fsharp/releases/tag/0.0.5)
=> Bump fsharp to v0.0.5

.gitmodules, extensions.toml
Hello there! It's me again, the same guy from a few hours ago failing your CI/CD checks.
I have now added light theme icons to the icon theme, which should make this theme possible to use on various light themes - it works really well for basically all themes I tested!
Here's the change log:
- Split up the extension into light and dark icons
- Updated the ActionScript icon to have a newer look akin to the JS/TS
icons.
- Changed the README.md slightly
- Bumped version to 0.3.0
=> Update colored-zed-icons-theme to v0.3.0

extensions.toml
Release notes:
https://github.com/catppuccin/zed-icons/releases/tag/v1.17.4
=> Update catppuccin-icons to v1.17.4

extensions.toml
This PR updates the Deno extension to v0.1.0.
See https://github.com/zed-industries/zed/pull/25255 for the changes in this version.
=> deno: Bump to v0.1.0

extensions.toml
This PR updates the TOML extension to v0.1.3.
See https://github.com/zed-industries/zed/pull/25278 for the changes in this version.
=> toml: Bump to v0.1.3

extensions.toml
Fixing an issue with custom tags, e.g. including `.`.
=> Update Cucumber to v0.0.2

extensions.toml
Release notes:
https://github.com/0PandaDEV/zed-one-dark-flat/releases/tag/v0.1.1
=> Update one-dark-flat to v0.1.1

extensions.toml
Update Axolosin theme to v1.1.1
Changes:
- Updated `scrollbar_thumb.background` style property to `scrollbar.thumb.background` to comply with https://github.com/zed-industries/zed/pull/8004
=> Update Axolosin to v1.1.1

extensions.toml
This replaces scrollbar_thumb with scrollbar.thumb and fixes #2101 for this theme
=> Update neovim-default theme to v0.3.0

extensions.toml
Release notes:
https://github.com/catppuccin/zed-icons/releases/tag/v1.18.0
=> Update catppuccin-icons to v1.18.0

extensions.toml
To stop using deprecated `scrollbar_thumb.background`.
=> Update `visual-assist-dark` to v0.0.4

.gitmodules, extensions.toml
[Air](https://github.com/posit-dev/air) is an extremely fast R code formatter, using the same underlying infra as both Ruff and Biome.
We've been working on a Zed extension (mostly mimicking Ruff) which lives here:
https://github.com/posit-dev/air/tree/main/editors/zed
The submodule commit points to https://github.com/posit-dev/air/commit/88c573ba9cdabf084cf7817ab419f87beea37b39 where we've introduced 0.1.0 of the zed extension.
Note that I had a bit of trouble finding the `path =` option to point Zed to our `editors/zed` subdirectory. I've also mentioned this here: https://github.com/zed-industries/zed/discussions/25575. I think I have it set up right, but it's hard for me to test. An extra line or two in the "Developing Extensions" section about this option would be great and would have …
=> Add Air extension

.gitmodules, extensions.toml
This PR updates the golangci-lint extension to v0.2.0.
The extension now lives at [zed-extensions/golangci-lint](https://github.com/zed-extensions/golangci-lint).
=> golangci-lint: Bump to v0.2.0

extensions.toml
Migrated most of my themes to use proper `scrollbar.thumb.background` tag as requested.
The missing themes (tomorrow, gruber-flavors, and v0) will be bumped to next version separately as I had other updates to make to those.
This should close these issues:
- https://github.com/bIaqat/aquarium-theme-zed/issues/1
- https://github.com/bIaqat/aylin-theme-zed/issues/1
- https://github.com/bIaqat/cyan-light-theme-zed/issues/2
- https://github.com/bIaqat/ember-theme-zed/issues/1
- https://github.com/bIaqat/flat-theme-zed/issues/2
- https://github.com/bIaqat/lusch-theme-zed/issues/1
- https://github.com/bIaqat/mariana-theme-zed/issues/2
- https://github.com/bIaqat/nordic-theme-zed/issues/1
- https://github.com/bIaqat/panda-theme-zed/issues/1
- https://github.com/bIaqat/polar-theme-zed/issues/1
- …
=> Update deprecated `scrollbar_thumb.background` usage in various themes

.gitmodules, extensions.toml
This PR adds a `/jira` slash command to pull an issue from JIRA and include it as a JSON object in assistant context.
Repo: https://github.com/trbroyles1/jira-slash-command
* Implementation is pure Rust, so no external MCP required.
* Uses `http_client` from the Zed extension API to talk to JIRA.
* Requires setting 3 environment variables: 
- `JIRA_URL`
- `JIRA_USER`
- `JIRA_API_TOKEN`. 
Example usage is like: `/jira JRA-1234`
The following issue fields will be included:
* Issue Key
* Summary
* Description
* Issue Type
* Created At
* Reporter
* Assignee (or "Unassigned" if not assigned)
* Status
Comments will be included, each will have:
* Author
* Created At
* Comment Body
It will _not_ try to do anything with attachments on the issue or images posted in the issue or comment bodies.
Ref …
=> Add `/jira` slash command extension

extensions.toml
bumps the outrun theme version to resolve https://github.com/Acepie/OutrunZedTheme/issues/1
=> Update outrun theme to v0.0.2

.gitmodules, extensions.toml
Fixes #1648
- This PR adds an extension to wrap `stylelint` LSP,
- [Stylelint](https://stylelint.io/) is used to lint CSS content in files that support it (CSS, SCSS, JS, etc.),
- The [VSCode Stylelint Extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) is fairly popular with more than 2,595,360 installs,
- The LSP server comes from the [stylelint/vscode-stylelint](https://github.com/stylelint/vscode-stylelint) project but there are few things to note:
- the GitHub repository contains both the LSP server and the VSCode extension code,
- the LSP server is not entirely decoupled from VSCode extension code but it does work on it's own,
- neither the LSP Server or the VSCode are published as npm packages,
- the source code needs to be built (TypeScript …
=> Add stylelint extension

.gitmodules, extensions.toml
This extension adds syntax highlighting for python `requirements.txt` and `constraints.txt` files.
Some post-installation steps are documented in the [README](https://github.com/dargor/zed-python-requirements/blob/master/README.md).
=> Add Python requirements extension

.gitmodules, extensions.toml
This extension adds syntax highlighting for hyprlang and optional language server support for hyprland config files.
It uses [hyprls](https://github.com/hyprland-community/hyprls) as a language server (which needs to be installed manually) and the [tree-sitter-hyprlang](https://github.com/tree-sitter-grammars/tree-sitter-hyprlang) tree sitter grammar.
close #695
=> Add hyprlang extension

.gitmodules, extensions.toml
Update the ezio-theme extension: 
- Adds release.yml to automate future updates 
- Bumps `ezio-theme/extension.toml` and `extensions.toml` to v0.0.3
- Updates colors of errors to be more readable 
**Before**
**After**
=> Update ezio-theme to v0.0.3

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.5
=> Update r to v0.0.5

extensions.toml
Release notes:
https://github.com/MordFustang21/zed-github-dark/releases/tag/v1.0.8
=> Update github-dark-default to v1.0.8

extensions.toml
- Update extension's title and description with 'spell checker' keywords
=> Update Typos extension to v0.0.5

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/d5bc7b9a7909269e649431e7380341b3f9c95138.
=> Bump extension CLI version to `d5bc7b9`

.gitmodules, extensions.toml
The icon theme now has properly scaled Svelte icons, which I have tested and they work perfectly!
=> Update colored-zed-icons-theme to v0.3.1

extensions.toml
Release notes:
https://github.com/phibr0/zed-min-theme/releases/tag/v0.1.10
=> Update min-theme to v0.1.10

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.0.6
=> Update r to v0.0.6

.gitmodules, extensions.toml
This PR updates the C# extension to v0.1.2.
The C# extension now lives at https://github.com/zed-extensions/csharp.
=> csharp: Bump to v0.1.2

.gitmodules, extensions.toml
Adds support for the [REDscript](https://github.com/jac3km4/redscript) programming language. It has an LSP and a treesitter grammar, I've tested it manually and both work pretty well in Zed.
=> Add redscript extension

.gitmodules, extensions.toml
This PR updates the Erlang extension to v0.1.2.
The Erlang extension now lives at https://github.com/zed-extensions/erlang.
=> erlang: Bump to v0.1.2

extensions.toml
Release notes:
https://github.com/TheBeyondGroup/zed-shopify-liquid/releases/tag/v0.2.0
=> Update liquid to v0.2.0

.gitmodules, extensions.toml
This PR updates the Lua extension to v0.1.2.
The Lua extension now lives at https://github.com/zed-extensions/lua.
=> lua: Bump to v0.1.2

extensions.toml
Hi, this PR updates Modus Theme to v0.0.10 that fixes two small issues:
- Changed: [Use new color names for VCS](https://github.com/vitallium/zed-modus-themes/commit/d28420841a10160b5dcfb7a84f291c8ef2fb8559)
- Fixed: [Use fg_link for accent colors of text and icons](https://github.com/vitallium/zed-modus-themes/commit/07324a8fd54f7be437b2366b557d279236ddce4c)
Thanks!
=> Update Modus Theme to v0.0.10

.gitmodules, extensions.toml
This PR updates the Haskell extension to v0.1.4.
The Haskell extension now lives at [zed-extensions/haskell](https://github.com/zed-extensions/haskell).
=> haskell: Bump to v0.1.4

extensions.toml
This PR updates the Gleam extension to v0.4.0.
See https://github.com/gleam-lang/zed-gleam/pull/12 for the changes in this version.
=> gleam: Bump to v0.4.0

extensions.toml
Release notes:
https://github.com/ziishaned/zed-jetbrains-icons/releases/tag/v0.0.3
=> Update jetbrains-icons to v0.0.3

extensions.toml
[jackTabsCode](https://github.com/jackTabsCode) had released [zed just extension](https://github.com/jackTabsCode/zed-just/tree/v0.1.4) v0.1.4, which supports the `[group]` part now.
- extension diff: https://github.com/jackTabsCode/zed-just/compare/0a1b7f3fdf27f8c8a089203190774839511af1bc...ea24f1debf8433b0e67f0541e6d40b3c2c6cad6e
- tree-sitter diff:  https://github.com/IndianBoy42/tree-sitter-just/compare/792717c262df6d6fa285c1136a11c23cedadcb0c...3f90d24eb8c8d9e8c74fee7120d79c3ec7229f26
=> Update Just to v0.1.4

.gitmodules, extensions.toml
This PR updates the Terraform extension to v0.1.3.
The Terraform extension now lives at [zed-extensions/terraform](https://github.com/zed-extensions/terraform).
=> terraform: Bump to v0.1.3

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/acf9b22466fc0f1aa26c4a403278bef6a1560aaa.
=> Bump extension CLI version to `acf9b22`

extensions.toml
This PR updates the Haxe extension to version 0.3.0.
- Completions are now styled.
- Fixed bracket-related grammar issues.
- Bumped required extension API version.
=> Update Haxe to v0.3.0

.gitmodules, extensions.toml
This PR updates the PureScript extension to v0.1.1.
The PureScript extension now lives at https://github.com/zed-extensions/purescript.
=> purescript: Bump to v0.1.1

.gitmodules, extensions.toml
This PR updates the Uiua extension to v0.0.2.
The Uiua extension now lives at https://github.com/zed-extensions/uiua.
=> uiua: Bump to v0.0.2

extensions.toml
<details><summary>Adds <code>variable.special</code></summary>
</details>
<details><summary>Fixes version control modified name as pointed out in <a href="https://github.com/zed-industries/zed/pull/26606">#26606</a></summary>
</details>
<details><summary>Fixes subheader color</summary>
</details>
<details><summary>Fixes git ignored file colors</summary>
</details>
=> Bump Darcula Dark to v0.1.1

extensions.toml
Release Note: 
https://github.com/weartist/zed-rainbow-csv/releases/tag/v1.0.0
=> Update rainbow-csv to v1.0.0

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.1.0
=> Update r to v0.1.0

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.1.1
=> Update r to v0.1.1

extensions.toml
Fix performance issue with build+preview on save with evince (GNOME default viewer): https://github.com/rzukic/zed-latex/issues/67
=> Update LaTeX to v0.1.13

extensions.toml
Release notes:
https://github.com/Tzal3x/move-zed-extension/releases/tag/v0.0.2
=> Update move to v0.0.2

extensions.toml
Release notes:
https://github.com/Acepie/OutrunZedTheme/releases/tag/v0.0.3
=> Update outrun to v0.0.3

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.1.2
=> Update r to v0.1.2

extensions.toml
Release notes:
https://github.com/MordFustang21/zed-github-dark/releases/tag/v1.0.9
=> Update github-dark-default to v1.0.9

.gitmodules, extensions.toml
Hi !
I really want to add this extension for zed!
It's extension for fantastic web-framework $mol
which out of the box supports **fully offline work** after the build
**work between windows and browser tabs**
incredible reactivity that renders only the necessary component in which the data is re-rendered
The application does **not crash due to errors**!
and that's not all, and all this was 10 years ago!
and this is all out of the box, you don't need to write anything, you only write business code! (logical code)
Links:
- https://github.com/dev-cmyser/zed-tree-mol-support
- https://github.com/Dev-cmyser/tree-sitter-mol-view-tree
=> Add viewtree extension

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.2.0
=> Update r to v0.2.0

extensions.toml
https://github.com/rubiojr/gas/releases/tag/v0.3.0
Supersedes https://github.com/zed-industries/extensions/pull/2305 that was closed accidentally.
=> Update github-activity-summarizer to v0.3.0

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.2.1
=> Update r to v0.2.1

.gitmodules, extensions.toml
I realized there was a bunch of recent work I hadn't pushed so the current extension is quite out of date. This should fix it.
=> Update Phosphor Icons Theme to v0.0.2

.gitmodules, extensions.toml
Hiya,
I'd love to add my theme I've been using for a while. It's a nice pastel-y dark theme, mainly optimized for rust.
Fwiw, when triyng to publish this, the sort script threw an exception for me 
```
const [subginal, key, value] = subline.match(/(.*?)\s*=\s*(.*)/);
^
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
at Object.deserialize (F:\zed_extensions\node_modules\git-submodule-js\dist\index.js:24:48)
at readGitmodules (file:///F:/zed_extensions/src/lib/git.js:41:24)
at async sortGitmodules (file:///F:/zed_extensions/src/lib/git.js:46:22)
at async file:///F:/zed_extensions/src/sort-extensions.js:5:1
```
so I had to sort things manually.
=> Add haku-dark-theme

extensions.toml
This PR updates the Postgres Context Server extension to v0.0.2.
=> postgres-context-server: Bump to v0.0.2

extensions.toml
This PR updates the Svelte extension to v0.2.6.
=> svelte: Bump to v0.2.6

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.0.1
=> Bump java to v6.0.1

extensions.toml
Hi, this PR updates Modus Themes to v0.0.11 which includes a small fix to address the background for inlay hints when you enable the background for them:
```jsonc
"inlay_hints": {
"enable": true,
"show_background": true // This configuration option
},
```
|before|after|
|-----|------|
|![CleanShot 2025-03-28 at 13 37 04@2x](https://github.com/user-attachments/assets/abe9f7b1-1237-458b-841d-ce243a1e5ab6)|![after](https://github.com/user-attachments/assets/5057f70e-9fa0-4a62-a572-d5d1a28cfb4a)|
Thanks!
=> Update Modus Themes to v0.0.11

extensions.toml
Changes: https://github.com/someone13574/zed-verilog-extension/releases/tag/v0.0.7
=> Bump verilog to v0.0.7

.gitmodules, extensions.toml
this adds a few `.svelte` only snippets
I am looking into having `.ts` snippets for svelte in the same extension but not sure at the moment how to have multiple files in the snippets field in extension.toml 
if I use multiple it does not show any snippets
=> Add Svelte Snippets extension

extensions.toml
revert: Remove empty string parsing support due to critical bugs
This reverts commits 81bfb05 and 5d0abb3. The changes caused unexpected parsing failures in quoted CSV fields. Rollback to stable parser behavior
=> Update rainbow-csv to v1.0.1

extensions.toml
- Fixes support for `Vue.js` files
=> Update Stylelint to v0.0.4

extensions.toml
This PR updates the nebula-pulse extension submodule to version 0.0.6 and updates the version in extensions.toml
=> Update nebula-pulse to v0.0.6

.gitmodules, extensions.toml
This PR adds the ZedHacker theme, a cyberpunk-inspired theme collection with three distinct variants optimized for contrast and readability.
- 🎨 Enhanced contrast for better UI element visibility
- 🖥️ Multiple theme variants (Monochrome, Matrix, Light)
- ⌨️ Improved selection states for keyboard navigation
- 🧩 Refined syntax highlighting for better code comprehension
- 🌓 Support for both light and dark environments
Vibrant green-focused cyberpunk theme inspired by classic hacker aesthetics.
Classic black and white aesthetic with maximum contrast for readability.
Light background variant ideal for daytime coding and high-glare environments.
Note: I had some issues running the `pnpm sort-extensions` script due to dependency errors, but I've manually placed my entry in alphabetical order in …
=> Add ZedHacker theme extension

.gitmodules, extensions.toml
In this PR, I introduce an extension to add the [Postgres Language Server](https://pgtools.dev) built by the lovely folks at Supabase.
=> Add Postgres Language Server

.gitmodules, extensions.toml
I'd like to submit the `Ninja Theme Collection` for inclusion in the official Zed extensions repository.
`Ninja` is a comprehensive theme suite with enhanced contrast, optimized readability, and robust accessibility features. The collection includes four carefully designed variants to support different preferences and needs:
- **Ninja Dark** - A refined dark theme with improved contrast and carefully weighted syntax elements
- **Ninja Light** - A clean, bright counterpart maintaining the same semantic relationships as the dark theme
- **Ninja Cosmic** - A vibrant, colorful theme with neon-inspired accents for developers who prefer more visual excitement
- **Ninja Colorblind** - An accessibility-focused theme with deuteranopia-friendly colors and enhanced font styling
- Optimized for 20+ …
=> Add Ninja Theme extension

.gitmodules, extensions.toml
This extension integrates [Framelink Figma MCP Server](https://github.com/GLips/Figma-Context-MCP) as a context server for Zed's Assistant.
=> Add Figma MCP Server extension

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-figma/releases/tag/v0.0.2
=> Update mcp-server-figma to v0.0.2

extensions.toml
Fixed potential security issue in ned grammar in OMNeT++ extension and updated version to 0.0.3
Tree-sitter diff: https://github.com/omnetpp/tree-sitter-ned/compare/f008614a9db91a39e6ba58461c3cbea30c3e4fd8...f18d2c7c0224ff868d8610367ed720147aa227e4
=> Update omnetpp to v0.0.3

extensions.toml
Upgrade the halcyon extension to version 0.2.1, reflecting the latest changes and improvements.
=> Update halcyon extension to v0.2.1

extensions.toml
Hi, this PR updates Modus Themes to v0.0.13. Just minor changes:
- [Add `document_highlight` colors](https://github.com/vitallium/zed-modus-themes/commit/6a40f0537d80cdf7c2becc9f907835bb8310e1bd)
- [Update the foreground color for inlay hints](https://github.com/vitallium/zed-modus-themes/commit/11a07c36b8968468e416c8ee7adfb095e89b8b28)
Thanks!
=> Update Modus themes to v0.0.13

extensions.toml
Updating the meson extension due to changes in the build process.
It should also be noted that I can't really maintain the extension much anymore as noted on the README now. I do not have a Linux or macOS machine with the capability to maintain it as my only machine as of right now is Windows.
If there's anyone who would take up the mantle in maintaining the extension, please let me know.
=> Update Meson to v0.4.0

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-github/releases/tag/v0.0.2
=> Update mcp-server-github to v0.0.2

.github/workflows/ci.yml
We don't want to make `git-lfs` be a requirement for interacting with this repo so prevent submodules from using git-lfs.
If submodule includes git-lfs it'll fail tests like this: (test run [here](https://github.com/zed-industries/extensions/actions/runs/14311780680/job/40108330859)):
Follow-up to:
- https://github.com/zed-industries/extensions/pull/2428
=> ci: Add Git Checks

extensions.toml
Hi, this is the second version of the previously reverted MR where GIT LFS was enabled: I disabled it and bumped theme to v0.0.15. The changelist is basically the same as in https://github.com/zed-industries/extensions/pull/2421:
1. [Changed license to GPL-v3](https://github.com/vitallium/zed-modus-themes/commit/14134b703a8faba646fdc8f3ca4a61c26aa9d231)
2. [Refine many color values in modus-operandi-tinted](https://github.com/vitallium/zed-modus-themes/commit/3eedc6fb55567afaad7c768fab144806664ba0b3)
3. [Refine green-warmer in modus-vivendi-tinted](https://github.com/vitallium/zed-modus-themes/commit/21308c30e7135b1f2d5739dd35575fc65ef1155e)
4. [Reduce the amount of magenta in some parts of the deuteranopia variants](https://github.com/vitallium/zed-modus-themes/commit/63389742546709e0ebcd …
=> Update Modus themes to v0.0.15

.gitmodules, extensions.toml
Add `prisma-mcp` extension that provides support for the MCP server in Prisma ORM.
=> Add `prisma-mcp` extension

extensions.toml
This PR bumps the Yara extension to `0.0.4` which adds support for the Yara Language Server if installed.
I can install the new version locally as a dev extension without having YLS installed, so this shouldn't cause any issues.
More info: https://github.com/egibs/yara.zed/pull/1
=> Update yara to v0.0.4

extensions.toml
This PR updates the HTML extension to v0.2.1.
See https://github.com/zed-industries/zed/pull/28575 for the changes in this version.
=> html: Bump to v0.2.1

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.0.2
=> java: Bump to v6.0.2

.gitmodules, extensions.toml
The very powerful [ast-grep](https://ast-grep.github.io/) tool can be used to write custom lints. Since it supports LSP integration, we can get those errors/warnings/suggestion inline while editing our files.
This first version of the ast-grep extension is pretty basic. Since ast-grep itself is configured via files in the project itself, we don't need anything special in the extension. To keep things simple, we are requiring that the user installs ast-grep themselves. I suspect many users will already be doing so anyways since ast-grep has other useful commands (ex. to test rules as you write them) but I may attempt to add auto install in a future version.
- Extension Repo: [mathieulj/ast-grep-zed](https://github.com/mathieulj/ast-grep-zed)
=> Add ast-grep extension

extensions.toml
Release notes:
https://github.com/catppuccin/zed/releases/tag/v0.2.22
=> Update catppuccin to v0.2.22

extensions.toml
Small update
Changelog:
- Add aarch64 support for Linux
- Update zed_extension_api version to 0.3.0
=> Update neocmake extension to v0.0.6

.github/workflows/ci.yml
This includes:
- https://github.com/zed-industries/zed/pull/28608
Which should unblock:
- https://github.com/zed-industries/extensions/pull/2443
New commit: [e34fee55a05e6ceb928b7d57f84c51cdd4fd323a](https://github.com/zed-industries/zed/commits/e34fee55a05e6ceb928b7d57f84c51cdd4fd323a) (2025-04-15)
Old commit: [acf9b22466fc0f1aa26c4a403278bef6a1560aaa](https://github.com/zed-industries/zed/commits/acf9b22466fc0f1aa26c4a403278bef6a1560aaa) (2025-03-13)
Build job was here:
- https://github.com/zed-industries/zed/actions/runs/14479521777/job/40613241316
=> Update the Zed Extension CLI version

extensions.toml
Changelog: https://github.com/lv37/zed-v/compare/v0.4.1...v0.4.2
=> Update V to v0.4.2

.gitmodules, extensions.toml
Refactor: Add Monospace Icon Theme
**What this PR does:**
This pull request introduces a new icon theme for the Zed editor called "Monospace".
**Basis and Inspiration:**
This icon theme is based on and inspired by the clean and distinctive Monospace Icon theme originally found in [**Firebase Studio**](https://firebase.google.com/studio). The aim is to bring a similar visual style and feel for file and folder icons to the Zed editing environment.
**Testing:**
* I have tested this theme locally in my Zed editor to ensure icons are displayed correctly for various file types and folders.
**Checklist:**
Looking forward to your review!
=> Add monospace-icon-theme extension

extensions.toml
This PR updates Modus Themes to v0.0.16. This release syncs changes with the upstream release of [Modus Themes v4.7.0](https://github.com/protesilaos/modus-themes/releases/tag/4.7.0). The following changes apply specifically to the Zed themes:
- [Make yellow-cooler of modus-operandi-tinted even more dark](https://github.com/vitallium/zed-modus-themes/commit/eb060dc362cb35fd1d313a5a3494143329c5f918)
- [Swap the mappings of 'type' and 'variable' in modus-operandi-tinted](https://github.com/vitallium/zed-modus-themes/commit/ff28588924eeb149b929f03b91e0892912ac497c)
- [Make yellow-faint of modus-operandi-tinted a bit darker](https://github.com/vitallium/zed-modus-themes/commit/32a69dfe21c3eea21ca7b7ea97c962c1b27fdae0)
- [Make yellow-cooler of modus-operandi-tinted a bit …
=> Update Modus Themes to v0.0.16

extensions.toml
Release notes:
https://github.com/irmhonde/monospace-icon-theme/releases/tag/v0.1.1
=> Update monospace-icon-theme to v0.1.1

extensions.toml
Release notes:
https://github.com/irmhonde/monospace-icon-theme/releases/tag/v0.1.2
=> Update monospace-icon-theme to v0.1.2

.gitmodules, extensions.toml
Repository migrated from d1y to [zed-extensions/dockerfile](https://github.com/zed-extensions/dockerfile).
Includes:
- https://github.com/zed-extensions/dockerfile/pull/18
- https://github.com/zed-extensions/dockerfile/pull/17
- https://github.com/zed-extensions/dockerfile/pull/16
=> Update Dockerfile to v0.0.5

extensions.toml
Release notes:
https://github.com/frederik-uni/zed-live-server/releases/tag/v0.3.1
=> Update live-server to v0.3.1

.gitmodules, extensions.toml
This is an extension to be used alongside the LaTeX one, providing a (very new) language server which only deals with live preview of a LaTeX document using [TeXpresso](https://github.com/let-def/texpresso), while `texlab` (from other extension) will provide all the other language server capabilities (go-to-definition, completions, snippets...). TeXpresso is a very experimental project but pulls off something not seen anywhere else in the LaTeX world with the preview updating smoothly with every keystroke. This particular project (LSP and zed integration) was prompted by a [user request in the LaTeX extension](https://github.com/rzukic/zed-latex/issues/85) and since then I have personally found it incredibly compelling.
*Demo showing live preview and inverse-search (clicking on parts of …
=> Add TeXpresso extension

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.2.2
=> Update r to v0.2.2

.gitmodules, extensions.toml
This pull request:
- adds syntax highlighting support for enums (https://github.com/acquitelol/elle/commit/4c807696b47debb58abe8850edcc649a22acccd8)
- adds the `type` keyword for pretty hover diagnostics when hovering primitive types 
(https://github.com/acquitelol/elle/commit/27d8f64b723f27dbafc3f5fd8e17bc9465130599 and https://github.com/acquitelol/elle/commit/eb4e12e665948f7c18353cef367b6264077aa506)
The submodule itself has many more changes (it's the whole compiler toolchain), but you can view the changes specifically for the extension since April 18th (my last pull request) [here](https://github.com/acquitelol/elle/commits/rewrite/editors/zed?since=2025-04-19&until=2025-04-30)
=> Update elle to v0.3.0

extensions.toml
Hi, this pull request updates Modus Themes to [v0.0.17](https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.17). List of changes:
- Revised all themes
- [Make read_background not that subtle](https://github.com/vitallium/zed-modus-themes/commit/769835a1f74c6d4c90bc5a348ccffe96a4f691f4)
- [Remove obsolete version.control.* colors](https://github.com/vitallium/zed-modus-themes/commit/831a562eb9abadc639924d2590b2d375f28cc354)
- [Introduce 'property' mapping](https://github.com/vitallium/zed-modus-themes/commit/2a2d60196be90c683ae98edab696e5aaec3795e0)
- [Make small refinements to modus-vivendi-tinted bg-paren-match value](https://github.com/vitallium/zed-modus-themes/commit/a742d262431f30995d5129e69815da2254bfb18f)
- [Revert "Revise all "paren" colours to be …
=> Update Modus Themes to v0.0.17

extensions.toml
I forgot to update the tag which veridian was downloading from, so it was downloading the veridian build from 0.0.5.
tree-sitter diff: https://github.com/gmlarumbe/tree-sitter-systemverilog/compare/0dacb911daa9614a7c7e79a594d4cb9f478e6554...ba3c1e305caf948f718293c86c6018a82ed5043e
language-server diff: https://github.com/someone13574/zed-verilog-extension/compare/v0.0.5...v0.0.8
=> Bump verilog to v0.0.8

extensions.toml
Release notes:
https://github.com/jayvicsanantonio/barbenheimer-zed-theme/releases/tag/v1.3.1
=> Update barbenheimer to v1.3.1

extensions.toml
Release notes:
https://github.com/vitallium/zed-tree-sitter-query/releases/tag/v0.0.2
=> Update tree-sitter-query to v0.0.2

extensions.toml
Minor update that changes the `path_suffix` from `sum` to `go.sum`.
=> Update gosum to v0.0.2

.gitmodules, extensions.toml
In this PR, I update the repo url for the extension. I made a typo and didn't follow my convention when I created this extension.
I bump the version to make sure people get the latest. (Probably not needed.)
=> Update mcp-server-sequential-thinking to v0.0.2

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.2.3
=> Update r to v0.2.3

.gitmodules, extensions.toml
This PR adds a Zed extension with useful React + TypeScript snippets that I often use. Thought it’d be helpful for others to have them bundled in one place.
Looking forward to the review!
=> Add react-typescript-snippets

.gitmodules, extensions.toml
Add syntax highlighting support for ASS/SSA subtitles by integrating the tree-sitter parser from [tree-sitter-ass](https://github.com/huaium/tree-sitter-ass).
=> Add ass subtitles extension

extensions.toml
Hi, this PR updates the Ruby extension to [v0.6.0](https://github.com/zed-extensions/ruby/releases/tag/v0.6.0).
- Update Rust crate zed_extension_api to 0.5.0 by @renovate in https://github.com/zed-extensions/ruby/pull/44
- Fix RSpec outlines by @joeldrapper in https://github.com/zed-extensions/ruby/pull/78
Thanks!
=> Update Ruby to v0.6.0

extensions.toml
This updates the mcp-server-axiom extension to v0.2.0.
This version adds support for the new context-server-configuration API.
=> Update mcp-server-axiom to v0.2.0

extensions.toml
This updates the mcp-server-axiom extension to v0.0.2.
This version adds support for the new context-server-configuration API.
=> Update mcp-server-brave-search to v0.0.2

extensions.toml
Hi, this pull request updates the Ruby extension to [v0.7.1](https://github.com/zed-extensions/ruby/releases/tag/v0.7.1) that contains two bug fixes:
1. Improve language server binary lookup in PATH by @vitallium in https://github.com/zed-extensions/ruby/pull/84
2. Fix gem environment and language server configuration by @vitallium in https://github.com/zed-extensions/ruby/pull/85
Thanks!
=> Update Ruby to v0.7.1

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-github/releases/tag/v0.0.3
=> Update mcp-server-github to v0.0.3

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-figma/releases/tag/v0.0.3
=> Update mcp-server-figma to v0.0.3

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-webflow/releases/tag/v0.0.2
=> Update mcp-server-webflow to v0.0.2

.gitmodules, extensions.toml
Zed extension to support [just-lsp](https://github.com/terror/just-lsp) (language server for `just`).
=> Add `just-ls`

extensions.toml
Hi! This PR updates the Ruby extension to [v0.7.3](https://github.com/zed-extensions/ruby/releases/tag/v0.7.3) that has 2 bug fixes related to using new Process extension API.
Thanks!
=> Update Ruby to v0.7.3

extensions.toml
[CHANGELOG](https://github.com/sectore/zed-just-ls/blob/main/CHANGELOG.md#v011---2025-05-10)
=> Update just-ls to v0.1.1

extensions.toml
Updates to match tree-sitter improvements and bug fixes.
Tree-sitter-diff: https://github.com/ChemisTechlabs/tree-sitter-firebase-security-rules/compare/b855571222af65f32df5e7c9e9e93f1a5a6b3a1b...065c18e6f18436b1d4594f2cb2d6e448a987b737
=> Update firebase-security-rules to v0.1.0

.gitmodules, extensions.toml
This PR adds a new extension for the [JSON5](https://json5.org/) file format.
The grammar is based on [@Joakker](https://github.com/Joakker)'s excellent [tree-sitter-json5](https://github.com/Joakker/tree-sitter-json5) project.
=> Add JSON5 language extension

extensions.toml
Implements context server configuration API - https://github.com/rubiojr/gas/pull/6
This probably needs to wait until Zed 0.186.X is released.
=> Update github-activity-summarizer to v0.5.0

.gitmodules, extensions.toml
This commit adds an extension for the Grafana MCP server. It's useful
when adding observability to existing code, as the MCP server can
do things like search for existing Prometheus metrics or create a
dashboard using the metrics it finds in the code.
=> Add mcp-server-grafana

extensions.toml
Release notes:
https://github.com/catppuccin/zed-icons/releases/tag/v1.20.0
=> Update catppuccin-icons to v1.20.0

.gitmodules, extensions.toml
Adding the removed "Minimal" variants of the [Tomorrow Theme](https://github.com/biaqat/tomorrow-theme-zed.git) as a separate extension 
(As reminded to do by https://github.com/bIaqat/tomorrow-theme-zed/issues/7)
<table>
<tr>
<td> Normal </td>
<td> Minimal </td>
</tr>
<tr>
<td rowspan="2"><img src="https://github.com/bIaqat/tomorrow-theme-zed/raw/main/assets/tomorrow.png" width="500"></td>
<td><img src="https://github.com/bIaqat/tomorrow-min-theme-zed/raw/main/assets/tomorrow-min.png" width="475"></td>
</tr>
</table>
Tomorrow Min was originally removed from "Tomorrow" in this PR https://github.com/zed-industries/extensions/pull/2146
=> Add Tomorrow Minimal Theme

extensions.toml
Release notes:
https://github.com/jylamont/zed-ember/releases/tag/v0.1.0
=> Update ember to v0.1.0

extensions.toml
Release notes:
https://github.com/phibr0/zed-min-theme/releases/tag/v0.2.1
=> Update min-theme to v0.2.1

extensions.toml
Release notes:
https://github.com/irmhonde/shades-of-purple-theme/releases/tag/v0.0.5
=> Update shades-of-purple-theme to v0.0.5

extensions.toml
Submodule Diff:
- https://gitlab.com/flukejones/zed-slint/-/compare/af1487...2b3f4d
=> Update slint to v0.0.7

.gitmodules, extensions.toml
Here is an extension for the RDF Turtle format `.ttl` and `.turtle` extensions.
It provides a tree-sitter grammar, highlighting and a LSP.
Let me know if anything needs to be sorted to be able to merge this.
Links:
- Extension: https://github.com/MoskitoHero/zed-turtle
- LSP NPM package: https://www.npmjs.com/package/turtle-language-server
- LSP Repo: https://github.com/stardog-union/stardog-language-servers
- Tree-sitter: https://github.com/GordianDziwis/tree-sitter-turtle
=> Add RDF Turtle extension

.gitmodules, extensions.toml
This adds a Zed extension that enables IntelliSense and syntax highlighting for [Statamic](https://statamic.com/)’s [Antlers](https://statamic.dev/antlers) templating language.
=> Add Statamic Antlers extension

.gitmodules, extensions.toml
Adds Liquid snippets to facilitate Shopify Theme development following the official [Shopify docs](https://shopify.dev/docs/api/liquid)
=> Add Liquid snippets extension

.gitmodules, extensions.toml
Updates repository URL and removes redundant bash tree-sitter for Shell Script already provided in Zed core.
Diff:
- https://github.com/zed-extensions/bash/compare/v0.0.1...v0.0.3
=> Update basher to v0.0.3

extensions.toml
Hello! This pull request updates Modus themes to [v0.0.19](https://github.com/vitallium/zed-modus-themes/releases/tag/v0.0.19) that contains mostly bug fixes for the VCS stuff:
- [Update version_control.* colors](https://github.com/vitallium/zed-modus-themes/commit/a0c4170d9b462c59ddeb15fbbc2bc9ba63edaf0d)
- [Fix version_control.conflict color](https://github.com/vitallium/zed-modus-themes/commit/0d8504aae7ebe2c2b398364dd04bfc9ac637d2cc)
- [Add success](https://github.com/vitallium/zed-modus-themes/commit/bd8a011112be1dc8e55d90f712c7d93403736628)
- [Change info to info](https://github.com/vitallium/zed-modus-themes/commit/487948e16d77b02fdcdf45f726800953a2b396dd)
- [Change warning to fg_prominent_warning](https://github.com/vitallium/zed-modus-themes/commit/280c032f61db89de87ccbe69fac31184 …
=> Update Modus themes to v0.0.19

extensions.toml
Release notes:
https://github.com/akbxr/gitlab-mcp-zed/releases/tag/v0.0.3
=> Update mcp-server-gitlab to v0.0.3

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.0.4
=> Update Java to v6.0.4

extensions.toml
Release notes:
https://github.com/vitallium/zed-marksman/releases/tag/v0.0.5
=> Update marksman to v0.0.5

extensions.toml
This PR updates the TOML extension to v0.1.4.
See https://github.com/zed-industries/zed/pull/31272 for the changes in this version.
=> toml: Bump to v0.1.4

extensions.toml
- **Adds basic grammar for HXML**, Haxe's compiler configuration syntax.
- Extension no longer fails to start when GH releases cannot be reached. That is, if a recent version of the extension has downloaded the LSP sometime in the past.
- Extension now emits warnings when detecting Lime and Ceramic frameworks with default configuration (their build systems are not supported out-of-the-box).
=> Update Haxe to v0.3.1

extensions.toml
This PR updates the Material Icon Theme extension to v1.0.0.
=> material-icon-theme: Bump to v1.0.0

.gitmodules, extensions.toml
This version contains important fixes for installing the MCP if it doesn't yet exist in `PATH`
=> Update mcp-server-buildkite to v0.0.3

extensions.toml
Release notes:
https://github.com/TheBeyondGroup/zed-shopify-liquid/releases/tag/v0.4.0
=> Update liquid to v0.4.0

.gitmodules, extensions.toml
Adds PlanetScale Model Context Protocol extension that integrates PlanetScale's MCP server with Zed.
- Extension: https://github.com/hunterjsb/zed-planetscale-mcp
- MCP: https://github.com/planetscale/cli
=> Add PlanetScale MCP extension

extensions.toml
Uses the new `extension.toml` format for the extension
Fixes my extension for #2104 
Does the folder name need to be the same as the extension ID? If so, I can update that
=> Update assembly-syntax to v0.0.2

.gitmodules, extensions.toml
This PR upgrades the existing Icons extension for Zed with updated previews, corrected icon mappings, and missing icon config.
* 🐛 **Fixed incorrect icon mapping** for `renovate`.
* 🧹 **Corrected icon associations** in `tsconfig` which previously pointed to the wrong icon.
* ➕ **Added missing icons** for:
* `.env.*` files
* `Makefile` and related variants
* 🔁 **Updated preview assets** for all affected icons.
* ⬆️ **Bumped extension version** to reflect the icon changes.
=> Upgrade `Modern-Icons` to `v0.3.0`

extensions.toml
Release notes: https://github.com/davidcornu/zed-haml/releases/tag/v0.1.1
> * Bump `tree-sitter-haml` to v0.0.5 by @vitallium in https://github.com/davidcornu/zed-haml/pull/8
>   - Upstream changes:
>     - [Allow multiple types of attributes (ruby/html-style) in any order](https://github.com/vitallium/tree-sitter-haml/commit/d6f7256aca9b39fbdbe7b1f0d4a5598e6be27dd2)
>     - [Add support for ruby variable references in HTML-style attributes](https://github.com/vitallium/tree-sitter-haml/commit/8c8ce9bf4fe617877357e23b2bbeb25354dcb1dc)
>     - [Use @keyword for HAML ruby control and output statements](https://github.com/vitallium/tree-sitter-haml/commit/cd03764d83380821f81b698aedac0127f07a671d)
>   - Upstream diff: https://github.com/vitallium/tree-sitter-haml/compare/ca002c14a373534affb320 …
=> Update HAML extension to v0.1.1

extensions.toml
Release notes:
https://github.com/irmhonde/shades-of-purple-theme/releases/tag/v0.0.6
=> Update shades-of-purple-theme to v0.0.6

.gitmodules, extensions.toml
Adding Spai Zero theme - a sleek dark theme with cyan accents and modern styling.
- Dark background with high contrast
- Cyan accent colors for better visibility
- Carefully crafted syntax highlighting
- Modern and clean design
1. Screenshot1: [screenshots/screenshot1.png](https://github.com/BasaiCorp/zed-spai-zero-theme/blob/59a189b3cc0263c529d661d6843a64cf8e693cd7/screenshots/screenshot1.png)
2. Screenshot2: [screenshots/screenshot2.png](https://github.com/BasaiCorp/zed-spai-zero-theme/blob/59a189b3cc0263c529d661d6843a64cf8e693cd7/screenshots/screenshot2.png)
3. Screenshot3: [screenshots/screenshot3.png](https://github.com/BasaiCorp/zed-spai-zero-theme/blob/59a189b3cc0263c529d661d6843a64cf8e693cd7/screenshots/screenshot3.png)
4. Screenshot4: …
=> Add Spai Zero theme extension

.gitmodules, extensions.toml
Upstream repo and org are gone:
- https://github.com/anya-theme/anya-zed
@cwooju0: Have you moved this repo elsewhere or would you like us to just pull it from the extension store?
Previously:
- https://github.com/zed-industries/extensions/pull/635
=> Remove anya theme

.gitmodules, extensions.toml
Upstream repo is missing:
- https://github.com/srghma/zed-idris2
See also:
- https://github.com/zed-industries/extensions/commit/a1554b532f3d83d8fa04e55b34161757855d3e31
- https://github.com/zed-industries/extensions/pull/1629 (deleted somehow?)
=> Remove idris2

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.1.0
=> Update java to v6.1.0

extensions.toml
updating base16 theme to 0.1.2
have submitted a PR [#12](https://github.com/bswinnerton/base16-zed/pull/12) to increase version number
=> Update base16 to v0.1.2

.github/workflows/ci.yml
This PR bumps the extension CLI version to https://github.com/zed-industries/zed/commit/3e8a07f496de79a3ed53b6a221ede554762611bc.
=> Bump extension CLI version to `3e8a07f`

.gitmodules, extensions.toml
Follow up to https://github.com/zed-industries/extensions/pull/2889 where I added the extension in an incorrect submodule path, and thus the `extensions.toml` wasn't being updated, leading to the extension not being published.
=> Fix Material UI MCP submodule path location

extensions.toml
The new versions of Supabase MCP server put entry point `stdio.js` under `transports/stdio.js`.
=> Update mcp-server-supabase to v0.0.2

extensions.toml
Release notes: https://github.com/zed-extensions/java/releases/tag/v6.2.0
=> Update java to v6.2.0

.gitmodules, extensions.toml
Dram is a lush green and blue color scheme for Zed utilizing the color palette from the science fantasy roguelike epic Caves of Qud. It is evocative of the venerable Solarized Dark by Ethan Schoonover.
=> Add Dram theme extension

extensions.toml
Hi! This pull request updates the Ruby extension to [v0.10.0](https://github.com/zed-extensions/ruby/releases/tag/v0.10.0). As always, here is the changelog with notable changes:
- Debugger prototype for Ruby by @osiewicz in https://github.com/zed-extensions/ruby/pull/96
- feat(herb): add Herb LSP by @vitallium in https://github.com/zed-extensions/ruby/pull/110
- Update herb-language-server executable path by @marcoroth
Thanks!
=> Update Ruby extension to v0.10.0

extensions.toml
This bumps the version of the swift extension to v0.4.2, incorporating https://github.com/zed-extensions/swift/pull/33 which added a Swift debug adapter.
=> Bump swift extension to v0.4.2

extensions.toml
Release notes:
- Fix the previous version can't download lsp binary.
https://github.com/huacnlee/color-lsp/releases/tag/v0.1.1
=> Update color-highlight to v0.1.1

.github/workflows/ci.yml
Incorporates https://github.com/zed-industries/zed/pull/33546, https://github.com/zed-industries/zed/pull/33548
=> Bump extension_cli version to fix debug adapters not being picked up

extensions.toml
There are no functional changes from v0.4.2, this is just to force the extension to be republished with a fixed version of zed_extension_cli (#2927).
=> Bump swift to v0.4.3

extensions.toml
This version includes:
- https://github.com/zed-extensions/ruby/pull/119
- https://github.com/zed-extensions/ruby/pull/111
- https://github.com/zed-extensions/ruby/pull/113
Also, as a result of rebuilding the extension with #2927, the new rdbg debug adapter will be registered successfully.
=> Bump ruby to v0.10.1

extensions.toml
Release notes:
https://github.com/Takk8IS/vercel-mcp-server-for-zed/releases/tag/v1.0.1
=> Update mcp-server-vercel to v1.0.1

extensions.toml
This PR will update the QML extension to version 0.0.4 which allows to set custom CLI arguments for qmlls.
=> Update QML to v0.0.4

.gitmodules, extensions.toml
Move Perplexity extension out of the main zed repo: [zed-industries/zed](https://github.com/zed-industries/zed/) into to [zed-extensions/perplexity](https://github.com/zed-extensions/perplexity/) 
Includes:
- https://github.com/zed-extensions/perplexity/pull/1
- https://github.com/zed-extensions/perplexity/pull/2
- https://github.com/zed-extensions/perplexity/pull/3
- https://github.com/zed-extensions/perplexity/pull/4
Fixes:
- https://github.com/zed-industries/zed/issues/34063
=> Update Perplexity to v0.2.0

extensions.toml
Hi, this pull request updates the Ruby extension from v0.10.1 to [v0.12.0](https://github.com/zed-extensions/ruby/releases/tag/v0.12.0). Here is the list of changes for each release:
```
What's Changed
feat(ruby): add gem uninstall functionality by @vitallium in https://github.com/zed-extensions/ruby/pull/135
Add support for debug locators by @Hawkbawk in https://github.com/zed-extensions/ruby/pull/130
feat(ruby): Add basic support for displaying dbg variables by @vitallium in https://github.com/zed-extensions/ruby/pull/125
Add snippets by @andyw8 in https://github.com/zed-extensions/ruby/pull/53
fix(rdbg): Improve debugger argument handling by @vitallium in https://github.com/zed-extensions/ruby/pull/136
```
```
What's Changed
feat(rdbg): support RUBY_DEBUG env vars for host and port by …
```
=> Update Ruby to v0.12.0

.gitmodules, extensions.toml
Adds a port of the [seoul256](https://github.com/junegunn/seoul256.vim) theme to Zed!
- repo: https://github.com/jcmorrow/seoul256-zed
=> Add seoul256 theme

extensions.toml
Tree-sitter update: https://github.com/tree-sitter-grammars/tree-sitter-requirements/compare/5ad9b7581b3334f6ad492847d007f2fac6e6e5f2...caeb2ba854dea55931f76034978de1fd79362939
=> Update python-requirements to v0.0.2

.gitmodules, extensions.toml
This PR removes the `todo.txt` extension added in https://github.com/zed-industries/extensions/pull/2854.
Extension IDs may not contain `.` characters.
cc @notpeter
=> Remove `todo.txt` extension

.gitmodules, extensions.toml
Change `extensions/slint` submodule origin from [flukejones/zed-slint](https://gitlab.com/flukejones/zed-slint) to [slint-ui/slint](https://github.com/slint-ui/slint).
=> Update Slint extension submodule to official repository

.gitmodules, extensions.toml
Includes: 
- https://github.com/zed-extensions/sql/pull/23
Also updates the submodule URL to point towards the moved remote repository.
=> sql: Bump to 1.1.4

.gitmodules, extensions.toml
- BadRat-in/zed-modern-icons/issues/1
**Vite icon is supported for following files:**
- vite
- vite.config.js
- vite.config.ts
- vite.config.mjs
- vite.config.mts
- vite.config.cjs
- vite.config.cts
=> Update Modern-Icons to v0.4.0

.gitmodules, extensions.toml
Hi! This pull request adds a new extension called `markdownlint` that uses `markdownlint-lsp` NPM package for running `markdownlint` program for linting Markdown files:
Thanks!
=> Add markdownlint extension

extensions.toml
This update fixes highlighting going off-rails when encountering advanced TCL command usage - especially in legacy codebases
- Tree-sitter diff: https://github.com/richnou/tree-sitter-tcl/compare/8f11ac7206a54ed11210491cee1e0657e2962c47...8e5ab6524dc7d081b1e5b980a7bbfba167e72332
=> Updated TCL to v0.0.2

.gitmodules, extensions.toml
A first-class extension for the https://container-use.com/ MCP server.
=> Add extension for the `container-use` MCP server

.gitmodules, extensions.toml
Adds my version of the hot dog stand theme, as well as a more usable version. 
This is an original theme, but it is inspired by the [Windows 3.1 theme](https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/) and the [Vscode Extension](https://marketplace.visualstudio.com/items?itemName=somekittens.hot-dog-stand)
<details>
<summary>Screenshots</summary>
</details>
=> Add Hot Dog Stand

extensions.toml
Bumps fsharp extension to [0.0.7](https://github.com/nathanjcollins/zed-fsharp/releases/tag/0.0.7)
=> Bump fsharp to v0.0.7

extensions.toml
Fixes sticky panel list transparency among other, mainly organizational and tooling tweaks.
=> Update tron-legacy to v1.1.4

extensions.toml
Release notes:
https://github.com/bobbymannino/svelte-snippets-for-zed/releases/tag/v0.0.6
=> Update svelte-snippets to v0.0.6

.gitmodules, extensions.toml
This PR adds the Monokai Original theme extension to the Zed extensions directory.
- **Extension ID**: monokai-og
- **Extension Name**: Monokai Original
- **Version**: 0.1.0
- **Description**: A faithful recreation of the original Monokai theme
- **Repository**: https://github.com/sidwachche/monokai-og-zed
=> Add Monokai Original theme extension

extensions.toml
Update syncs the WASM build of fortran tree-sitter with the current fortran tree-sitter base repo, and adds more fortran file extensions.
=> Update fortran to v0.0.3

extensions.toml
Release notes:
https://github.com/catppuccin/zed/releases/tag/v0.2.23
=> Update catppuccin to v0.2.23

extensions.toml
This PR updates racket extension to v0.1.0 which adds lsp support
=> Update racket to v0.1.0

.gitmodules, extensions.toml
I wrote a little [lsp](https://github.com/nilskch/jj-lsp) to resolve conflicts in the [jj-vcs](https://github.com/jj-vcs/jj) since Zed currently does not have native support for that.
PS: Happy to help adding native support for jj in Zed if there is interest and ongoing development on your side. I currently [colocate](https://jj-vcs.github.io/jj/latest/git-compatibility/#co-located-jujutsugit-repos) the `.git` folder to get the diff and blame, but this comes with a performance hit and I would love to not do that.
=> Add jj-lsp

extensions.toml
Release notes:
https://github.com/bobbymannino/svelte-snippets-for-zed/releases/tag/v0.0.7
=> Update svelte-snippets to v0.0.7

extensions.toml
This PR updates the emmet extension to version 0.0.4
See https://github.com/zed-industries/zed/pull/35305 for more context.
=> emmet: Bump to 0.0.4

.gitmodules, extensions.toml
Adds syntax highlighting support for the authzed/spicedb schema language.
- Extension: https://github.com/mleonidas/authzed-zed
- Tree-sitter: https://github.com/mleonidas/tree-sitter-authzed
=> Add Authzed (SpiceDB) extension

extensions.toml
Fix for upstream changes in release artifact naming.
- https://github.com/zed-extensions/elixir/pull/20
=> Update Elixir to v0.1.10

extensions.toml
Release notes:
https://github.com/catppuccin/zed-icons/releases/tag/v1.21.0
=> Update catppuccin-icons to v1.21.0

extensions.toml
[CHANGELOG v0.1.2](https://github.com/sectore/zed-just-ls/blob/main/CHANGELOG.md#v012---2025-08-05)
=> Update just-ls to v0.1.2

extensions.toml
This PR updates the Emmet extension to v0.0.5.
See https://github.com/zed-industries/zed/pull/36066 for the changes in this version.
=> emmet: Bump to v0.0.5

extensions.toml
This PR updates the Emmet extension to v0.0.6.
See https://github.com/zed-industries/zed/pull/36129 for the changes in this version.
=> emmet: Bump to v0.0.6

extensions.toml
release note: https://github.com/mizdra/css-modules-kit/releases/tag/css-modules-kit-zed%400.1.0
=> Update css-modules-kit to v0.1.0

.gitmodules, extensions.toml
Adds LSP support for GitHub Actions. Since these files are YAML, to avoid conflicting with yaml-language-server, it follows suite how Ansible and Docker Compose do it by copying the YAML grammar but having it identified as a unique language.
- Extension: [neoncitylights/zed-github-actions](https://github.com/neoncitylights/zed-github-actions)
- Tree-sitter: [zed-industries/tree-sitter-yaml](https://github.com/zed-industries/tree-sitter-yaml)
- Language Server: [actions/languageservices](https://github.com/actions/languageservices)
- Language Server (binary): [lttb/gh-actions-language-server](https://github.com/lttb/gh-actions-language-server)
Also, here's a note copied from the extension's README.md (since I figure it's important to point out):
> The LSP provided by the official NPM …
=> Add GitHub Actions extension

.gitmodules, extensions.toml
This PR updates the Emmet extension to v0.0.7.
The Emmet extension now lives at https://github.com/zed-extensions/emmet.
=> emmet: Bump to v0.0.7

extensions.toml
Release notes: https://github.com/valentinegb/zed-groovy/releases/tag/v1.3.0
=> Bump groovy to v1.3.0

.gitmodules, extensions.toml
This PR adds Baml Language support to Zed.
Extension: https://github.com/BoundaryML/zed-baml
Tree-sitter: https://github.com/BoundaryML/tree-sitter-baml
Playground (included in extension): https://github.com/BoundaryML/baml/tree/canary/typescript/packages/playground-common
Language repo: https://github.com/BoundaryML/baml
=> Add BAML extension

.gitmodules, extensions.toml
The zed-objectscript extension initially adds a syntax coloring suppor to Zed for InterSystems ObjectScript via our [tree-sitter-objectscript](https://github.com/intersystems/tree-sitter-objectscript) grammar.
=> Add InterSystems ObjectScript extension

.gitmodules, extensions.toml
This PR removes the becker-theme extension, as the upstream repo is gone: https://github.com/Becker-Theme/zed
=> Remove becker-theme extension

.gitmodules, extensions.toml
Extension: https://github.com/hjr265/zed-gitignore-templates
This extension provides snippets for `.gitignore` files. The snippets are all templates from https://github.com/github/gitignore.
I have written a Bash script (`refresh.sh`) that fetches the templates from that Git repository and turns them into a `git ignore.json` snippets file. I run this script and then track the generated snippets JSON into the extension's Git repository. Whenever there are new or updated templates in that Git repository, I will need to do a refresh and release a new version of the extension.
Perhaps in the future, when the Rust extensions API allows it, we can avoid this and fetch the templates on the fly from the templates Git repository.
I am also including the templates from the root directory only, not …
=> Add Gitignore Templates extension

src/lib/validation.js
This PR updates the validation to reject extensions that declare a `schema_version` that isn't set to `1`.
=> Reject extensions that don't use `schema_version = 1`

extensions.toml
Fixes precedent issues around using `*` in $EXTRACT()/$PIECE() etc.
=> Bump objectscript to v1.0.1

extensions.toml
Release notes:
https://github.com/ocsmit/zed-r/releases/tag/v0.2.4
=> Update r to v0.2.4

extensions.toml
This PR updates the Clojure extension to v0.2.1
Relevant changes: 
- https://github.com/zed-extensions/clojure/pull/9
=> clojure: Bump to v0.2.1

extensions.toml
This PR updates the Zig extension to v0.3.5
Includes:
- https://github.com/zed-extensions/zig/pull/6
- https://github.com/zed-extensions/zig/pull/1
=> zig: Bump to v0.3.5

extensions.toml
This PR updates the Kotlin extension to v0.1.3
Includes:
- https://github.com/zed-extensions/kotlin/pull/37
- https://github.com/zed-extensions/kotlin/pull/38
=> kotlin: Bump to v0.1.3

extensions.toml
This PR updates the Kotlin extension to v0.1.4
Includes:
- https://github.com/zed-extensions/kotlin/pull/40
=> kotlin: Bump to v0.1.4

extensions.toml
This PR updates the Elixir extension to v0.2.0.
This version brings support for [Expert](https://github.com/elixir-lang/expert), the official Elixir language server.
=> elixir: Bump to v0.2.0

extensions.toml
This PR updates the Elixir extension to v0.2.1.
Includes:
- https://github.com/zed-extensions/elixir/pull/28
=> elixir: Bump to v0.2.1

extensions.toml
Release notes:
https://github.com/GeneaLabs/zed-phpcs-lsp/releases/tag/v0.1.6
=> Update phpcs to v0.1.6

.gitmodules, extensions.toml
This is a language extension that provides support for [Podman Quadlet](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html) files using the [quadlet-lsp](https://github.com/onlyati/quadlet-lsp) language server.
=> Add Quadlet extension

extensions.toml
This PR updates the Nu extension to version v0.0.7.
Includes:
- https://github.com/zed-extensions/nu/pull/12
- https://github.com/zed-extensions/nu/pull/13
=> nu: Bump to v0.0.7

extensions.toml
This PR updates the Nix extension to v0.1.2.
Includes:
- https://github.com/zed-extensions/nix/pull/30
- https://github.com/zed-extensions/nix/pull/31
- https://github.com/zed-extensions/nix/pull/32
=> nix: Bump to v0.1.2

extensions.toml
- Move repo from [m1guer/basedpyright-zed](https://github.com/m1guer/basedpyright-zed) to [pub-struct/basedpyright-zed](https://github.com/pub-struct/basedpyright-zed)
=> Update basedpyright to v0.1.3

.gitmodules, extensions.toml
While I'm porting my [VSCode theme](https://github.com/subframe7536/vscode-theme-maple) to Zed, I found someone already have already port it (extension id: `maple-theme`), but lack some font styles in syntax and use the old color palette, also the project seems inactive. So I want to submit a new theme extension here.
=> Add Maple theme

extensions.toml
Release notes:
https://github.com/huacnlee/zed-autocorrect/releases/tag/v0.1.2
=> Update autocorrect to v0.1.2

.gitmodules, extensions.toml
This PR updates the TOML extension to v0.1.5.
The TOML extension now lives at https://github.com/zed-extensions/toml.
=> toml: Bump to v0.1.5

extensions.toml
This PR updates the Elixir extension to v0.2.2.
Includes:
- https://github.com/zed-extensions/elixir/pull/19
- https://github.com/zed-extensions/elixir/pull/34
=> elixir: Bump to v0.2.2

extensions.toml
This PR updates the Snippets extension to v0.0.6.
See https://github.com/zed-industries/zed/pull/37567 for the changes in this version.
=> snippets: Bump to v0.0.6

extensions.toml
Closes https://github.com/zed-industries/zed/issues/37683
This PR updates the PHP extension to v0.4.2.
Includes:
- https://github.com/zed-extensions/php/pull/40
- https://github.com/zed-extensions/php/pull/48
- https://github.com/zed-extensions/php/pull/49
=> php: Bump to v0.4.2

extensions.toml
This PR updates the material-icon-theme extension to v1.1.0.
=> material-icon-theme: Bump to v1.1.0

extensions.toml
Release notes:
https://github.com/catppuccin/zed-icons/releases/tag/v1.22.0
=> Update catppuccin-icons to v1.22.0

.gitmodules
This PR fixes the entry in `.gitmodules` for the `fiber-snippets` extension.
=> fiber-snippets: Fix `.gitmodules` entry

extensions.toml
Hi! This pull request updates the Ruby extension to v0.13.3. You can find the release notes [here](https://github.com/zed-extensions/ruby/releases/tag/v0.13.3). Thank you!
=> Update Ruby to v0.13.3

extensions.toml
Now that `0.205.4` is stable, I've merged the PR that bumps the `zed_extension_api` to improve Windows compatibility.
This version only contains this change:
https://github.com/florian-sanders/zed-stylelint/releases/tag/1.0.2
=> Update Stylelint to v1.0.2

extensions.toml
Hi! This pull request updates the `markdownlint` extension to v0.3.0. You can find the release notes [here](https://github.com/vitallium/zed-markdownlint/releases/tag/v0.3.0). Thanks!
=> Update markdownlint to v0.3.0

extensions.toml
Release notes:
https://github.com/irmhonde/monospace-icon-theme/releases/tag/v0.1.4
=> Update monospace-icon-theme to v0.1.4

src/lib/fs.js, src/lib/test_licenses/test_apache_2_license, src/lib/test_licenses/test_gpl_v3_license, src/lib/test_licenses/test_mit_license, src/lib/validation.js, src/lib/validation.test.js, src/package-extensions.js
This PR adds validation to check if an extension repository contains either an MIT or Apache 2 license. If one is not present, it throws an error.
The pattern checking for MIT and Apache 2.0 licensing is a bit simple, it just verifies the first line or sentence of each block from each license. I could've matched on the whole license, but that felt a bit extreme; we can adjust if we find this isn't ideal.
=> Add license validator

extensions.toml
Release notes: 
- https://github.com/davidcornu/zed-haml/releases/tag/v0.1.2
> * Change comment symbol to `#-` for silent HAML comments by @wilfison in https://github.com/davidcornu/zed-haml/pull/9
- https://github.com/davidcornu/zed-haml/releases/tag/v0.1.3
> - Add a `LICENSE` file (MIT)
>     This is a new requirement for extensions: https://zed.dev/docs/extensions/developing-extensions#extension-license-requirements
=> Update HAML extension to v0.1.3

extensions.toml
Update `prisma-mcp` to v0.2.0 for Windows support.
Release notes: https://github.com/aqrln/prisma-mcp-zed/releases/tag/v0.2.0
Ref: https://github.com/zed-industries/extensions/issues/3350
=> Update `prisma-mcp` to v0.2.0

src/lib/test-licenses/utilities.js
This is likely not that big of a deal, but I wanted to cache this test license content so that subsequent tests within the same test module wouldn't need to open and read from these files again.
We could inline these sample licenses, but mixing that large of content into source code feels bad, so I used separate files.
=> Cache test license content for subsequent test runs

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-figma/releases/tag/v0.2.0
=> Update mcp-server-figma to v0.2.0

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-github/releases/tag/v0.1.0
=> Update mcp-server-github to v0.1.0

extensions.toml
Release notes:
https://github.com/LoamStudios/zed-mcp-server-linear/releases/tag/v0.1.0
=> Update mcp-server-linear to v0.1.0

extensions.toml
This PR bump the version of the Java extension to 6.5.0.
Includes: 
- https://github.com/zed-extensions/java/pull/79
- https://github.com/zed-extensions/java/pull/84
- https://github.com/zed-extensions/java/pull/85
- https://github.com/zed-extensions/java/pull/87
=> java: Bump to v6.5.0

extensions.toml
Hi! This pull request updates the Ruby extension to v0.13.5. You can find release notes on [the release page](https://github.com/zed-extensions/ruby/releases/tag/v0.13.5). Thank you!
=> Update Ruby to v0.13.5
